docs/RELEASE.md, scripts/ghpages-deploy, scripts/publish-release
Modify scripts for publishing to gh-pages and public npm.
- Changed `href` in index.html to work with public ghpages in `ghpages-deploy` script.
- Removed enterprice registry code from `publish-release` script.
=> feature(public npm)

README.md, docs/DEVELOPER_GUIDE.md
Adding badges and updating readme
- gitter badge
- npm badge
- setup in readme
=> update(readme): badges & setup in readme

src/app/components/docs/overview/overview.component.html
Talk about the great work you've done!
- One
- Two
- Three
I ran into an issue when I tried to clone with" git clone git@github.com:teradata/covalent-quickstart.git ". updated it to correct repo url.
=> Updated git clone to correct repo url.

README.md, docs/CHANGELOG.md, src/platform/file-upload/package.json, src/platform/highlight/package.json, src/platform/http/package.json, src/platform/markdown/package.json
First draft of CHANGELOG for 0.6.0.
- CHANGELOG.md file in docs/
=> Feature/changelog 0.6.0

config/karma.conf.js, config/karma.travis.conf.js, src/app/app.component.spec.ts, src/system-config.ts, src/tsconfig.json
Making sure karma runs fine in rc6 and see what needs to be done for it to execute without issues. https://github.com/Teradata/covalent/issues/57
- New karma set up.
- Intermediate test case as example.
=> Feature/karma rc6 (code-health)

src/app/components/layouts/manage-list/manage-list.component.html
Manage list example code was wrong
- Fixed code snippet
=> fix(layout-docs): manage-list tutorial

src/app/components/style-guide/resources/resources.component.html
=> update(resources): axure links

docs/CHANGELOG.md
Updating changelog to have `0.7.0` logs.
=> update(changelog): 0.7.0

src/platform/http/http-rest.service.ts
Bug fix for patch request in `RESTService`
=> check for 200 in patch request

package.json, src/platform/charts/package.json, src/platform/chips/package.json, src/platform/core/package.json, src/platform/data-table/package.json, src/platform/file-upload/package.json, src/platform/highlight/package.json, src/platform/http/package.json, src/platform/json-formatter/package.json, src/platform/markdown/package.json, src/platform/paging/package.json, src/platform/search/package.json
Updated the contributors list in package.json
package.json changes
=> Updating contributors list in package.json

scripts/rollup.js, src/platform/search/search-input/search-input.component.ts
Added debounceTime operator to the rollup file. Fixes #161
=> MINOR: Missing debounceTime operator

docs/CHANGELOG.md
Updated changelog for 0.9 release.
=> feat(changelog): updated 0.9 commits

src/platform/core/paging/_paging-bar-theme.scss, src/platform/core/paging/paging-bar.component.html, src/platform/core/paging/paging-bar.component.scss
Replaced `md-icon-buton` and `md-menu` with `md-select`
=> feature(paging): usage of md-select as menu

src/platform/core/file/file-upload.component.html, src/platform/core/paging/paging-bar.component.html, src/platform/core/search/search-box/search-box.component.html, src/platform/core/search/search-input/search-input.component.html
https://github.com/Teradata/covalent/issues/210
Make buttons type="button" so its not assumed they are a type="submit" by a form element
=> bugfix(file): stop submit when enter is pressed inside a form. closes(#210)

README.md, docs/CONTRIBUTING.md, docs/DEVELOPER_GUIDE.md, docs/GETTING_STARTED.md
https://github.com/Teradata/covalent/issues/178
Added improvements to `README.md` files for better instructions.
- docs/GETTING_STARTED.md
=> feature(docs): getting started docs + improvements. (closes #178)

README.md, docs/UPGRADE.md
Added documentation steps on how to upgrade `@covalent` linking to [covalent-quickstart](https://github.com/Teradata/covalent-quickstart) upgrade PR's
=> feature(docs): initial UPGRADE.md that links to `covalent-quickstart` upgrade PR's

src/platform/http/interceptors/http-interceptor.service.ts
Fix for `rxjs` dependency changes which caused concurrency request failure. (when multiple requests were thrown at the same time, sometimes one or more would fail)
=> bugfix(http): solved request concurrency issue.

README.md
Fix the badge so it properly points to `develop`
=> bugfix(coverage-badge): make coverage badge point to the develop branch.

src/platform/core/common/common.module.ts, src/platform/core/common/services/router.path.service.ts, src/platform/core/common/services/router.service.spec.ts
Upstreaming Router Service that keeps track of last used Route.  Good for backbutton.  Also unit test to test this service
- modified:   src/platform/core/common/common.module.ts
- new file:   src/platform/core/common/services/router.path.service.ts
- new file:   src/platform/core/common/services/router.service.spec.ts
=> Upstream Router Service that keeps track of last used Route

src/platform/core/expansion-panel/expansion-panel.component.spec.ts
Unit tests for Expansion Panel
Closes #289
- npm run test and see all the test cases passing including Expansion Panel.
=> code-health(expansion-panel): Initial unit tests for expansion-panel component. (closes #289)

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, docs/CHANGELOG.md, docs/UPGRADE.md, src/platform/charts/package.json
Includes the commits that are gonna be part of the Beta-1 release.
=> Changelog for @covalent/beta.1

README.md
Browser support based on Flexbox:
=> add(readme): browser support

.travis.yml, scripts/nightly-publish
No way to test than pushing stuff :)
=> bugfix(travis): fixing travis to use `github` token so it publishes the night build.

angular-cli.json, package.json, src/app/components/components/ngx-charts/data.ts, src/app/components/components/ngx-charts/ngx-charts.component.html, src/app/components/components/ngx-charts/ngx-charts.component.ts
Upgraded ngx-charts
- ngx-charts using latest version `4.1.1`
=> feature(ngx-charts): ngx upgrade to latest

src/app/components/home/home.component.html
Typo fix on home page FAQ section
=> Typo Fix: Anguer -> Angular

src/app/components/components/data-table/data-table.component.html
Typo fix  in data table code example
=> docs(data-table): fix typo in code example.

src/app/components/components/data-table/data-table.component.html, src/app/components/components/data-table/data-table.component.ts, src/platform/core/data-table/data-table.component.html, src/platform/core/data-table/data-table.component.ts
A property is added to ITdDataTableColumn check whether column is sortable or not
``` js 
columns: ITdDataTableColumn[] = [
{ name: 'sku', label: 'SKU #', tooltip: 'Stock Keeping Unit', sortable: true },
{ name: 'item', label: 'Item name' },
{ name: 'price', label 'Price (US$)', numeric: true, format: v => v.toFixed(2) },
];
```
``` js
<td-data-table
[data]="filteredData"
[columns]="columns"
[sortBy]="sortBy"
[sortOrder]="sortOrder"
(sortChange)="sort($event)">
</td-data-table>
```
- A property is added to ITdDataTableColumn check whether column is sortable or not.
- Updated Docs Accordingly.
- Updated `data-table.component.html` 
``` js 
<th td-data-table-column
*ngFor="let column of columns"
[name]="column.name"
[numeric]="column.numeric"
[active]="_sortable && column === _sortBy" …
```
=> feature(data-table): configurable sortable column with td-data-table. (closes #347)

src/platform/core/data-table/data-table.component.ts
Force change detection cycle when `ngModel` array changes. (not internal values)
=> fix(data-table): force change detection when model array is changed

docs/GETTING_STARTED.md
closes( #410)
Update Material styles from md-* to mat-*
- Revision to GETTINGSTARTED.md
None, doc change
=> chore(): update docs to updated Material style prefixes

src/app/components/components/data-table/data-table.component.html
Talk about the great work you've done!
- One
- Two
- Three
=> fix mismatch of the basicData property

scripts/compile-sass.js, scripts/sass-importer.js
=> chore(sass): abstract sass-importer from compiler-sass script

scripts/rollup.js, src/platform/core/chips/chips.component.ts, src/platform/core/search/search-input/search-input.component.ts, src/polyfills.ts
Remove general import from polyfill so we need to get the errors of the individual functions used in our components.
- fix(chips): added rxjs timer import
- fix(search): add rxjs skip import
- chore(rollup): update bundle with rxjs imports
=> feat(rxjs): add individual rxjs imports in needed modules.

package.json, src/platform/core/package.json, src/platform/dynamic-forms/package.json, src/platform/highlight/package.json, src/platform/http/package.json, src/platform/markdown/package.json
Small patch release to include a bugfix in stepper and better Getting started docs
- https://github.com/Teradata/covalent/pull/503
- https://github.com/Teradata/covalent/pull/505
=> chore(): bump to beta.3-2

package.json, src/platform/core/package.json, src/platform/dynamic-forms/package.json, src/platform/highlight/package.json, src/platform/http/package.json, src/platform/markdown/package.json
Updated the contributors list in package.json
- package.json changes
=> chore(): updating contributors list in package.json

src/app/components/components/data-table/data-table.component.html
Talk about the great work you've done!
- One
- Two
- Three
=> fix (data-table): missing colon in example

src/app/components/components/data-table/data-table.component.html
* Added missing selectedRows property on the data tables component description. Closes #441
* ng serve --aot still works
* ng lint no changes
* npm run test not working (chips related)
=> fixed(docs): missing properties on data table documentation

src/platform/core/dialogs/prompt-dialog/prompt-dialog.component.ts
=> fix(): aot build break with prompt commit

src/platform/core/file/services/file.service.ts
Make progress upload based on upload, not need backend compatible
=> fix(file-upload): make progress based on upload API

src/platform/core/file/services/file.service.ts
Reverts Teradata/covalent#649
Didnt notice it was pointing to master, rather than develop
=> Revert "fix(file-upload): make progress based on upload API"

src/platform/core/file/services/file.service.ts
Make progress upload based on upload, not need backend compatible
=> make progress based on upload API

src/app/components/docs/angular/angular.component.html, src/app/components/docs/creating/creating.component.html
=> Docs tweaks

src/platform/core/common/styles/_variables.scss
Fixed breakpoints in _variables.scss
-sm, -md, -lg were all incorrect.
=> Fixed breakpoints

src/platform/core/layout/layout.module.ts, src/platform/core/layout/navigation-drawer/navigation-drawer.component.html, src/platform/core/layout/navigation-drawer/navigation-drawer.component.ts
=> feature: navigation-drawer toolbar template

package.json, yarn.lock
- Upgrade to latest angular/cli
=> chore(): upgrade to `@angular/cli@1.4.1`

docs/CHANGELOG.md, src/app/components/components/components.component.html, src/app/components/design-patterns/design-patterns.component.html, src/app/components/docs/docs.component.html, src/app/components/layouts/layouts.component.html, src/app/components/style-guide/style-guide.component.html, src/app/components/toolbar/toolbar.component.html, src/app/components/toolbar/toolbar.component.ts
The changelog for beta.7 release!
=> chore(): beta.7 release changelog

docs/CHANGELOG.md
Typo fixed in the documentation
=> Typo fixed

src/platform/core/data-table/data-table.component.ts
- Return unselected row when using single row selection mode in data-table
closes https://github.com/Teradata/covalent/issues/881
=> fix(data-table): show which column was deselected when using single selection mode

src/platform/core/data-table/README.md
Data table readme was missing rowClick event.
=> Updates data-table readme

docs/CHANGELOG.md
The angular material project is in 2.0 betas. :smile: 
- Update version numbers in changelog
=> Fix Angular Material version number

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, src/app/components/templates/templates.component.html
Adding Stackblitz
- Update template tooltips
- Update Github PR/Issue templates
- Update readme link w/ Stackblitz
=> feat(): StackBlitz templates

docs/CHANGELOG.md, src/app/components/toolbar/toolbar.component.html, src/app/components/toolbar/toolbar.component.ts
Changelog and notification updates for rc release.
=> chore(): changelog for covalent@rc.0

docs/CHANGELOG.md, src/app/components/style-guide/typography/typography.component.html, src/app/components/toolbar/toolbar.component.html, src/app/components/toolbar/toolbar.component.ts
Changelog and home notification updates for rc.1
=> chore(): update changelog for rc.1 release

src/platform/core/message/message.component.scss
Show message component properly in RTL
Part of https://github.com/Teradata/covalent/issues/323
=> feat(message): support RTL

src/platform/markdown/README.md
Fixed the include in the docs.
- Docs
=> Fixed markdown include

src/app/components/components/data-table/data-table.component.html
Fixed sample code not up to date with demo code on Datatable with components example
- modified:   src/app/components/components/data-table/data-table.component.html
=> fix(docs): Fix sample code not up to date with demo code on Datatable

src/app/components/components/components.component.ts, src/app/components/components/components.module.ts, src/app/components/components/components.routes.ts, src/app/components/components/flavored-markdown/flavored-markdown.component.html, src/app/components/components/flavored-markdown/flavored-markdown.component.ts, src/app/components/components/overview/overview.component.ts, src/platform/flavored-markdown/_flavored-markdown-theme.scss, src/platform/flavored-markdown/flavored-markdown.component.scss, src/platform/flavored-markdown/flavored-markdown.component.ts
- Demos and example code on usage
Note: separate PR will be done for README with installation and setup
=> docs(flavored-markdown): add demo and example code

src/platform/flavored-markdown/README.md, src/platform/flavored-markdown/flavored-markdown.component.ts
=> docs(flavored-markdown): add README for setup and usage

src/platform/core/chips/chips.component.ts
Fix another memory leak in Chips due to unsubscribe from `his.inputControl.valueChanges` subscription
bugfix
=> fix(chips): Fix another memory leak in Chips

src/platform/core/steps/_steps-theme.scss, src/platform/core/steps/nav/nav-step-link/nav-step-link.component.html, src/platform/core/steps/nav/nav-step-link/nav-step-link.component.ts, src/platform/core/steps/step-header/step-header.component.html, src/platform/core/steps/step-header/step-header.component.ts
Fixed issue where tabbing through steps wasnt working properly.
=> fix(nav-steps): fix a11y issue with tabs

.browserslistrc, package.json, scripts/post-ng-packagr-build.js
Rename file so its properly picked up by autoprefixer and remove other configurations.
=> chore(): rename browserlist to .browserslistrc

README.md, src/app/components/style-guide/resources/resources.component.html
Minor fixes to documentation to close a couple PRs.
closes https://github.com/Teradata/covalent/issues/1376
closes https://github.com/Teradata/covalent/issues/1386
=> fix(documentaion): minor updates to docs

src/platform/core/sidesheet/sidesheet.component.scss
=> fix: sidesheet action styling

package.json
Allow pre commit hook to only attempt to prettify file types we specify.
=> fix(prettier): add pattern to pre commit hook

.travis.yml, commitlint.config.js, package-lock.json, package.json, scripts/ci/travis-script.sh
- Adds a pre commit hook to validate commit messages using commitlint 
- Adds a travis script to verify commit messages. See the error that is thrown here https://travis-ci.org/Teradata/covalent/jobs/565596117 Not the most helpful message, but at least it says a commit message is malformed.
- Using [commitlint/config-angular](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-angular). Should we use that or [commitlint/config-conventional](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional)?
=> ci(commitlint): add commitlint

angular.json, scripts/build-release, src/platform/utilities/functions/index.ts, src/platform/utilities/functions/placeholder.ts, src/platform/utilities/index.ts, src/platform/utilities/karma.conf.js, src/platform/utilities/ng-package.js, src/platform/utilities/package.json, src/platform/utilities/public_api.ts, src/platform/utilities/test.ts, src/platform/utilities/tsconfig.lib.json, src/platform/utilities/tsconfig.spec.json, src/platform/utilities/tslint.json
Scaffolding directory for utilities module.
- Directory structure for utilities (with placeholder function)
- Added to build script
Missing things:
- Nightly build
- Documentation scaffolding and README
=> chore(utilities): scaffolding for utilities module

src/platform/flavored-markdown/flavored-markdown.component.ts, src/platform/markdown/markdown-utils/markdown-utils.spec.ts, src/platform/markdown/markdown-utils/markdown-utils.ts, src/platform/markdown/markdown.component.ts
=> test(markdown-utils): test helper functions

src/platform/core/common/functions/convert.spec.ts, src/platform/experimental/help/draggable-help-window-dialog/draggable-help-window-dialog.service.spec.ts, src/platform/experimental/help/draggable-help-window-dialog/draggable-help-window-dialog.service.ts, src/platform/experimental/help/help-window/help-window.component.spec.ts, src/platform/experimental/help/help.component.spec.ts, src/platform/experimental/help/help.module.ts
test(draggable-help-window): add tests
=> test(draggable-help-window): add tests

package-lock.json, src/app/components/components/components.component.html, src/app/components/echarts/components.component.ts, src/app/components/echarts/overview/overview.component.ts, src/app/components/echarts/types/pie/pie.component.html, src/app/components/echarts/types/pie/pie.component.ts, src/app/components/echarts/types/types.module.ts, src/app/components/echarts/types/types.routes.ts, src/platform/echarts/README.md, src/platform/echarts/bar/README.md, src/platform/echarts/base/axis/README.md, src/platform/echarts/base/dataset/README.md, src/platform/echarts/base/public-api.ts, src/platform/echarts/base/series/series.interface.ts, src/platform/echarts/graph/README.md, src/platform/echarts/line/README.md, src/platform/echarts/pie/README.md, src/platform/echarts/pie/index.ts, src/platform/echarts/pie/package.json, src/platform/echarts/pie/pie.component.ts, src/platform/echarts/pie/pie.module.ts, src/platform/echarts/pie/public-api.ts, src/platform/echarts/public-api.ts, src/platform/echarts/sankey/README.md, src/platform/echarts/scatter/README.md, src/platform/echarts/toolbox/README.md, src/platform/echarts/tooltip/README.md, src/platform/echarts/tree/README.md, src/platform/echarts/treemap/README.md
- Pie Charts
- Demo For Pie Charts
=> feat(pie_chart): add pie charts to covalent

src/platform/flavored-markdown/flavored-markdown-loader/flavored-markdown-loader.component.html, src/platform/flavored-markdown/flavored-markdown-loader/flavored-markdown-loader.component.scss, src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.html, src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.ts, src/platform/markdown-navigator/markdown-navigator.component.html, src/platform/markdown-navigator/markdown-navigator.component.scss
Add styling tweaks to improve styling and alignment of items + some fixed on list scrolling and labels.
=> feat(markdown-nav): styling tweaks

src/app/components/components/overview/overview.component.ts, src/app/components/toolbar/toolbar.component.html, src/app/components/toolbar/toolbar.component.ts
Add the new components or functions in the notifications toolbar.
=> docs(): update new notifications toolbar

src/app/components/components/overview/overview.component.html
Remove broken link to external echarts docs.
=> fix(): remove echarts link from overview

src/platform/dynamic-forms/dynamic-element.component.ts, src/platform/dynamic-forms/dynamic-forms.component.ts, src/platform/dynamic-forms/dynamic-forms.module.ts, src/platform/flavored-markdown/flavored-markdown.component.ts, src/platform/highlight/highlight.component.ts, src/platform/markdown-navigator/markdown-navigator-window-service/markdown-navigator-window.service.spec.ts, src/platform/markdown/markdown.component.spec.ts, src/platform/markdown/markdown.component.ts
Run on dynamic forms and markdown components
=> feat(tslint): run on dynamic forms and markdown components

package.json, src/platform/core/common/configs/tslint/tslint.json, src/platform/core/expansion-panel/expansion-panel.component.spec.ts, src/platform/core/expansion-panel/expansion-panel.component.ts, src/platform/core/file/directives/file-drop.directive.ts, src/platform/core/file/directives/file-select.directive.ts, src/platform/core/file/file-input/file-input.component.ts, src/platform/core/file/file-upload/file-upload.component.html, src/platform/core/file/file-upload/file-upload.component.ts, src/platform/core/file/services/file.service.ts, src/platform/core/json-formatter/json-formatter.component.ts, src/platform/core/layout/layout-card-over/layout-card-over.component.ts, src/platform/core/layout/layout-manage-list/layout-manage-list.component.ts, src/platform/core/layout/layout-nav-list/layout-nav-list.component.ts, src/platform/core/layout/layout-nav/layout-nav.component.ts, src/platform/core/layout/layout.component.ts, src/platform/core/layout/navigation-drawer/navigation-drawer.component.ts, src/platform/core/loading/directives/loading.directive.ts, src/platform/core/loading/loading.component.ts, src/platform/core/loading/services/loading.factory.ts, src/platform/core/loading/services/loading.service.spec.ts
Targeting #1539
- file-upload: `cancel()` -> `_cancel()`
=> feat(tslint): expansion-panel, file, json-formatter, layout, loading

package.json, src/app/components/components/steps/steps.component.ts, src/platform/core/common/configs/tslint/tslint.json, src/platform/core/loading/services/loading.service.ts, src/platform/core/media/services/media.service.ts, src/platform/core/message/message.component.ts, src/platform/core/paging/paging-bar.component.spec.ts, src/platform/core/paging/paging-bar.component.ts, src/platform/core/search/search-box/search-box.component.ts, src/platform/core/search/search-input/search-input.component.ts, src/platform/core/steps/nav/nav-step-link/nav-step-link.component.ts, src/platform/core/steps/step.component.ts, src/platform/core/steps/steps.component.ts
=> feat(tslint): run on media , message, paging, search, steps

src/platform/code-editor/code-editor.component.spec.ts, src/platform/core/common/configs/tslint/tslint.json, src/platform/core/sidesheet/sidesheet.component.ts, src/platform/dynamic-forms/dynamic-forms.component.spec.ts, src/platform/dynamic-forms/dynamic-forms.component.ts, src/platform/echarts/base/axis/axis.interface.ts, src/platform/echarts/base/base.types.ts, src/platform/echarts/base/series/series.component.ts, src/platform/echarts/base/series/series.interface.ts, src/platform/echarts/graph/graph.component.ts, src/platform/echarts/line/line.component.ts, src/platform/echarts/scatter/scatter.component.ts, src/platform/echarts/toolbox/toolbox.component.ts, src/platform/echarts/tooltip/README.md, src/platform/echarts/tooltip/tooltip.component.ts, src/platform/highlight/highlight.component.ts, src/platform/http/actions/methods/abstract-method.decorator.ts, src/platform/http/actions/methods/delete.decorator.ts, src/platform/http/actions/methods/get.decorator.ts, src/platform/http/actions/methods/patch.decorator.ts, src/platform/http/actions/methods/post.decorator.ts, src/platform/http/actions/methods/put.decorator.ts
- Re-enabled some rules I had disabled and fixed the issues.
- Sorted the rules
- Targeting #1539 
N/A
=> fix(tslint): fix remaining issues

package.json
add nightly build for markdown navigator package
https://github.com/Teradata/covalent-markdown-navigator-nightly
=> feat(markdown-navigator): add nightly for package

src/app/components/shared/demo-tools/demo.component.ts, src/app/content/echarts/echarts-content.ts, src/app/content/echarts/echarts-demos/scatter/demos/scatter-demo-basic/scatter-demo-basic.component.html, src/app/content/echarts/echarts-demos/scatter/demos/scatter-demo-basic/scatter-demo-basic.component.ts, src/app/content/echarts/echarts-demos/scatter/demos/scatter-demo-routing.module.ts, src/app/content/echarts/echarts-demos/scatter/demos/scatter-demo.component.html, src/app/content/echarts/echarts-demos/scatter/demos/scatter-demo.component.ts, src/app/content/echarts/echarts-demos/scatter/demos/scatter-demo.module.ts
Added scaffolding and example for scatter demo
- Scatter example
=> feat(scatter-echarts): add demos, scaffolding, examples

src/app/components/content-container/content-container.component.ts, src/app/components/shared/component-overview/component-overview.component.ts, src/app/components/shared/sidenav-content/sidenav-content.component.ts, src/app/content/components/component-demos/json-formatter/demos/json-formatter-demo-basic/json-formatter-demo-basic.component.ts, src/app/content/components/components.routes.ts, src/app/content/components/components.ts, src/app/content/docs/docs.ts, src/app/content/echarts/echarts-content.ts, src/app/content/echarts/echarts.routes.ts, src/app/content/utilities/content-details/content-api/content-api.component.ts, src/app/content/utilities/content-details/content-details.component.ts, src/app/content/utilities/content-details/content-examples/content-examples.component.ts, src/app/content/utilities/content-details/content-overview/content-overview.component.ts, src/app/content/utilities/utilities-content.ts, src/app/content/utilities/utilities-demos/media/directive/media.component.ts, src/app/content/utilities/utilities-demos/media/service/media.component.ts, src/app/utilities/route-builder.ts, src/app/utilities/route-group.ts
Fix lint errors
- Fixed types
- Added types
- Removed empty blocks
- Fix variable declarations
=> feat(lint-errors): fix types, remove empty blocks n unused imports

src/app/components/content-container/content-container.component.ts, src/app/components/shared/component-overview/component-overview.component.ts, src/app/components/shared/sidenav-content/sidenav-content.component.ts, src/app/content/components/component-demos/json-formatter/demos/json-formatter-demo-basic/json-formatter-demo-basic.component.ts, src/app/content/components/components.routes.ts, src/app/content/components/components.ts, src/app/content/docs/docs.ts, src/app/content/echarts/echarts-content.ts, src/app/content/echarts/echarts-demos/tree/demos/tree-demo-basic/tree-demo-basic.component.html, src/app/content/echarts/echarts-demos/tree/demos/tree-demo-basic/tree-demo-basic.component.ts, src/app/content/echarts/echarts-demos/tree/demos/tree-demo-routing.module.ts, src/app/content/echarts/echarts-demos/tree/demos/tree-demo.component.html, src/app/content/echarts/echarts-demos/tree/demos/tree-demo.component.ts, src/app/content/echarts/echarts-demos/tree/demos/tree-demo.module.ts, src/app/content/echarts/echarts.routes.ts, src/app/content/utilities/content-details/content-api/content-api.component.ts, src/app/content/utilities/content-details/content-details.component.ts, src/app/content/utilities/content-details/content-examples/content-examples.component.ts, src/app/content/utilities/content-details/content-overview/content-overview.component.ts, src/app/content/utilities/utilities-content.ts, src/app/content/utilities/utilities-demos/media/directive/media.component.ts, src/app/content/utilities/utilities-demos/media/service/media.component.ts, src/app/utilities/route-builder.ts, src/app/utilities/route-group.ts
Scaffolding and example for echarts-tree demo
- echarts tree example
=> feat(echarts-tree): Add tree chart demo

src/app/content/utilities/utilities-demos/animations/animations.component.html, src/app/content/utilities/utilities-demos/directives/directives.component.html, src/app/content/utilities/utilities-demos/functions/functions.component.html, src/app/content/utilities/utilities-demos/pipes/pipes.component.html, src/platform/echarts/tooltip/README.md
- Fixed spellings
- Fixed urls
- indentation
=> fix(url): fix spellings and urls

src/app/content/components/component-demos/message/message.component.html, src/platform/core/message/README.md
Clarify usage of td-message. Address https://github.com/Teradata/covalent/issues/1592
- Modified demo HTML to show closing, toggling message
- Modified readme
=> feat(fix-td-message-demo): modified for clarity of usage

build.conf.js
Fixes https://github.com/Teradata/covalent-text-editor-nightly/pull/30
=> fix(text-editor): fix mde placeholder

src/app/components/shared/demo-tools/demo.component.html, src/app/components/shared/demo-tools/demo.component.ts
Added demo title input so demos can have custom defined titles rather than taken from file name.
- demo title component input
=> feat(): configurable demo title

src/app/content/components/component-demos/breadcrumbs/breadcrumbs.module.ts, src/app/content/components/component-demos/breadcrumbs/demos/breadcrumbs-demo-custom-separator/breadcrumbs-demo-custom-separator.component.html, src/app/content/components/component-demos/breadcrumbs/demos/breadcrumbs-demo-custom-separator/breadcrumbs-demo-custom-separator.component.ts, src/app/content/components/component-demos/breadcrumbs/demos/breadcrumbs-demo-resize/breadcrumbs-demo-resize.component.html, src/app/content/components/component-demos/breadcrumbs/demos/breadcrumbs-demo-resize/breadcrumbs-demo-resize.component.ts, src/app/content/components/component-demos/breadcrumbs/demos/breadcrumbs-demo.component.html, src/app/content/components/component-demos/breadcrumbs/demos/breadcrumbs-demo.module.ts
Added missing demos for breadcrumbs
- Added breadcrumb demo with custom separator
- Added breadcrumb demo to showcase resizing and removing breadcrumbs.=
=> fix(breadcrumbs): add missing demos

src/app/content/components/component-demos/breadcrumbs/demos/breadcrumbs-demo.component.html, src/app/content/components/component-demos/markdown/demos/markdown-demo.component.html, src/app/content/components/component-demos/steps/demos/steps-demo-basic/steps-demo-basic.component.html, src/app/content/components/component-demos/steps/demos/steps-demo-basic/steps-demo-basic.component.scss, src/app/content/components/component-demos/steps/demos/steps-demo-basic/steps-demo-basic.component.ts, src/app/content/components/component-demos/steps/demos/steps-demo.component.html, src/app/content/components/component-demos/steps/demos/steps-demo.module.ts, src/app/content/components/component-demos/steps/steps.component.html, src/app/content/components/component-demos/steps/steps.component.ts, src/app/content/components/components.ts
Added missing buttons for stepper
- Added missing buttons for stepper
=> fix(stepper): update demos

package-lock.json
update lock to fix stylelint issue.
=> feat(): update lock

src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-basic/flavored-markdown-demo-basic.component.html, src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-basic/flavored-markdown-demo-basic.component.ts, src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-inline/flavored-markdown-demo-inline.component.html, src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-inline/flavored-markdown-demo-inline.component.ts, src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-loader/flavored-markdown-demo-loader.component.html, src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-loader/flavored-markdown-demo-loader.component.ts, src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-tables/flavored-markdown-demo-tables.component.html, src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-tables/flavored-markdown-demo-tables.component.ts, src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo.component.html, src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo.module.ts, src/app/content/components/component-demos/flavored-markdown/flavored-markdown.component.html, src/app/content/components/component-demos/flavored-markdown/flavored-markdown.component.ts
Added missing demos for flavored markdown
- Added missing demos for flavored markdown
Closes #1634
=> fix(flavored-markdown): add missing demos (#1634)

docs/RELEASE.md, package-lock.json, package.json, scripts/ghpages-deploy, src/app/components/toolbar/toolbar.component.html, src/app/components/toolbar/toolbar.component.scss, src/app/components/toolbar/toolbar.component.ts, src/app/components/toolbar/toolbar.module.ts, src/app/services/github.service.ts
update to release/2.1.x branch for documentation hosting
- drop-down menu to link documentation versions 1 - 3 on gh-pages branch
=> feat(menu) - update to release/2.1.x branch for documentation hosting

docs/RELEASE.md, package.json, scripts/ghpages-deploy, src/app/components/toolbar/toolbar.component.html, src/app/components/toolbar/toolbar.component.scss, src/app/components/toolbar/toolbar.component.ts, src/app/components/toolbar/toolbar.module.ts, src/app/services/github.service.ts, yarn.lock
update to release/1.0.x branch for documentation hosting
- drop-down menu to link documentation versions 1 - 3 on gh-pages branch
=> Feat/doc menu - update to release/1.0.x branch for documentation hosting

src/platform/core/schematics/version-names.ts
Update angular and covalent versions for schematics
=> feat(update-schematics-version): update angular and covalent versions

src/app/content/components/components.routes.ts, src/app/content/components/components.ts
- Removed loading mask for this covalent release
=> fix(loadingmask): remove loading mask from route and ui

src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-children-url/markdown-navigator-demo-children-url.component.ts, src/platform/markdown-navigator/README.md, src/platform/markdown-navigator/markdown-navigator.component.html, src/platform/markdown-navigator/markdown-navigator.component.ts
Add id support to properly use `compareWith` functions and also being able to target specific sections on e2e, guided tours, etc.
=> feat(markdown-nav): add id support

src/platform/core/tab-select/tab-select.component.ts
Material tabs dont check for host resize to realign the ink bar. So we have to add some logic in our tab select wrapper to do so.
This makes sure that if the `tab-select` element changes width, the ink bar will be realigned.
=> fix(tab-select): ink bar realign on host width changes

README.md
Removed quickstart link as it is not a valid link and it is giving 404
- Removed quick start link
=> fix(readme): fix covalent readme links

src/platform/markdown/markdown.component.ts
Fixes https://github.com/Teradata/covalent/issues/1771
=> Literal mid word underscores

package-lock.json, package.json
Fix NPM audit build issue
package json update
=> build(audit): fix npm audit

.github/workflows/ci.yml
fix to remove github workflow action that runs ci on push
=> fix(actions): remove on push action

src/platform/code-editor/code-editor.component.ts
=> fix(code-editor): dispose the event listener when the component is destroyed

.github/workflows/release.yml
using GH token and Github token
=> build(releas): use GH and GITHUB secret

.github/workflows/release.yml
Add NODE_AUTH_TOKEN to use for npm publish step
=> fix(release): add NODE_AUTH_TOKEN variable

libs/angular-dynamic-forms/package.json, libs/angular-echarts/package.json, libs/angular-guided-tour/package.json, libs/angular-highlight/package.json, libs/angular-text-editor/package.json, libs/angular/package.json, libs/markdown-flavored/package.json, libs/markdown-navigator/package.json, libs/markdown/package.json, libs/markdown/src/lib/markdown.component.ts, tsconfig.base.json
Adding correct peer dependency versions for each pacakage.json
- npm package updates
- some linting cleanup
=> fix(package): adding back npm package meta

libs/angular-dynamic-forms/src/lib/dynamic-elements/dynamic-input/dynamic-input.component.html
=> fix(dynamic-forms): material input name overriding (#1895)

libs/angular-text-editor/src/test-setup.ts
fixing the test build step for text-editor
=> build(text-editor): fix test build

libs/markdown-navigator/src/markdown-navigator.component.html, libs/markdown-navigator/src/markdown-navigator.component.ts
Fixing issue with dissappear breadcrumbs within the markdown navigator
- adjusted the history logic to go back to a particular page
```
[
{
"id": "apw1640280478763",
"title": "Organization",
"description": "View company information and create and manage organization administrators.",
"url": "https://raw.githubusercontent.com/Teradata/product-help/master/Vantage/apw1640280478763.md",
"children": [
{
"id": "sja1640281381091",
"title": "Configuration",
"url": "https://raw.githubusercontent.com/Teradata/product-help/master/Vantage/sja1640281381091.md"
},
{
"id": "hrv1640281410572",
"title": "Organization Admins",
"url": "https://raw.githubusercontent.com/Teradata/product-help/master/Vantage/hrv1640281410572.md"
},
{
"id": "sny1640281499378",
"title": "Accounts",
"url": …
```
=> fix(markdown-navigator): fix for markdown navigator breadcrumbs

libs/markdown-navigator/src/markdown-navigator.component.ts
Attempt to jumpt to a navigation item by inferred id from file name while navigating between links in the markdown-navigator component
- from the md file name attempt to infer the ID and jump to a navigation item if found
- default to normal behavior of file look up view markdown loader
=> feat(markdown-navigator): attempt to jump links before loading md file

libs/markdown-navigator/README.md, libs/markdown-navigator/src/markdown-navigator-window/markdown-navigator-window.component.html, libs/markdown-navigator/src/markdown-navigator-window/markdown-navigator-window.component.ts, libs/markdown-navigator/src/markdown-navigator.component.ts
Need the item id to maintain the help panel state
- add EventEmitter to navigator selected item
=> feat(navigator): add EventEmitter to selected item

libs/angular/side-sheet/README.md
update side sheet documentation
=> update sidesheet documentation

libs/angular/file/src/file-input/README.md, libs/angular/file/src/file-upload/README.md
Docs update to reflect the updated outputs from the last NG update
- Updating file upload output
- Updating file input output
=> docs(file): file upload/input docs update

package.json, scripts/ghpages-deploy
changing up the component storybook deployed folder again
=> docs(storybook): changing gh-deploy dir

.github/workflows/ci.yml
using `npx affected` command in the ci github action to run faster
=> build(nx): using affected command for ci build

libs/components/webpack.config.js
fixing build issue where webpack is cleaning out all other packages which is messing up the npm publish process
=> fix(build): fix to npm not publishing all packages

libs/components/stories/item-detail-and-editing.stories.mdx
Adding Item detail guided created by @ecni19 
- storybook written ux guide for item detail patterns
=> docs(components): adding item detail guide from @ecni19

libs/angular-echarts/README.md, libs/components/README.md, libs/components/stories/Introduction.stories.mdx
Adding readme content for components project and echarts project
- Added old readme from 3.x branch for echarts module
- Added new readme for components including getting started content
just look at the readme content
=> docs(readmes): adding readmes for components and echarts

libs/components/vite.config.js
=> fix( components): removing vendor plugin

libs/components/index.html, libs/components/project.json, libs/components/src/app-shell/app-shell.scss, libs/components/src/app-shell/app-shell.stories.js, libs/components/src/app-shell/app-shell.ts, libs/components/src/list/list-expansion.ts, libs/components/src/list/list-item.ts, libs/components/src/list/list.ts, libs/components/theme/theme.scss, libs/components/vite.config.js
Some minor CSS fixes for app shell navigation
- CSS updates for the app shell component
- Fixes an issue when opening/collapsing the hamburger menu
- Added a serve command to see the testing app for components
=> fix(components): app-shell navigation style updates

libs/components/vite.config.js
Reverting some changes added early to vite.config.js causing Angular build to fail
=> fix(components): reverting vit.config.js to earlier version

.releaserc, apps/docs-app/src/app/content/components/component-demos/flavored-markdown/flavored-markdown.component.html, apps/docs-app/src/app/content/components/component-demos/flavored-markdown/flavored-markdown.component.ts, apps/docs-app/src/app/content/components/component-demos/highlight/demos/highlight-demo-copy-code/highlight-demo-copy-code.component.html, apps/docs-app/src/app/content/components/component-demos/highlight/demos/highlight-demo-ts/highlight-demo-ts.component.html, apps/docs-app/src/app/content/components/component-demos/highlight/demos/highlight-demo.component.html, libs/angular-highlight/_highlight-theme.scss, libs/angular-highlight/src/lib/copy-code-button/copy-code-button.component.html, libs/angular-highlight/src/lib/copy-code-button/copy-code-button.component.scss, libs/angular-highlight/src/lib/copy-code-button/copy-code-button.component.ts, libs/angular-highlight/src/lib/highlight.component.html, libs/angular-highlight/src/lib/highlight.component.scss, libs/angular-highlight/src/lib/highlight.component.ts, libs/angular-highlight/src/lib/highlight.module.ts, libs/markdown-flavored/src/lib/flavored-markdown.component.ts
(cherry picked from commit 8bfb6820deca222080b3b026de5a336d4d33d221)
- One
- Two
- Three
=> feat: add raw code toggle to highlight component and update theme

libs/angular-highlight/src/lib/copy-code-button/copy-code-button.component.ts, libs/angular-highlight/src/lib/highlight.component.ts
Removing unintended console logs
=> fix: remove console logs

apps/docs-app/src/app/content/components/component-demos/highlight/demos/highlight-demo-copy-code/highlight-demo-copy-code.component.html, libs/angular-highlight/_highlight-theme.scss
Applying change from 4.x.x branch
=> fix: use is-dark for highlight dark theme

libs/components/stories/Introduction.stories.mdx
Fix links to not break navigation in production
=> fix: correction in links to not break in production

libs/components/theme/_mixins.scss
Fix issues for dark style theme
=> fix: dark style issues

libs/icons/package.json, libs/icons/project.json
Adding the icons package as an NX project & including a package.json for publising to NPM
New package will be published as `@covalent/icons`
=> feat(icons): adding icons as nx lib & npm package

libs/angular-echarts/package.json, scripts/version-placeholder.js
Adjusting the placeholder values for ECharts stat package. This value was not being correctly replaced prior to being pushed to NPM
=> build(echarts): modifying echarts stats package version placeholder

apps/knapsack/data/blocks/block.Fv2gGxz6Kl.json
Edit the target field for change event of checkbox component to 'cv-checkbox'
=> docs(knapsack): edit the target for change event to cv-checkbox

docs/COMPONENTS_QUICKSTART.md, docs/COMPONENTS_THEMING.md, libs/components/stories/Introduction.stories.mdx
Adding some documenation for `@covalent/components` for getting started and theming
=> docs(components): adding quick start and theming guides

libs/components/src/card/card-base.ts
styling fix for cards that are non-interactive
- using primary card class only when card has ripple affect and is primary action only
=> fix(components): styling adjustment to cards web component

libs/angular/dialogs/src/resizable-draggable-dialog/resizable-draggable-dialog.ts
=> fix(icons): fix material icons

libs/markdown/src/lib/markdown.component.ts
Updated comment
Updated comment
=> fix(markdown): updates comment

apps/docs-app/src/app/content/components/component-demos/highlight/demos/highlight-demo-copy-code/highlight-demo-copy-code.component.html, libs/angular-highlight/_highlight-theme.scss
Missed a commit that needed to be on 4.x.x
=> fix(): use is-dark for highligh dark theme (#2053)

package-lock.json
updating lock file to pull latest tokens
=> fix(tokens): update tokens to latest

.github/workflows/ci.yml, nx.json
=> build(nx): remove nx cloud token

.releaserc
* Attempt number 2 to get a new release of the 5.x branch out (as we slowly try to get to the latest angular in our code).
=> fix: trying to get 5.x.x out the door, try 2 😏

package.json
adjusting the docs build so that the version 10 publishes correctly
=> build(docs-app): fixing version numbering for docs build

libs/components-react/README.md
This pull request includes significant updates to the `libs/components-react/README.md` file to enhance its content and structure. The changes aim to provide better documentation and ease of use for developers integrating Covalent Components into their React applications.
* **Introduction and Overview**: Added a detailed introduction explaining the purpose and benefits of the Covalent Components React library, including its seamless integration with React and TypeScript support.
* **Table of Contents**: Introduced a comprehensive table of contents to improve navigation and readability.
* **Key Features**: Highlighted the main features of the library, such as React compatibility, declarative syntax, and automatic prop conversion.
* **Installation and Usage**: Provided clear installation …
=> Update components react README.md

apps/knapsack/public/ks-overrides.css
style fix to knapsack code renderer
=> docs(knapsack): style fix to knapsack renderer

apps/knapsack/public/ks-overrides.css
Fixing CSS overrides for knapsac
=> fix(knapsack): adjust knapsack overrides to fix some demos

libs/tokens/src/color/covalent-m3.json
updating the material 3 tokens file to latest brand updates from the Covalent Principles figma file. Updates some surface value colors
=> feat(tokens): update tokens from latest figma vars

libs/angular/theming/_teradata-theme.scss, package-lock.json
updating covalent/tokens package
=> style(deps): update @covalent/tokens to version 10.2.1

package-lock.json, package.json
Upgrade monaco-editor dependency to the latest version 0.52.2
- Upgrade monaco-editor dependency to v0.52.2 (latest)
=> refactor(code-editor): upgrade monaco-editor to the latest version

libs/angular/common/src/directives/web-components/form-control.directive.spec.ts, libs/angular/common/src/directives/web-components/form-control.directive.ts
- Fix `CovalentTextfieldValueAccessorDirective` to handle input changes
- Trigger form validation on input changes in the form control
- Support Async validators
=> fix: form control directive to handle input (10.x.x)

.github/workflows/ci.yml, .github/workflows/release.yml, .releaserc
Trigger a release when changed are merged into `release/10.x.x` branch
- Add branch `10.x.x` to the ci pipeline
- Add branch `10.x.x` to the `.releaserc` file
N/A
=> fix(ci): trigger releases for changes in 10.x.x branch
