- .travis.yml
- README.md
- config/karma.travis.conf.js
- package.json
Added a first draft of testing using Travis. Lots of room to improve over time.
- Travis CI configuration for unit tests with karma
- Runs only in latest Firefox
https://travis-ci.org/Teradata/covalent/builds/144336920
> task(test): setup travis

- src/app/components/style-guide/colors/colors.component.html
- src/app/components/style-guide/colors/colors.component.ts
- src/app/components/style-guide/iconography/iconography.component.html
- src/app/components/style-guide/iconography/iconography.component.ts
- src/app/components/style-guide/product-icons/product-icons.component.html
- src/app/components/style-guide/typography/typography.component.html
- src/app/components/style-guide/typography/typography.component.ts
Added docs to use our various material color utility styles
- Background color docs
- Typography color docs
- Iconography color docs
> feature(colors): docs on font/background/fill colors

- src/app/components/style-guide/style-guide.component.ts
- src/app/components/style-guide/style-guide.routes.ts
- src/app/components/style-guide/utility-styles/index.ts
- src/app/components/style-guide/utility-styles/utility-styles.component.html
- src/app/components/style-guide/utility-styles/utility-styles.component.spec.ts
- src/app/components/style-guide/utility-styles/utility-styles.component.ts
- src/system-config.ts
Documentation for utility styles
- General utilities
- Sizing utilities
- Text utilities
- Pad/Pull/Push utilities
> feature(docs): add utility styles docs

- src/main.ts
Use the `/#/` strategy for url routing to work with github pages since it doesn't support url rewrites.
Fixes #33 
- Hash Strategy
> fix(deploy) use hash urls for github pages

- build.conf.js
Moving scss files to `./deploy` so they get packaged when releasing to npm.
https://github.com/Teradata/covalent/issues/28
- scss files on release build
> ship scss files when building platform

- src/app/app.component.html
- src/app/components/components/components.component.html
- src/app/components/docs/docs.component.html
- src/app/components/layouts/card-over/card-over.component.html
- src/app/components/layouts/manage-list/manage-list.component.html
- src/app/components/layouts/nav-list/nav-list.component.html
- src/app/components/layouts/nav-view/nav-view.component.html
- src/app/components/style-guide/style-guide.component.html
- src/platform/core/README.md
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.html
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.ts
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.ts
- src/platform/core/layout/layout.component.html
Changing `<list-items>` to use `<md-nav-list>` so we can declare a `dense` attribute and have more control over our content projection. See [https://github.com/angular/material2/tree/master/src/components/list#dense-lists](https://github.com/angular/material2/tree/master/src/components/list#dense-lists)
- Changed all instances of `<list-items>` to `<md-nav-list list-items>` and removed from the root template.
- Changed all instances of `<menu-items>` to `<md-nav-list menu-items>` and removed from the root template.
- Updated readme and docs
> feat(layouts): md-nav-list dense ⚡️ Breaking Change

- src/app/app.module.ts
- src/app/app.routes.ts
- src/app/components/components/components.routes.ts
- src/app/components/docs/docs.routes.ts
- src/app/components/layouts/layouts.routes.ts
- src/app/components/style-guide/style-guide.routes.ts
- src/platform/core/index.ts
bugfix(router): router in submodules was configured incorrectly using `forRoot()`, needed to use `forChild()` since `forRoot()` tries to replaces the routes at an application level, which it already exists.
- Backbutton fixed.
- Router in submodules configured correctly with `forChild()`.
> bugfix(router): backbutton isnt working correctly.

- src/app/components/docs/docs.component.ts
- src/app/components/docs/docs.module.ts
- src/app/components/docs/docs.routes.ts
- src/app/components/docs/mock-data/mock-data.component.html
- src/app/components/docs/mock-data/mock-data.component.ts
- src/app/components/docs/overview/overview.component.html
- src/app/components/style-guide/resources/resources.component.ts
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.ts
Adding docs for basic usage of the new mock data server
- Update Docs > Getting Started w/ link to new mock-data page
- Update docs nav list w/ link to mock-data
- Add /docs/mock-data
Getting Started link
> docs(mock-data): adding covalent-data docs

- .travis.yml
- src/app/components/docs/mock-data/mock-data.component.html
The documentation for mock-api in Covalent Quickstart now has instructions for the npm version of Covalent Data.
- updates to `/src/app/components/docs/mock-data.component.html`
> changed covalent data instructions in the documentation

- src/platform/http/http-interceptor.service.spec.ts
- src/platform/http/http-interceptor.service.ts
Added `complete()` hook as part of the `HttpInterceptorService` response Observable since it was not being fired when a request is successful.
https://github.com/Teradata/covalent/issues/87
- Added `complete()` subscriber hook when request is successful.
- Added initial draft of code health code for `HttpInterceptorService`. (karma unit test)
> bugfix(http): adding complete callback

- src/app/components/components/loading/loading.component.html
- src/app/components/components/loading/loading.component.ts
- src/platform/core/index.ts
- src/platform/core/loading/directives/loading.directive.ts
- src/platform/core/loading/loading.component.html
- src/platform/core/loading/loading.component.ts
- src/platform/core/loading/services/loading.service.ts
Added `mode` to loading component so it can be created with either `LoadingMode.Determinate` or `LoadingMode.Indeterminate`.
https://github.com/Teradata/covalent/issues/80
- Added enum for `LoadingMode.Determinate` and `LoadingMode.Indeterminate`.
- Added `loadingMode` input to `TdLoadingDirective` which accepts either `LoadingMode` or `'determinate'|'indeterminate'`.
- Added `setValue(name: string, value: number): boolean` method to `TdLoadingService` which is only successful if loading is set to `LoadingMode.Determinate` or `'determinate'`.
- Added `reset` flag in `TdLoadingComponent` so its refreshed before removing it from DOM. (else the animation going from the previous value to 0 would happen when the component is reattached again)
- Kept `protractor` hack intact so it does not …
> feature(loading): added mode to loading directive + service.

- src/app/components/components/components.component.ts
- src/app/components/components/components.module.ts
- src/app/components/components/components.routes.ts
- src/app/components/components/directives/directives.component.html
- src/app/components/components/directives/directives.component.ts
- src/app/components/components/overview/overview.component.ts
- src/platform/core/directives/auto-trim/auto-trim.directive.ts
- src/platform/core/index.ts
`TdAutoTrim` to trim string values on `blur` event. `ngModel` is required since it hooks into it.
> Added auto trim directive for string values

- src/app/components/components/directives/directives.component.html
- src/app/components/components/directives/directives.component.ts
- src/platform/core/index.ts
- src/platform/core/validators/max.validator.ts
- src/platform/core/validators/min.validator.ts
- src/platform/core/validators/number-required.validator.ts
- tslint.json
Added `min`/`max`/`number-required` validations since ng2 doesnt support them at the moment.
- `TdMinValidator` for selector: `[min][formControlName],[min][formControl],[min][ngModel]`.
- `TdMaxValidator` for selector: `[max][formControlName],[max][formControl],[max][ngModel]`.
- `TdNumberRequiredValidator` for selector: `[type=number][required][formControlName],[type=number][required][formControl],[type=number][required][ngModel]`
```
<md-input #el="ngModel" type="number" [(ngModel)]="val" min="5" max="550" required></md-input>
{{el?.errors | json}}
```
> added min/max/number-required validators

- src/app/components/components/directives/directives.component.html
- src/app/components/style-guide/dialogs/dialogs.component.html
- src/app/components/style-guide/dialogs/dialogs.component.ts
- src/app/components/style-guide/style-guide.component.html
- src/app/components/style-guide/style-guide.component.ts
- src/app/components/style-guide/style-guide.module.ts
- src/app/components/style-guide/style-guide.routes.ts
- src/platform/core/styles/_input.scss
- src/platform/core/styles/platform.scss
Design patterns & code snippets on when & where to use dialogs, toasts & inline errors.
- Dialog patterns
- Toast/Snackbar patterns
- Inline form error patterns
> feature(docs): dialogs, toast & inline error patterns

- src/app/components/layouts/overview/overview.component.html
- src/app/components/layouts/overview/overview.component.scss
Included flexbox layout info on Layouts page
- Flexbox intro
- Link to ng-material v1 layout docs
> feature(docs): flexbox layout intro

- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.scss
- src/platform/core/steps/step-header/step-header.component.scss
Fixed disabled state for stepper and expansion-panel
https://github.com/Teradata/covalent/issues/111
- Remove pointer cursor on `stepper` disable state.
- Remove hover state and pointer cursor on `expansion-panel` + remove outline in focus/active state.
> Feature/expansion + stepper disable 

- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/components/components/components.component.html
- src/app/components/docs/docs.component.html
- src/app/components/layouts/card-over/card-over.component.html
- src/app/components/layouts/manage-list/manage-list.component.html
- src/app/components/layouts/nav-list/nav-list.component.html
- src/app/components/layouts/nav-view/nav-view.component.html
- src/app/components/layouts/overview/overview.component.html
- src/app/components/style-guide/logo/logo.component.html
- src/app/components/style-guide/style-guide.component.html
- src/platform/core/README.md
- src/platform/core/layout/layout-card-over/layout-card-over.component.html
- src/platform/core/layout/layout-card-over/layout-card-over.component.ts
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.html
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.scss
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.scss
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.ts
- src/platform/core/layout/layout-nav/layout-nav.component.html
- src/platform/core/layout/layout-nav/layout-nav.component.ts
- src/platform/core/layout/layout.component.html
- src/platform/core/layout/layout.component.ts
Renamed the title attribute on layouts to instead be sidenavTitle and toolbarTitle instead of title and updated title and subTitle on td-layout-card-over to be cardTitle and cardSubTitle.  Updated all the documentation and ReadMe to reflect these new changes.  The attribute title was causing a tooltip on hover anywhere on the page to show the value passed in.  Renaming this removes the clashing with the native title attribute.
Changes to html and typescript files as well as one test spec file and documentation and readme files
> Rename title attribute on layouts

- src/platform/core/steps/step-body/step-body.component.html
- src/platform/core/steps/step-body/step-body.component.scss
Removing margin and padding from step templates when they are empty or not used.
https://github.com/Teradata/covalent/issues/130
> bugfix(stepper): Conditional margin for stepper templates

- package.json
- src/platform/charts/package.json
- src/platform/chips/package.json
- src/platform/core/package.json
- src/platform/data-table/package.json
- src/platform/file-upload/package.json
- src/platform/highlight/package.json
- src/platform/http/package.json
- src/platform/json-formatter/package.json
- src/platform/markdown/package.json
- src/platform/paging/package.json
- src/platform/search/package.json
Removed `@covalent/core` as dependency from `http` module since this module in particular only needs `@angular/core` and `@angular/http`. https://github.com/Teradata/covalent/issues/123
Relaxed engine node dependency to be up `< 7` https://github.com/Teradata/covalent/issues/134
> feature(deps): relaxed dependency limitations

- src/platform/charts/chart-line/chart-line.component.ts
The line chart wouldn’t render at all if an empty array is used on the [data] attribute, the following error would be thrown:
`TypeError: Cannot read property 'xValue' of undefined`
I narrowed it down to the translation of the data, where it was assumed that the value would be defined at all times, which isn’t the case if data is an empty array.
This fix solves the problem.
- Fix for line chart with empty data sets
The error is the following:
> fix(charts): line charts wouldn’t render with empty data set

- src/platform/http/http-rest.service.ts
Allows adding headers in HTTP requests that are not yet available initially (i.e. when defining `baseHeaders`).
- new `dynamicHeaders?: () => Headers` property on `RESTService`.
Todo. Are there existing tests/fiddles demoing RestService?
> add dynamicHeaders, closes #151

- src/app/components/components/expansion-panel/expansion-panel.component.html
- src/app/components/components/expansion-panel/expansion-panel.component.ts
- src/platform/core/expansion-panel/_expansion-panel-theme.scss
- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.scss
- src/platform/core/expansion-panel/expansion-panel.component.ts
- src/platform/core/index.ts
Initial support for label/sublabel templates (fallback to inputs) + updated docs
```html
<td-expansion-panel label="label" sublabel="sublabel" expand="true|false" disabled="true|false" (expanded)="expandedEvent()" (collapsed)="collapsedEvent()">
<template td-expansion-panel-label>
... add label content (if not used, falls back to [label] input)
</template>
<template td-expansion-panel-sublabel>
... add sublabel content (if not used, falls back to [sublabel] input)
</template>
<td-expansion-summary>
... add summary that will be shown when expansion-panel is "collapsed".
</td-expansion-summary>
... add content that will be shown when the step is "expanded"
</td-expansion-panel>
```
> feat: initial support to templates in label/sublabel for expansion-panel

- src/app/components/components/data-table/data-table.component.html
- src/platform/data-table/README.md
- src/platform/data-table/data-table.component.html
- src/platform/data-table/data-table.component.ts
- src/platform/data-table/data-table.module.ts
- src/platform/data-table/directives/data-table-template.directive.ts
Reopened the PR for template support with up-to-date `data-table`.
https://github.com/Teradata/covalent/pull/125
- Updated docs and demo.
- `tdDataTableTemplateDirective` for template support with access to value, row and column.
Usage:
```html
<td-data-table
[data]="basicData"
[columns]="columns">
<template tdDataTableTemplate="type" let-value="value" let-row="row" let-column="column">
<div layout="row">
<span flex>{{value}}</span>
<md-icon>star</md-icon>
</div>
</template>
</td-data-table>
```
> feat: initial data table template support

- src/app/components/style-guide/resources/resources.component.html
Fix URLS since dribbble attachment link urls change when files are updated
- Axure link fix
- Sketch link update
> hotfix(resources): urls for downloads

- src/platform/search/search-input/search-input.component.html
- src/platform/search/search-input/search-input.component.ts
Bugfix for `td-search-input` since `search` event does not work in FF and IE.
- Internally use `enter` event instead of `search` event
> use enter event instead of search event so it works in IE and firefox

- karma.conf.js
- package.json
- src/app/app.component.scss
- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
- src/app/components/components/material-components/material-components.component.html
- src/app/components/components/material-components/material-components.component.ts
- src/app/components/style-guide/colors/colors.component.html
- src/app/components/style-guide/dialogs/dialogs.component.html
- src/app/components/style-guide/dialogs/dialogs.component.ts
- src/app/components/style-guide/iconography/iconography.component.html
- src/app/components/style-guide/typography/typography.component.html
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.scss
- src/platform/http/http-rest.service.ts
- src/styles.scss
- src/tsconfig.json
Upgrade dependencies for latest angular and material. (11-2 and 2.3.0)
https://github.com/angular/material2/blob/master/CHANGELOG.md#200-alpha11-polyester-golem-2016-12-08
https://github.com/angular/angular/blob/master/CHANGELOG.md#230-2016-12-07
- `@angular@2.3.0`
- `@angular/material@2.0.0-alpha.11-3`
- `rxjs@5.0.0-rc.4`
- `zone.js@0.7.2`
- Fix `.map` generics in `http` module for `rxjs@5.0.0-rc.4`
- Remove top `64px` from manage-list content since its not needed anymore.
- Remove `viewContainterRef` from all places where is not needed and use new duration in `SnackBar`.
- Remove `md-divider` scss override since its fixed now.
- Remove scss override for stretching tabs and favor `md-stretch-tabs` attr
- Update tsconfig.json to use @covalent/* internally between modules
> feat(upgrade-deps): material.11-3 and ng@2.3.0

- src/platform/core/animations/collapse.animation.ts
- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.scss
- src/platform/core/expansion-panel/expansion-panel.component.ts
- src/platform/core/index.ts
- src/platform/core/steps/step-body/step-body.component.html
- src/platform/core/steps/step-body/step-body.component.scss
- src/platform/core/steps/step-body/step-body.component.ts
Added animation `TdCollapseAnimation` and able to reuse it.
typescript
```
import { TdCollapseAnimation } from '@covalent/core';
...
...
animations: [
TdCollapseAnimation(200),
],
```
html
```
<div [@tdCollapse]="true|false">
...
</div>
```
The reason is because `TdToggleDirective` had many issues executing the animations with the `AnimationPlayer` class and its better to do animations the [ng2] way either way. 
- Fixed bug with overlapping content when animating stepper and expansion in FF50.
- [TdCollapseAnimation] animation.
- Replaced `TdToggleDirective` usage in steps and expansion-panel with `TdCollapseAnimation`
> feat(animations): added collapse animation and used in steps and expansion

- .travis.yml
- karma.conf.js
Bug fix to address https://github.com/angular/angular-cli/issues/2125
Unit tests not running in Chrome 55 
Bugfix for travis failing in Chrome
http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/
> fix(code-health): fix to run unit tests in chrome 55 and travis CI

- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
- src/platform/data-table/data-table.component.html
- src/platform/data-table/data-table.component.ts
Switched the way we format the column values in the `data-table` component to be on display, so the underlying data is not modified nor copied.
https://github.com/Teradata/covalent/issues/187
> fix(data-table): format columns correctly when displaying them. closes(#187)

- src/app/components/components/dialogs/dialogs.component.ts
- src/platform/core/dialogs/confirm-dialog/confirm-dialog.component.html
- src/platform/core/dialogs/prompt-dialog/prompt-dialog.component.html
- src/platform/core/dialogs/services/dialog.service.ts
Added better `a11y` support for confirm and prompt dialogs.
https://github.com/Teradata/covalent/issues/170
Added open() and closeAll() methods into `TdDialogService` to allow `MdDialog` underlying usage of both methods without having to inject `MdDialog`.
https://github.com/Teradata/covalent/issues/171
> feature(dialogs): better a11y + exposed open/closeAll methods from MdDialog. closes(#170 and #171)

- src/app/components/components/http/http.component.html
- src/app/components/components/http/http.component.ts
- src/platform/http/README.md
- src/platform/http/http-interceptor.service.ts
- src/platform/http/http-rest.service.spec.ts
- src/platform/http/http-rest.service.ts
There is a need to be able to override the service `transform` in the RESTService at a method level. So now you can pass a specific `transform` callback that overrides the service level `transform` function.
https://github.com/Teradata/covalent/issues/179
- REST Methods now accept an extra optional parameter for method level `IRestTransform` callback to allow more flexibility on response transformations
- Added new `onRequestError` hook to the `IHttpInterceptor` interface and usage in `HttpInterceptorService` (upstreamed from AC)
- Added `code-health` unit test to `RESTService`
- Updated docs and README.md
There is no real way to test it without actually using it, so the `unit-tests` should check if the `RESTService` acts like it should on every scenario.
> feature(http): improvements on http module. closes (#179)

- src/app/components/layouts/manage-list/manage-list.component.html
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.scss
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.scss
The left sidenav list is suppose to scroll while the left top toolbar sticks, and there's suppose to be no box shadow
- updated nav-list
- updated manage-list
- updated manage-list docs
> update(nav-list): remove non-spec box-shadow

- src/app/components/home/home.component.html
- src/app/components/layouts/card-over/card-over.component.html
- src/app/components/layouts/manage-list/manage-list.component.html
- src/app/components/layouts/nav-list/nav-list.component.html
- src/app/components/layouts/nav-view/nav-view.component.html
- src/platform/core/layout/_layout-theme.scss
- src/platform/core/layout/layout-footer/layout-footer.component.html
- src/platform/core/layout/layout-footer/layout-footer.component.scss
- src/platform/core/layout/layout-footer/layout-footer.component.ts
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav/layout-nav.component.html
- src/platform/core/layout/layout.module.ts
Added optional sticky td-layout-footer component to all layouts.
Manage List & Nav List also got optional td-layout-footer-inner which would go in the bottom of the content, not the entire width.
- td-layout-footer for all layouts
- td-layout-footer-inner for nav-list & manage-list
> feature(layout): sticky footer (and footer-inner)

- angular-cli.json
- package.json
- scripts/ghpages-deploy
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/components/docs/icons/icons.component.html
Improved `ghpages-deploy` npm command to deploy it in `AoT`.
- Deploy `ghpages` in `AoT` compilation and `production` mode.
- Added `chart` data files into cli `assets`.
- Replaced base href with `--base-href` ng command.
- Use svg URL's relative path instead of absolute path.
Note: if you have problems with the memory heap. Check the following `angular-cli` issue.
https://github.com/angular/angular-cli/issues/1652#issuecomment-261269197
> feature(deployment): `ghpages-deploy` npm command improvements

- src/platform/core/common/animations/fade/fade.directive.ts
- src/platform/core/common/animations/toggle/toggle.directive.ts
Depending on the `tsconfig.json`, `setTimeout` could be either `window.setTimeout` or `NodeJS.setTimeout`.. to avoid this, we have to explicitly call it from `window`.
https://github.com/Teradata/covalent/issues/225
> bugfix(animations): explicitly used window.setTimeout. (closes #225)

- docs/CHANGELOG.md
- package.json
- src/platform/charts/package.json
- src/platform/core/package.json
- src/platform/dynamic-forms/package.json
- src/platform/highlight/package.json
- src/platform/http/package.json
- src/platform/markdown/package.json
- Updated changelog for 0.10.1
- Contains bugfixes:
- Solved request concurrency issue. https://github.com/Teradata/covalent/pull/228
- Explicitly used window.setTimeout. https://github.com/Teradata/covalent/pull/227
> bump(npm): released patch @0.10.1

- docs/CHANGELOG.md
- package.json
- src/platform/charts/package.json
- src/platform/core/package.json
- src/platform/dynamic-forms/package.json
- src/platform/highlight/package.json
- src/platform/http/http.module.ts
- src/platform/http/interceptors/http-interceptor.service.spec.ts
- src/platform/http/package.json
- src/platform/markdown/package.json
- Updated changelog for 0.10.2
- Contains bugfixes:
- `inteceptors` typo fix in `HttpConfig`. https://github.com/Teradata/covalent/issues/233
> bump(npm): released patch @0.10.2.

- src/styles.scss
- src/theme.scss
Since `theme.scss` was included in the `angular-cli.json` and as part of an `import` in the `styles.scss`, the file was actually getting included twice. This meant duplicated `css` rules and a bigger file.
> bugfix(docs): theme styles duplication

- package.json
- scripts/compile-ts.js
- src/app/app.animations.ts
- src/platform/charts/charts.component.ts
- src/platform/core/data-table/data-table.component.ts
- src/platform/core/file/directives/file-drop.directive.spec.ts
- src/platform/core/file/directives/file-drop.directive.ts
- src/platform/core/file/directives/file-select.directive.spec.ts
- src/platform/core/file/file-upload.component.html
- src/platform/core/file/file-upload.component.spec.ts
- src/platform/core/file/file-upload.component.ts
- src/platform/core/loading/loading.component.ts
- src/platform/core/steps/step.component.ts
- src/platform/core/steps/steps.component.ts
- src/platform/dynamic-forms/services/dynamic-forms.service.spec.ts
- src/platform/http/http-rest.service.spec.ts
- src/platform/http/interceptors/http-interceptor.service.spec.ts
- src/platform/http/interceptors/url-regexp-interceptor-matcher.class.spec.ts
- src/platform/tsconfig-aot.json
- src/test.ts
- src/tsconfig.json
- tslint.json
- Upgraded to `@angular@2.4.2`
- Upgraded to `typescript@2.1.4`
- Upgraded to `tslint@4.1.1`
- Upgraded to `codylizer@2.0.0-beta.4` (angular2 linter)
There is an issue with the `File.types` property between typescript 2.0 and 2.1. https://github.com/Teradata/covalent/issues/236
https://github.com/Microsoft/TypeScript/issues/12069
https://github.com/angular/angular-cli/issues/3157
So for now we are gonna use both types so you can compile it in both cases.
> bugfix(ts): changed `file.types` type to work with both ts 2.0 and 2.1. (closes #236)

- .travis.yml
- docs/RELEASE.md
- package.json
- scripts/start-release
Upgrade to use latest `angular-cli` in covalent docs.
https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#bug-fixes
> upgrade(angular-cli): upgrade to beta.25-5 and fix ng lint usage

- src/app/components/components/material-components/material-components.component.html
Removing inline styles from material-components
- Removed all instances of inline styles
- Replacing with utility classes and material layout
Next PR todo: Reorganize components with demo/code separation in tabs.
> fix(inline-styles) Removing inline styles from material component demos

- src/tsconfig.json
Adding exclusion of spec test files when running ng serve --aot
See bug: https://github.com/Teradata/covalent/issues/267
- modified:   src/tsconfig.json
> bugfix(serve): "ng serve --aot" broken from test file (closes #267)

- src/app/app.module.ts
- src/app/components/home/home.component.html
- src/app/components/home/home.component.ts
- src/app/services/github.service.ts
- src/app/services/index.ts
Adding star count in docs so people can see stargazers and possibly star/unstar covalent from docs in the future.
- `GitHubService` for internal use only
- Star count in home view.
> feature(docs): Added star count in docs.

- angular-cli.json
- src/app/components/components/components.component.html
- src/app/components/components/components.component.ts
- src/app/components/components/markdown/markdown.component.html
- src/app/components/components/markdown/markdown.component.ts
- src/platform/markdown/README.md
- src/platform/markdown/_markdown-theme.scss
- src/platform/markdown/markdown.component.html
- src/platform/markdown/markdown.component.scss
- src/platform/markdown/markdown.component.spec.ts
- src/platform/markdown/markdown.component.ts
Major enhancements, initial unit tests and XSS protection.
- **feature(markdown):** Support space indentation set by the first markdown line.
- **feature(markdown):** No more need to add `<pre><code>`.
- **feature(markdown):** Added `[content]` input to `td-markdown` to load content dynamically.
- **bugfix(markdown):** Use `Renderer` to limit access to native DOM and `DomSanitizer` to prevent `XSS` issues. 
- **bugfix(markdown):** `<hr>` was not showing properly. 
- **code-health(markdown):** Added initial set of unit-tests.
- Updated `README.md` and demo.
- Load `README.md` as resource using `[content]` input in docs to avoid doc duplication.
> feature(markdown): enhancements and code-health.

- src/platform/charts/abstract-chart.component.ts
- src/platform/core/common/animations/collapse/collapse.animation.ts
- src/platform/core/common/animations/fade/fadeInOut.animation.ts
- src/platform/core/common/pipes/bytes/bytes.pipe.ts
- src/platform/core/common/services/router.service.spec.ts
- src/platform/core/data-table/data-table-cell/data-table-cell.component.ts
- src/platform/core/data-table/data-table-column/data-table-column.component.ts
- src/platform/core/data-table/data-table-row/data-table-row.component.ts
- src/platform/core/data-table/data-table-table/data-table-table.component.ts
- src/platform/core/data-table/services/data-table.service.ts
- src/platform/core/dialogs/services/dialog.service.ts
- src/platform/core/file/services/file.service.ts
- src/platform/core/json-formatter/json-formatter.component.spec.ts
- src/platform/core/loading/directives/loading.directive.ts
- src/platform/core/loading/services/loading.factory.ts
- src/platform/core/loading/services/loading.service.ts
- src/platform/core/media/services/media.service.ts
- src/platform/core/steps/steps.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.spec.ts
- src/platform/highlight/highlight.component.ts
- src/platform/markdown/markdown.component.ts
- src/tests/utilities/covalent-tests.ts
After upgrading lint we are encountering many lint errors with trailing whitespace.  This PR fixes those.
- modified:   src/platform/charts/abstract-chart.component.ts
- modified:   src/platform/core/common/animations/collapse/collapse.animation.ts
- modified:   src/platform/core/common/animations/fade/fadeInOut.animation.ts
- modified:   src/platform/core/common/pipes/bytes/bytes.pipe.ts
- modified:   src/platform/core/common/services/router.service.spec.ts
- modified:   src/platform/core/data-table/data-table-cell/data-table-cell.component.ts
- modified:   src/platform/core/data-table/data-table-column/data-table-column.component.ts
- modified:   src/platform/core/data-table/data-table-row/data-table-row.component.ts
- modified: …
> Fix all trailing whitespace lint errors

- src/app/components/docs/deployment/deployment.component.html
Clarified build process for production with the explanation below.
Adding the prod flag to ng build will set the build target and environment to production, which will optimize the build.
`ng build --prod`
When building for production, add the aot flag to enable the Ahead-Of-Time compiler where the browser will download a pre-compiled (from TypeScript) version of your application. Ahead-of-time compilation may require modifications to your code, but will enable faster rendering, fewer asynchronous requests, smaller Angular framework size, and better security.
`ng build --prod --aot`
> enhancement/docs/deployment (prod build clarification)

- src/platform/core/chips/chips.component.html
- src/platform/core/data-table/_data-table-theme.scss
- src/platform/core/search/search-input/search-input.component.html
- src/platform/core/search/search-input/search-input.component.scss
- src/platform/core/search/search-input/search-input.component.ts
- src/platform/core/search/search.module.ts
- **bugfix(chips):** `[readOnly]` state was not being shown properly.
- **bugfix(search):** clear button was not working properly since `input` was not considered empty and label would stay floating.
- **bugfix(search):** scss for `hide-underline` was wrong (md-input deprecation)
> bugfix(general): fixes for `chips` and `search`.

- docs/CHANGELOG.md
- package.json
- scripts/publish-release
- src/platform/charts/package.json
- src/platform/core/loading/directives/loading.directive.ts
- src/platform/core/package.json
- src/platform/dynamic-forms/package.json
- src/platform/highlight/package.json
- src/platform/http/package.json
- src/platform/markdown/package.json
- **bugfix(loading):** Fixed edge case that tried to create the same `tdLoading` twice when using `tdLoading` directive inside a component that uses `[routerLinkActive]` when navigating into it.
- **bugfix(publish):** Fixed publish script to only loop through directories inside `deploy/platform/`
> bugfix(loading): fixed bug between `tdLoading` and `[routerLinkActive]`

- scripts/build-release
There is a need to remove the source files (`ts`) from the release code since the `@angular-cli` picks them up instead of the `js` files which in term breaks `aot` with their new release.
We still needed to do this since those files shouldnt be there either way.
- Cleanse of build when running the `npm run build` script.
> bugfix(build): cleanse the build by removing the `ts` source files.

- scripts/rollup.js
Flex-Layout was added as a dependency but was omitted from the rollup script.
- Adds flex-layout prop to rollup.js `options.globals` .
Executing  `build-release` will currently emit a warning when executing rollup.
```
Treating '@angular/flex-layout' as external dependency
No name was provided for external module '@angular/flex-layout' in options.globals – guessing '_angular_flexLayout'
Treating '@angular/flex-layout' as external dependency
No name was provided for external module '@angular/flex-layout' in options.globals – guessing '_angular_flexLayout'
```
> fix(rollup): add missing dep to options.globals

- src/platform/core/data-table/data-table-column/data-table-column.component.ts
The td-data-table-column wasnt setting the name properly and getting it from a global name. https://github.com/Teradata/covalent/issues/349
> fix(data-table): td-data-table-column return proper name in sort event. (closes #349)

- src/app/components/home/home.component.html
- src/app/components/home/home.component.ts
- updated notifications menu on homepage
> update(home): notification updates for beta2

- docs/UPGRADE.md
> chore(): upgrade guide for beta.2

- src/platform/core/loading/loading.component.html
Center loading component on replace mode. (it was sticking to the top)
> fix(loading): center loading component in replace mode

- src/platform/core/common/animations/collapse/collapse.animation.ts
- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.scss
- src/platform/core/expansion-panel/expansion-panel.component.spec.ts
- src/platform/core/steps/step-body/step-body.component.html
- src/platform/core/steps/step-body/step-body.component.scss
`tdCollapse` animation needs `overflow: hidden`, but it was affecting the content of both components. Now we only add `overflow: hidden` when its animating.
> fix(animations): remove overflow from styles in steps and expansion-panel

- docs/CHANGELOG.md
- package.json
- src/platform/charts/package.json
- src/platform/core/package.json
- src/platform/dynamic-forms/package.json
- src/platform/highlight/package.json
- src/platform/http/package.json
- src/platform/markdown/package.json
> chore(): bump to 1.0.0 beta.2-1

- src/platform/core/layout/navigation-drawer/navigation-drawer.component.scss
Added `overflow:hidden` to animations in `td-navigation-drawer`
> fix(): animation not working correctly in navigation-drawer

- src/platform/http/interceptors/http-interceptor.service.ts
https://github.com/Teradata/covalent/issues/340
we can remove this decorator since this service isnt intended to be injected alone, it needs to be provided via factory. (e.g. Router)
- Removal @Injectable decorator from HttpInterceptorService so we can support @angular@4.X
> fix(): remove @Injectable decorator from HttpInterceptorService. (closes #340)

- src/app/components/components/chips/chips.component.html
- src/app/components/components/chips/chips.component.ts
Docs updated to show demo & code both in tabs
> docs(chips): chips & autocomplete docs

- src/platform/core/search/search-box/search-box.component.scss
- src/platform/core/search/search-input/search-input.component.html
leverage [floatPlaceholder] to make the placeholde stay in place when focused
https://github.com/Teradata/covalent/issues/226
> feat(search): make placeholder stay in place when focused. (closes #226)

- src/platform/core/loading/directives/loading.directive.ts
- src/platform/core/loading/loading.module.ts
- src/platform/core/loading/services/loading.service.ts
Removing the `beta.1` deprecations from code.
> chore(): removal of `beta.1` deprecations

- src/platform/core/media/directives/media-toggle.directive.ts
there are cases when `ngOnDestroy` is executed before `ngOnInit` can even execute, so we need to validate for that. https://github.com/Teradata/covalent/issues/396
more info: https://github.com/Teradata/covalent/issues/396#issuecomment-283879366
> fix(media): check if subscription has been created before unsubscribing. (closes #396)

- src/platform/core/search/search-input/search-input.component.ts
we need to skip the first change event since its thrown when the value is set to undefined
https://github.com/Teradata/covalent/issues/385
> fix(search): stop debounceSearch event when page loads. (closes #385)

- src/app/components/components/notifications/notifications.component.html
- src/platform/core/search/search-box/search-box.component.scss
- src/platform/core/search/search-input/search-input.component.scss
https://github.com/Teradata/covalent/issues/412
There was a scrollbar appearing in the `td-search-input` since we set a height on the component.
- fix(search): removed fixed height in search-box and search-input
- fix(search): stop hiding label when focusing
> fix(search): overflow search-input fix + stop hiding label when focusing. (closes #412)

- src/platform/core/expansion-panel/expansion-panel.component.html
Remove `Click to expand!` string from `expansion-panel`.
Part of https://github.com/Teradata/covalent/issues/324
> fix(expansion-panel): remove hardcoded string

- src/app/components/components/loading/loading.component.ts
- src/platform/core/loading/services/loading.factory.ts
Part of https://github.com/Teradata/covalent/issues/325
Addding support for `OnPush` change detection strategy into the loading component.
Currently it wasnt working correctly on replace mode under `OnPush`.
> fix(loading): support OnPush change detection strategy

- docs/GETTING_STARTED.md
Changing instructions from place to clarify that it is not only enough to use the SCSS file.
Modified Readme to clarify FAQs:
https://github.com/Teradata/covalent/issues/451
https://github.com/Teradata/covalent/issues/436#issuecomment-288412639
- Readme.md
N/A
> Clarify instructions to include the platform.css

- src/platform/core/data-table/directives/data-table-template.directive.ts
- src/platform/core/expansion-panel/expansion-panel.component.ts
- src/platform/core/file/file-input/file-input.component.ts
- src/platform/core/steps/step.component.ts
When upgrading to ng4 missed some directives that used `template` instead of `ng-template`
This fixes the unit tests and makes every component work well in ng4
> fix(): change directive selectors to use `ng-template` for ng4

- src/platform/core/data-table/data-table.module.ts
https://github.com/Teradata/covalent/issues/439
Add missing interface export for `ITdDataTableSelectAllEvent`
> fix(data-table): add missing export for ITdDataTableSelectAllEvent (closes #439)

- src/platform/core/data-table/data-table.component.ts
- src/platform/core/file/file-input/file-input.component.ts
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.ts
- src/platform/core/search/search-box/search-box.component.ts
- src/platform/core/search/search-input/search-input.component.ts
- src/platform/core/steps/step.component.ts
https://github.com/Teradata/covalent/issues/384
Need to remove the `private` access modifier from properties that have `@ViewChild`, `@ViewChildren`, `@ContentChild` and `@ContentChildren` since they are accessed from outside the class they are declared in and hence the `compiler` complains about it.
> fix(aot): remove private keyword from @View and @Content children. (closes #384)

- src/app/components/components/dynamic-forms/dynamic-forms.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.spec.ts
- src/platform/dynamic-forms/services/dynamic-forms.service.ts
https://github.com/Teradata/covalent/issues/449
Add support for `password` element in `dynamic-forms` module.
- `TdDynamicElement.Password` enum value.
> feat(dynamic-forms): add `password` element. (closes #449)

- src/platform/core/common/styles/utilities/_general.scss
Angular 4 added tabindex to everything which is good for a11y but it added the default outline to everything. This removes the outline from icons, cards, etc.
- remove outline style from items w/ [tabindex]
Before
After
> fix(tabindex): remove default outline

- README.md
- src/app/components/home/home.component.html
Adding both Covalent-Electron and Covalent-Data to Readme and docs of Covalent
- modified:   README.md
- modified:   src/app/components/home/home.component.html
> chore(docs): add covalent-electron and covalent-data to README and docs

- .travis.yml
Use `npm install` instead of `yarn install` while we debug the issue for AoT errors.
> fix(travis): fix npm install for now while we check why yarn install gives AoT errors

- src/platform/core/steps/step-header/step-header.component.scss
- src/platform/core/steps/steps.component.scss
instead of using margin-inline-start or margin-inline-end, its better to just use proper styles depending on ltr or rtl
https://github.com/Teradata/covalent/issues/501
- fix(steps): add proper styles depending if its rtl or lrt
> fix(steps): issue margin-inline style in certain conditions. (closes #501)

- .angular-cli.json
- docs/GETTING_STARTED.md
- src/app/components/docs/docs.module.ts
- src/app/components/docs/overview/overview.component.html
we need to show our GETTING_STARTED information easier by loading it in the docs site.
https://github.com/Teradata/covalent/issues/504
- load our `docs/` dir as part of the build.
- Loading `GETTING_STARTED.md` with our `pretty-markdown` component
> chore(getting-started): load our GETTING_STARTED.md in the docs (closes #504)

- src/app/components/components/http/http.component.html
- src/platform/core/chips/chips.module.ts
- src/platform/core/common/common.module.ts
- src/platform/core/data-table/data-table.module.ts
- src/platform/core/dialogs/dialogs.module.ts
- src/platform/core/expansion-panel/expansion-panel.module.ts
- src/platform/core/file/file.module.ts
- src/platform/core/index.ts
- src/platform/core/json-formatter/json-formatter.module.ts
- src/platform/core/layout/layout.module.ts
- src/platform/core/loading/loading.module.ts
- src/platform/core/media/media.module.ts
- src/platform/core/menu/menu.module.ts
- src/platform/core/notifications/notifications.module.ts
- src/platform/core/paging/paging.module.ts
- src/platform/core/search/search.module.ts
- src/platform/core/steps/steps.module.ts
- src/platform/dynamic-forms/dynamic-forms.module.ts
- src/platform/highlight/highlight.module.ts
- src/platform/markdown/markdown.module.ts
they were deprecated in beta.3, so we can remove them for beta.4 now
- Removal of `forRoot()` methods deprecated in beta.3
> chore(all): remove forRoot() deprecations.

- src/platform/core/layout/layout-card-over/layout-card-over.component.html
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav/layout-nav.component.html
- src/platform/core/layout/layout.component.html
This selectors were deprecated a few releases back so it should be ok to remove them now
- Removal of `ng-content` selectors that were deprecated in `beta.2`
> chore(layout): remove deprecated selectors for `ng-content`

- package.json
- src/app/components/components/file-upload/file-upload.component.ts
- src/platform/core/chips/chips.component.ts
- src/platform/core/common/forms/validators/max/max.validator.ts
- src/platform/core/common/forms/validators/min/min.validator.ts
- src/platform/core/common/forms/validators/validators.ts
- src/platform/core/data-table/data-table.component.ts
- src/platform/core/expansion-panel/expansion-panel.component.ts
- src/platform/core/file/file-input/file-input.component.ts
- src/platform/core/package.json
- src/platform/core/steps/step-body/step-body.component.ts
- src/platform/core/steps/step-header/step-header.component.ts
- src/platform/core/steps/step.component.ts
- src/platform/dynamic-forms/dynamic-elements/abstract-control-value-accesor.ts
- src/platform/highlight/package.json
- src/platform/http/package.json
- src/platform/markdown/package.json
- tslint.json
- yarn.lock
Also upgraded codelyzer to 3.0.0, added @angular/language-service, tslint to 5.1.0 and upgraded typescript to 2.3.1
> chore(): upgrade to @angular@4.1.0

- src/platform/core/common/pipes/bytes/bytes.pipe.spec.ts
- src/platform/core/common/pipes/bytes/bytes.pipe.ts
Modified the TdBytesPipe to convert using 1024 bytes per Kilobyte (technically [Kilibyte](https://en.wikipedia.org/wiki/Kibibyte)).
Closes #527
- Updated pipe conversion
- Updated unit test numbers
Per #527 http://plnkr.co/edit/gLMsYWq064zvaN9FOl32
> fix(pipes): convert bytes using powers of 2 in `TdBytesPipe`. (closes #527)

- src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.html
https://github.com/Teradata/covalent/issues/508
There is a problem when accessing certain properties in an `AbstractControl`. So we need to use methods like `hasError()` and `get()` to get the proper data for AoT.
> fix(dynamic-forms): fix AoT issue with min/max validators (closes #508)

- tsconfig.json
Fixed tsconfig typeRoots file path. (closes [#554](https://github.com/Teradata/covalent/issues/554))
- modified: tsconfig.json
> fix(typings) fix tsconfig typeRoots file path (closes #554)

- src/platform/markdown/README.md
- src/platform/markdown/markdown.component.spec.ts
- src/platform/markdown/markdown.component.ts
Added a new event binding to the TdMarkdownComponent called `contentReady`. The event is emitted after the markdown content rendering is finished. 
I added additional unit test to the spec to include this new feature. Also made some small mods in the respective spec to help organize its unit tests for future development. 
This is a feature requested from [#563](https://github.com/Teradata/covalent/issues/536)
- modified: src/platform/markdown/README.md
- modified: src/platform/markdown/markdown.component.spec.ts
- modified: src/platform/markdown/markdown.component.ts
> feat(markdown): added contentReady event binding. (closes #563) (#536)

- src/platform/core/paging/paging-bar.component.spec.ts
- src/platform/highlight/README.md
- src/platform/highlight/highlight.component.spec.ts
- src/platform/highlight/highlight.component.ts
Added a new event binding to the TdHighlightComponent called contentReady. The event is emitted after the highlight content rendering is finished.
I added additional unit test to the spec to include this new feature. Also made some small mods in the respective spec to help organize its unit tests for future development.
This is a feature requested from [#553](https://github.com/Teradata/covalent/issues/553)
- modified: src/platform/highlight/README.md
- modified: src/platform/highlight/highlight.component.spec.ts
- modified: src/platform/highlight/highlight.component.ts
> feat(highlight): added contentReady event binding. (closes #553)

- src/app/components/components/chips/chips.component.html
- src/app/components/components/chips/chips.component.ts
- src/platform/core/chips/chips.component.html
- src/platform/core/chips/chips.component.spec.ts
- src/platform/core/chips/chips.component.ts
currently the chip element disappeared, so the space should remain there to let the user know something is there on screen.
Also update docs to use toggles instead of buttons
- Disable input, set its width to 0 and remove its placeholder when state is `readOnly="true"` or `chipAddition="false"`
- Changed demo/docs to use toggles instead of buttons since its a better look and feel for it.
- fix(chips): added missing rxjs/add/operator/debounceTime import
- code-health(chips): added initial unit tests for chips component
> feat(chips): make chips preserve input height when chipAddition is false

- src/platform/core/chips/chips.component.html
- src/platform/core/chips/chips.component.ts
underline was being removed because of a previous commit, now its show in readOnly state but disabled
> fix(chips): show underline when readOnly and add codeblocks

- package.json
- scripts/rollup.js
- src/platform/core/index.ts
- src/platform/core/package.json
- yarn.lock
since CovalentCoreModule has been removed, there is really no use for @angular/flex-layout inernally. we will leave it to the developer to include it on demand.
closes https://github.com/Teradata/covalent/issues/542 and https://github.com/Teradata/covalent/issues/502
- remove `@angular/flex-layout` as a dependency since it should be included as needed now that CovalentCoreModule has been removed.
- updated `yarn.lock`
> chore(dependencies): removal of flex-layout dependency. (closes #542) (closes #502)

- src/app/app.component.html
- src/app/components/components/components.component.html
- src/app/components/docs/docs.component.html
- src/app/components/layouts/card-over/card-over.component.html
- src/app/components/layouts/manage-list/manage-list.component.html
- src/app/components/layouts/nav-list/nav-list.component.html
- src/app/components/layouts/nav-view/nav-view.component.html
- src/app/components/layouts/overview/overview.component.html
- src/app/components/style-guide/style-guide.component.html
- src/platform/core/layout/README.md
- src/platform/core/layout/layout-nav-list/README.md
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.ts
- src/platform/core/layout/layout-nav/README.md
- src/platform/core/layout/layout-nav/layout-nav.component.html
- src/platform/core/layout/layout-nav/layout-nav.component.ts
- src/platform/core/layout/layout.module.ts
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.html
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.ts
Remove usage of `[routerLink]` directive and make use of an `@Optional` `Router` explicitly to decide whether or not to set the navigation style and to navigate on click.
Also removes the default `/` navigation, and makes it more explicit.
This will allow you to use logo & text in our plunker w/o router fail.
- remove `RouterModule` as required dependency
- Remove `[routerLink]` usage.
- Use of `Optional` `Router` to indicate whether there are routes to be navigate or not.
- Make `navigationRoute` required if you want navigation (still validates for `Optional` `Router`)
- Set cursor pointer if there is a router injected.
```
<td-layout-nav toolbarTitle="title" icon="apps"></td-layout-nav>
```
> feat(layout): make navigation optional if there are no routes to navigate to.

- src/app/components/components/loading/loading.component.html
- src/app/components/components/loading/loading.component.ts
- src/platform/core/loading/loading.component.ts
- src/platform/core/loading/services/loading.factory.ts
we need to remove OnPush from `td-loading` since its technically a container component and shouldnt affect the change detection of its children. The reason for this is that it was enforcing `OnPush` on its children when it shouldnt have.
Also we need to use `detectChanges` in the replace scenario so the change detection works well.
- remove `OnPush` from `TdLoadingComponent`.
- call `detectChanges` when the template replaced by the loading is re-attached.
- docs(loading): improve demo by adding `ngModel`.
> fix(loading): remove OnPush from `td-loading`

- src/platform/core/data-table/data-table.component.spec.ts
- src/platform/core/data-table/data-table.component.ts
if you dont set data properly (undefined) and you have the data-table as selectable and multiple, it will error out will trying to see if all rows are selected.
https://github.com/Teradata/covalent/issues/559
- fix to allow data to be undefined when setting datatable as selectable/multiple.
- unit test for this specific case
> fix(data-table): fix when data is undefined and multiple selection (closes #559)

- src/platform/core/data-table/data-table.component.scss
the css was incorrect for the pseudo checkbox in this release because it was changed in material, we need to remove the top and left overrides from it
https://github.com/Teradata/covalent/issues/525
> fix(data-table): fix pseudo checkbox in data-table. (closes #525)

- src/platform/core/data-table/data-table.component.html
- src/platform/core/data-table/data-table.component.spec.ts
- src/platform/core/data-table/data-table.component.ts
when at least one row is selected and not every row is selected, the checkbox for select/deselect all should be in indeterminate state.
https://github.com/Teradata/covalent/issues/571
- Show indeterminate state when at least one row is selected.
- Unit tests with proper use cases for indeterminate states.
> feat(data-table): indeterminate state in 'selectAll' checkbox (closes #571)

- package.json
- src/app/components/style-guide/style-guide.module.ts
- src/platform/core/chips/chips.component.spec.ts
- src/platform/core/package.json
- src/platform/highlight/package.json
- yarn.lock
Upgraded material to the latest release to leverage the new components like datepicker and such.
https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta5-taffeta-admiral-2017-05-13
and
https://github.com/angular/material2/blob/master/CHANGELOG.md#200-beta4-unobtainium-sunglasses-2017-05-12
- Upgraded `angular/material` to `2.0.0-beta.5`
- Moved `@angular/material` as `peerDependency`
- Upgraded `highlight.js` to `9.11.0`
- Upgraded `@angular/cli` to `1.0.3`
- Upgraded `tslint` to `5.2.0`
- Updated `yarn.lock`
> chore(dependencies): upgrade material to beta.5

- src/platform/core/common/styles/_layout.scss
updated layout scss to suppor the existing `[flex-noshrink]` with expected `[flex="noshrink"]` syntax
- updated _layout.scss
> fix(flex): flex=“value” for grow/initial/auto/none/noshink/nogrow (closes #586)

- src/app/components/components/components.component.ts
- src/app/components/components/components.module.ts
- src/app/components/components/components.routes.ts
- src/app/components/components/message/message.component.html
- src/app/components/components/message/message.component.ts
- src/app/components/components/overview/overview.component.ts
- src/platform/core/index.ts
- src/platform/core/message/README.md
- src/platform/core/message/_message-theme.scss
- src/platform/core/message/message.component.html
- src/platform/core/message/message.component.scss
- src/platform/core/message/message.component.spec.ts
- src/platform/core/message/message.component.ts
- src/platform/core/message/message.module.ts
- src/platform/core/theming/_all-theme.scss
adding `CovalentMessageComponent` with `TdMessageComponent` for easy display of inline messages or info boxes
https://github.com/Teradata/covalent/issues/316
Adding `message` component to `covalent`.
This leverages our color styles to set the color and contrast (`red`,`blue`, etc), but also can use the material theme colors like `primary` , `warn` and `accent`.
Usage example:
```html
<td-message #message label="Label" sublabel="Sublabel goes here" icon="warning" color="primary | blue | red" [opened]="true">
<button td-message-actions md-button>View More<button>
<button td-message-actions md-icon-button (click)="message.close()">
<md-icon>cancel</md-icon>
<button>
</td-message>  
```
Properties:
| Name | Type | Description |
| --- | --- | --- |
| `label?` | `string` | Sets the label of the …
> feat(message): introducing `message` module. (closes #316)

- src/app/components/home/home.component.html
- src/app/components/home/home.component.ts
Beta 4 features in notification menu
> update(home): beta 4 notification menu

- src/platform/core/data-table/data-table.component.html
- src/platform/core/data-table/data-table.component.spec.ts
- src/platform/core/data-table/data-table.component.ts
even though clicking on the checkbox is still clicking on the row, we need to block this since people want to navigate when clicking on row and select when clicking on checkbox.
https://github.com/Teradata/covalent/issues/611
- block `(rowClick)` event when click event target is `md-pseudo-checkbox`
- unit test for this particular use case
> fix(data-table): block (rowClick) event when clicking on checkbox (closes #611)

- src/platform/core/data-table/data-table.module.ts
- src/platform/core/data-table/services/data-table.service.ts
- src/platform/core/dialogs/dialogs.module.ts
- src/platform/core/dialogs/services/dialog.service.ts
- src/platform/core/loading/loading.module.ts
- src/platform/core/loading/services/loading.factory.ts
- src/platform/core/loading/services/loading.service.ts
- src/platform/core/media/media.module.ts
- src/platform/core/media/services/media.service.ts
- src/platform/dynamic-forms/dynamic-forms.module.ts
- src/platform/dynamic-forms/services/dynamic-forms.service.ts
- src/platform/http/http.module.ts
when using modules, make sure we reuse the instance provided by the parent module rather than creation a new instance.
all covalent services are meant to be singleton and app wise instances.
- Added provider factories to either return the parent instance or create one if there is none.
> perf(providers): make sure all services are singleton

- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/platform/core/layout/README.md
- src/platform/core/layout/_layout-theme.scss
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.ts
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.ts
- src/platform/core/layout/layout-nav/layout-nav.component.ts
- src/platform/core/layout/layout.component.html
- src/platform/core/layout/layout.component.ts
this so we can use diff types of modes for mid-small size projects in `td-layout`
- added `[mode]` and `[opened]` to td-layout so we can play around with both inputs and provide different experiences for users.
- Menu button in `td-layout-nav` and `td-layout-nav-list` now `toggle`s instead of just `open`ing
> feat(layout): add `[mode]`, `[opened]` and `[sidenavWidth]` to main `td-layout`

- package.json
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav/layout-nav.component.html
- src/platform/core/layout/layout.module.ts
- src/platform/core/package.json
https://github.com/Teradata/covalent/issues/620
we need to add `cdkScrollable` in our layouts so components like `md-autocomplete` can hook into them and reposition themselves when a user scrolls.
> fix(layout): upgrade to material@beta.6 to use exposed `ScrollDispatchModule` (closes #620)

- src/app/components/home/home.component.html
- src/styles.scss
Even though IE11 isn't officially supported by Covalent, angular-material supports IE11 and all the components work in IE11. However, the Covalent home page doesn't really look that great in IE11. We want to show off Covalent at an upcoming demo, and stakeholders want to see that Covalent is compatible with IE11 so that we can continue to use it in TDAA applications. 
This change makes the Covalent homepage work and display well in IE11.
Before:
- .../app/components/home/home.component.html
- .../app/styles.scss (not needed, just picked up a white space change)
View in IE 11
After:
> chore(docs): make covalent homepage look right in IE11

- src/app/components/components/overview/overview.component.html
Even though IE11 isn't officially supported by Covalent, angular-material supports IE11 and all the components work in IE11. However, the Covalent component overview doesn't really look that great in IE11. We want to show off Covalent at an upcoming demo, and stakeholders want to see that Covalent is compatible with IE11 so that we can continue to use it in TDAA applications. 
This change makes the Covalent component overview work and display well in IE11.
Before:
- .../app/components/overview/overview.component.html
View in IE 11
After:
> chore(docs): update overview.component.html to support IE11

- src/platform/core/chips/chips.component.ts
when clicking near the bottom of the input, the focus would make the autocomplete render, but the click event would close it since its technically outside of it.
we need to disable the focus listener when its via click user interaction
> fix(chips): protect against case where click would close the autocomplete

- src/app/components/components/expansion-panel/expansion-panel.component.html
- src/app/components/components/expansion-panel/expansion-panel.component.ts
- src/platform/core/expansion-panel/README.md
- src/platform/core/expansion-panel/expansion-panel.component.html
https://github.com/Teradata/covalent/issues/475
also created README.md and loaded it in docs + added code blocks in the examples
- chore(expansion-panel): updated docs with better examples
- fix(expansion-panel): only render label and sublabel when its needed
> chore(expansion-panel): updated docs with better examples (closes #475)

- src/app/components/components/components.module.ts
- src/platform/core/steps/step-body/step-body.component.html
- src/platform/core/steps/step-body/step-body.component.scss
- src/platform/core/steps/steps.module.ts
https://github.com/Teradata/covalent/issues/282
Certain elements overflowed out of the stepper and no scroll would appear. With this the `data-table` doesnt overflow.
> fix(stepper): horizontal scroll was not appearing when needed in certain cases. (closes #282)

- src/app/components/style-guide/cards/cards.component.html
- src/app/components/style-guide/style-guide.module.ts
- src/platform/core/common/styles/_card.scss
- src/platform/core/common/styles/_variables.scss
Fixed margins & borders (RTL/LTR) for card images in card title groups
> fix(card-images): sm/md/lg card images in title-group (closes #575)

- src/app/components/components/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/README.md
- src/platform/core/expansion-panel/_expansion-panel-theme.scss
- src/platform/core/expansion-panel/expansion-panel-group.component.html
- src/platform/core/expansion-panel/expansion-panel-group.component.ts
- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.scss
- src/platform/core/expansion-panel/expansion-panel.component.ts
- src/platform/core/expansion-panel/expansion-panel.module.ts
this will give spec margin to grouped expansion panels following the spec, but its optional so we can use stand alone expansion panels without margin too for other use cases.
- new component `TdExpansionPanelGroupComponent` so we can group expansion panels and add margin following material spec
```html
<td-expansion-panel-group>
<td-expansion-panel label="Label goes here">
<div class="md-padding">
<h3 class="md-subhead">md-padding class</h3>
</div>
</td-expansion-panel>
<td-expansion-panel label="Another label goes here">
<div class="md-padding">
<h3 class="md-subhead">md-padding class</h3>
</div>
</td-expansion-panel>
<td-expansion-panel label="Yet another label goes here">
<div class="md-padding">
<h3 class="md-subhead">md-padding class</h3>
</div>
</td-expansion-panel> …
```
> feat(expansion-panel): introducing expansion-panel-group to only give margin to expansion panels when grouped

- src/app/components/components/expansion-panel/expansion-panel.component.html
- src/app/components/components/steps/steps.component.html
- src/app/components/components/steps/steps.component.ts
- src/platform/core/expansion-panel/README.md
- src/platform/core/expansion-panel/_expansion-panel-theme.scss
- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.scss
- src/platform/core/expansion-panel/expansion-panel.component.ts
- src/platform/core/steps/_steps-theme.scss
- src/platform/core/steps/step-header/step-header.component.html
- src/platform/core/steps/step-header/step-header.component.scss
- src/platform/core/steps/step-header/step-header.component.ts
- src/platform/core/steps/step.component.ts
- src/platform/core/steps/steps.component.html
Adding `[disableRipple]` input so developers can disable ripple effect on step header or expansion panel header.
Also small ninja fix for https://github.com/Teradata/covalent/issues/318
- feat(expansion-panel): add `[disableRipple]` input
- feat(expansion-panel): add `[disableRipple]` input
- fix(expansion-panel): expand input works with "true" string (closes #318)
> feat(expansion-panel) and (steps): add `[disableRipple]` input.

- src/platform/core/steps/_steps-theme.scss
- src/platform/core/steps/step-header/step-header.component.html
Makes more sense to call it `mat-inactive` since it just colors it and helps out in unit testing when trying to figure out if a step is disabled or inactive.
> fix(steps): change internal class to mat-inactive

- src/platform/core/dialogs/prompt-dialog/prompt-dialog.component.html
- src/platform/core/dialogs/prompt-dialog/prompt-dialog.component.ts
https://github.com/Teradata/covalent/issues/616
Improved a11y in prompt dialog. 
Now we will select input text when pre-populated when focused.
> feat(dialog): improve prompt a11y by selection text in input when focused. (closes #616)

- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.routes.ts
- src/app/components/components/components.component.html
- src/app/components/docs/docs.component.html
- src/app/components/layouts/manage-list/manage-list.component.html
- src/app/components/layouts/nav-list/nav-list.component.html
- src/app/components/style-guide/style-guide.component.html
- src/app/components/templates/templates.component.html
- src/app/components/toolbar/toolbar.component.ts
- src/app/utilities/direction.ts
there were issues when navigation between views or when using the td-layout.. state was lost and sidenavs were not working as intended.
> fix(rtl-demo): fix rtl/lrt demo in docs

- src/app/components/components/chips/chips.component.html
- src/platform/core/chips/README.md
- src/platform/core/chips/chips.component.html
- src/platform/core/chips/chips.component.scss
- src/platform/core/chips/chips.component.spec.ts
- src/platform/core/chips/chips.component.ts
- src/platform/core/chips/chips.module.ts
now we can use normal chip strings, template chips and contact chips by mixin and matching our templates and directives
we renamed `td-basic-chip` to `td-chip` since it will serve a generic purpose depending on its content.
- Styling for `[td-chip-avatar]`
- Updated demos
```html
<td-chips>
<ng-template td-chip let-chip="chip">
<div class="tc-grey-100 bgc-teal-700" td-chip-avatar>{{chip.substring(0, 1).toUpperCase()}}</div>
</ng-template>
</td-chips>
```
> feat(chips): leverage `td-chip` for all cases introducing `td-chip-avatar`

- src/platform/core/layout/_layout-theme.scss
- src/platform/core/layout/layout-card-over/README.md
- src/platform/core/layout/layout-footer/layout-footer.component.html
- src/platform/core/layout/layout-footer/layout-footer.component.scss
- src/platform/core/layout/layout-footer/layout-footer.component.ts
- src/platform/core/layout/layout-manage-list/README.md
- src/platform/core/layout/layout-nav-list/README.md
- src/platform/core/layout/layout-nav/README.md
https://github.com/Teradata/covalent/issues/489
this input will be optional since by default the background is gray and can be overriden by using primary, accent or warn
- `color` input in `td-layout-footer`
> feat(layout): add `color` input to `td-layout-footer`. (closes #489)

- src/app/app.module.ts
- src/app/app.routes.ts
- src/app/services/index.ts
- src/app/services/selective-preloading-strategy.service.ts
Preload modules that are lazy loaded to prevent load delay for parent routes.
- Added a SelectivePreloadingStrategyService
- Added config to each parent route ( set to true for now for preloading )
> feat(preload): add selective preload strategy for lazy loading

- src/app/components/components/loading/loading.component.ts
- src/platform/core/loading/services/loading.factory.ts
it complains in change detection, so we have to explicitly call a change detection cycle when rendering it
Also: fix(loading): make sure to detect changes when creating the loading component in a hook like `ngAfterViewInit` or `ngAfterContentInit`
> fix(loading): when using the full screen loader in `ngOnInit` it fails

- src/app/components/home/home.component.ts
- src/app/components/layouts/manage-list/manage-list.component.html
- src/app/components/layouts/manage-list/manage-list.component.ts
- src/app/components/layouts/nav-list/nav-list.component.html
- src/app/components/layouts/nav-list/nav-list.component.ts
angular is more restrictive now and complains if we dont explicitly call a change detection cycle when changing any input via a life hook cycle such as `ngAfterViewInit` and `ngAfterContentInit`..
this happens because the change detections have finished by then, so if you must change anything at that point, you need to call explicitly for a new change detection cycle via `detectChanges`
https://github.com/Teradata/covalent/issues/684
> chore(): update documentation with the way to use media.broadcast (closes #684)

- src/app/components/home/home.component.html
- src/app/components/style-guide/logo/logo.component.html
- src/app/components/style-guide/logo/logo.component.scss
- src/app/components/style-guide/style-guide.module.ts
- src/theme.scss
- dark td-layout-footer
- proper expansion theme
- updated logo docs w/ sizing snippet & updated toolbar/sidenav logo docs
> fix(): footer & expansion theme, update logo docs (closes #578)

- docs/CHANGELOG.md
- package.json
- src/platform/core/package.json
- src/platform/dynamic-forms/package.json
- src/platform/highlight/package.json
- src/platform/http/package.json
- src/platform/markdown/package.json
Patch release for beta.5 and updated changelog.
> chore(): bump to beta.5-1 and update changelog

- src/platform/core/data-table/data-table.component.ts
Data Grid row click not working in firefox. This fixes it.
> fix(): fixes click row fails in mozilla for datagrid (#692)

- package.json
Hard setting typescript dependency to 2.3.2 to avoid incompatability with rxjs
Talk about the great work you've done!
- package.json
> chore(): hard set typescript dependency to 2.3.2

- src/platform/core/message/README.md
Fixed closing `button` html tags in **message** `README.md`
- Example `docs` changes
- N/A
- N/A
> Fixed closing html tags

- src/platform/core/loading/directives/loading.directive.ts
https://github.com/Teradata/covalent/issues/732
Language service was complaining because we had the generic of `TemplateRef` as `Object` when it needs to be a class that has a `$implicit` value.. in this case `TdLoadingContext`.
> fix(language-service): complain with loading directive (template with no implicit value) (closes #732)

- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
- src/platform/core/data-table/README.md
- src/platform/core/data-table/data-table.component.spec.ts
- src/platform/core/data-table/data-table.component.ts
Since sometimes we need to prepopulate `ngModel` and comparison by reference doesnt apply when using server side pagination and such, we need to be able to compare the rows and model by a set property or something.
- Added `[compareWith]` input so we can override the comparison by reference and compare the rows and model by anything we want to state whats selected when prepopulating.
> feat(table): add `[compareWith]` input to allow row comparison

- src/platform/core/layout/README.md
- src/platform/core/layout/layout-manage-list/README.md
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.html
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.ts
- src/platform/core/layout/layout-nav-list/README.md
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.ts
- src/platform/core/layout/layout.component.html
- src/platform/core/layout/layout.component.ts
also fix issue where the width would act weird in certain occasions when the min-width was greater than the max-width
- Remove note about % not well supported since it appears that md-sidenav supports it now.
- add min-width also since there were weird behaviors when the min-width was greater than the max-width.
> fix(layout): remove % note from sidenavWidth

- src/platform/core/data-table/_data-table-theme.scss
- src/platform/core/data-table/data-table-row/data-table-row.component.ts
- src/platform/core/data-table/data-table.component.html
To avoid executing the `isSelectable` method twice, we execute it once and assign it to the `row` component to reuse its value.
> perf(table): add selected input in row to preserve value

- src/platform/core/data-table/data-table.component.ts
Before we where sending the `ngModel` which doesnt mean anything.. now we are gonna send the toggled rows when clicking in the select/deselect all checkbox.
> fix(table): selectAll event will send toggled rows only

- package.json
- src/app/components/components/code-editor/code-editor.component.html
Upgrade Covalent-Electron to use Code Editor 1.0.0-alpha.6-3
- modified:   package.json
> Upgrading to Covalent Code Editor 1.0.0-alpha.6-3

- package.json
Upgrade Covalent-Electron to use Code Editor 1.0.0-alpha.6-4
- modified:   package.json
> Upgrading to Covalent Code Editor 1.0.0-alpha.6-4

- docs/CHANGELOG.md
Generating changelog for beta.6 will proper explanation of the layout breaking changes.
> chore(): changelog for beta.6 release

- src/platform/core/chips/chips.component.ts
- src/platform/core/common/behaviors/disabled.mixin.ts
- src/platform/core/data-table/data-table.component.html
- src/platform/core/data-table/data-table.component.ts
- src/platform/core/expansion-panel/expansion-panel.component.ts
- src/platform/core/file/directives/file-drop.directive.ts
- src/platform/core/file/directives/file-select.directive.ts
- src/platform/core/file/file-input/file-input.component.ts
- src/platform/core/file/file-upload/file-upload.component.ts
- src/platform/core/steps/step.component.ts
Instead of validating boolean | string inputs to take them as `true` if undefined and parse strings properly, we will leverage the `coerceBooleanProperty` from `@angular/cdk`
> feat(): leverage coerceBooleanProperty from cdk

- src/app/services/selective-preloading-strategy.service.ts
- src/platform/core/chips/chips.component.ts
- src/platform/core/common/common.module.ts
- src/platform/core/common/services/router-path.service.spec.ts
- src/platform/core/common/services/router-path.service.ts
- src/platform/core/loading/directives/loading.directive.spec.ts
- src/platform/core/media/services/media.service.ts
- src/platform/core/search/search-input/search-input.component.ts
- src/platform/http/http-rest.service.spec.ts
- src/platform/http/http-rest.service.ts
- src/platform/http/interceptors/http-interceptor.service.spec.ts
https://github.com/angular/material2/pull/5314
Remove patch imports from rxjs since they affect the user's setup, which can affect the developers later on if we remove those imports.
- User rxjs function call chaining rather than patch imports
> feat(rxjs): remove uses of rxjs patch operators

- package.json
- src/platform/core/layout/layout-toggle.class.ts
when the route changes without the sidenav opening/closing, the visibility check wasnt toggled and the element wasnt hidden.
now we execute the visibility method in `ngAfterViewInit` always.
> fix(layout): fix layout directives not hidden element in certain scenarios

- src/platform/core/common/behaviors/disable-ripple.mixin.ts
- src/platform/core/common/behaviors/disabled.mixin.ts
- src/platform/core/common/common.module.ts
- src/platform/core/expansion-panel/expansion-panel.component.ts
- src/platform/core/steps/step-header/step-header.component.ts
- src/platform/core/steps/step.component.ts
Second mixin for common behaviors.
- `ICanDisableRipple` interface
- `mixinDisableRipple` mixin
- use of both in stepper and expansion panel
> feat(behaviors): abstract disableRipple inputs and create mixin for reuse

- .travis.yml
- README.md
- package.json
- src/app/components/docs/build-tasks/build-tasks.component.html
- src/app/components/docs/overview/overview.component.html
- src/platform/core/package.json
- src/platform/dynamic-forms/package.json
- src/platform/highlight/package.json
- src/platform/http/package.json
- src/platform/markdown/package.json
update node to 6.11.1 due to this vulnerability:
https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
What's included?
package.json
platform/X/package.json
.travis.yml
README.md
> chore(): update node engine to 6.11.1

- src/platform/core/data-table/data-table.component.ts
also, when clicking on uncheck all, we only uncheck the items that are in the current data array
> perf(data-table): make checkbox state check more performant

- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/paging/paging.component.html
- src/app/components/components/paging/paging.component.ts
- src/app/components/style-guide/management-list/management-list.component.html
- src/app/components/style-guide/management-list/management-list.component.ts
- src/platform/core/paging/README.md
- src/platform/core/paging/paging-bar.component.html
- src/platform/core/paging/paging-bar.component.scss
- src/platform/core/paging/paging-bar.component.spec.ts
- src/platform/core/paging/paging-bar.component.ts
- src/platform/core/paging/paging.module.ts
instead of having the paging bar render the `md-select` from material, we are gonna abstract it and add tons of examples on how people can leverage the paging-bar API to add a page size `md-select`, or `md-input` `go to` navigation + other examples. 
This will allow the module to be more lightweight, plus be flexible enough to allow anything in the bar without binding it to certain components nor wrapping them and letting users provide their own translation strings for the content.
This will also allow the paging-bar to be more responsive and the user can pick and choose what to show/hide depending on screen size https://github.com/Teradata/covalent/issues/533
Will also take care of https://github.com/Teradata/covalent/issues/520 since now it's up to the user to show/hide the `md-select` …
> feat(paging): refactor paging bar to allow devs leverage API for multiple usages

- src/platform/core/chips/chips.component.ts
since we are stopping the propagation of the click event for chips, this causes some issues with autocomplete since its listening to it
closes #783
> fix(chips): close manually autocomplete menu on mousedown

- src/app/components/components/dynamic-forms/dynamic-forms.component.html
- src/app/components/components/dynamic-forms/dynamic-forms.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.scss
- src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.ts
- src/platform/dynamic-forms/dynamic-forms.module.ts
- src/platform/dynamic-forms/index.ts
- src/platform/dynamic-forms/services/dynamic-forms.service.ts
Upstreamed Dynamic File Input from AppCenter. Modified the name from `upload` to `file-input`.
- Added new file input into dynamic forms
- Added docs & demo on http://localhost:4200/#/components/dynamic-forms
> feat(dynamic-form): Added dynamic file input

- package.json
- src/app/components/components/components.component.ts
- src/app/components/components/components.module.ts
- src/app/components/components/components.routes.ts
- src/app/components/components/overview/overview.component.ts
- src/app/components/components/text-editor/text-editor.component.html
- src/app/components/components/text-editor/text-editor.component.scss
- src/app/components/components/text-editor/text-editor.component.ts
- src/app/components/toolbar/toolbar.component.ts
Added demo for Covalent Text/Markdown Editor into Covalent Docs
- new file:   src/app/components/components/text-editor/text-editor.component.html
- new file:   src/app/components/components/text-editor/text-editor.component.scss
- new file:   src/app/components/components/text-editor/text-editor.component.ts
- modified:   package.json
- modified:   src/app/components/components/components.component.ts
- modified:   src/app/components/components/components.module.ts
- modified:   src/app/components/components/components.routes.ts
- modified:   src/app/components/components/overview/overview.component.ts
- modified:   src/app/components/toolbar/toolbar.component.ts
> feat(docs): Covalent Text/Markdown Editor Demo

- package.json
- scripts/combat-training
- src/app/components/style-guide/iconography/iconography.component.html
- src/tsconfig.app.json
- yarn.lock
Upgrade CLI to address some AoT errors introduced in 1.2.0 cli dependencies.
Note: AoT is failing because of CovalentTextEditor which will be fixed in a separate PR
> feat(dependencies): upgrade angular/cli to 1.2.7

- src/app/components/components/animations/animations.component.html
- src/app/components/components/animations/animations.component.ts
- src/app/components/components/components.component.ts
- src/app/components/components/components.module.ts
- src/app/components/components/components.routes.ts
- src/app/components/components/overview/overview.component.ts
- src/platform/core/common/animations/index.ts
- src/platform/core/common/animations/rotate/rotate.animation.ts
- src/platform/core/common/common.module.ts
- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.ts
Stepping stone for animation utilities to be consumable publicly. This PoC contains both implementation and documentation for the first of the utilities, rotate animation utility. This lays a general structure for future animation utilities to build upon.
I applied the rotate animation utility internally to the covalent expansion panel as an example use case. When opening and closing the expansion panel the `keyboard_arrow_down` icon will rotate accordingly. 
The plan is to start off by delivering many pre-canned modular animations utilities (commonly used animations) that can be easily applied to any template element. Next is to have many pre-canned route animations. Far beyond that we plan to research ways to make it easier to create custom/complex Angular based animations. 
- Rotate …
> feat(animations): add rotate animation utility function and documentation

- src/app/components/components/loading/loading.component.html
Fix link to asterisk syntax
Update url to correct documentation. 
This is only a change in documentation.
> docs(loader): fix link to * syntax docs

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR uses comments for instructions within issue templates rather than plain text. This helps clean up how issues are displayed when people don't remove instructions,
- Issue template
- PR template
> chore(): use comments in issue templates

- src/platform/core/common/styles/_variables.scss
Following https://github.com/Teradata/covalent/issues/851 there was a variable usage that was renamed with the `mat` preffix.. and the variable was preffixed with `md` on its definition.
- Added missing variable to `_elevation.scss`
closes https://github.com/Teradata/covalent/issues/851
> fix(scss): missing scss variables for scss compilation (closes #851)

- src/app/components/components/dynamic-forms/dynamic-forms.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.html
- src/platform/dynamic-forms/services/dynamic-forms.service.ts
* feat(): Select input label and values separated
- Create TdDynamicElement.Select with selections as array of objects eg. {label: "Label", value: "MyValue"}
- As backcompat create TdDynamicElement.Select with selections as array of strings
* docs(dynamic-forms): update docs to reflex new select definition
Add custom values for select on dynamic forms
Update docs about it
- new way of define collection for select in dynamic forms
> feat(dynamic-forms): dynamic forms select values (#802)

- src/app/components/components/components.component.ts
- src/app/components/components/components.module.ts
- src/app/components/components/components.routes.ts
- src/app/components/components/overview/overview.component.ts
- src/app/components/components/virtual-scroll/virtual-scroll.component.html
- src/app/components/components/virtual-scroll/virtual-scroll.component.ts
- src/platform/core/index.ts
- src/platform/core/virtual-scroll/README.md
- src/platform/core/virtual-scroll/virtual-scroll-container.component.html
- src/platform/core/virtual-scroll/virtual-scroll-container.component.scss
- src/platform/core/virtual-scroll/virtual-scroll-container.component.spec.ts
- src/platform/core/virtual-scroll/virtual-scroll-container.component.ts
- src/platform/core/virtual-scroll/virtual-scroll-row.directive.ts
- src/platform/core/virtual-scroll/virtual-scroll.module.ts
This is the initial implementation of the virtual-scroll component. The initial use case that this will solve it to be able to render thousands of rows (e.g. md-list) without consuming all browser resources.
- `TdVirtualScrollComponent` and `TdVirtualScrollRow` components.
- `virtual-scroll` demo and docs.
- `virtual-scroll` README
> feat(virtual-scroll): initial implementation of virtual scroll component

- src/app/components/components/dynamic-forms/dynamic-forms.component.html
- src/app/components/components/dynamic-forms/dynamic-forms.component.ts
- src/platform/dynamic-forms/README.md
- src/platform/dynamic-forms/dynamic-element.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.html
- src/platform/dynamic-forms/dynamic-forms.component.spec.ts
- src/platform/dynamic-forms/services/dynamic-forms.service.ts
Add minLength and maxLength validation for text text fields.
-`minLength` validation option for dynamic elements
-`maxLength` validation option for dynamic elements
- unit tests
> feat(dynamic-forms): 577 add minLength and maxLength validations

- src/app/components/design-patterns/alerts/alerts.component.html
- src/app/components/design-patterns/cards/cards.component.html
- src/app/components/design-patterns/management-list/management-list.component.html
- replace all href elements with routerLink in all patterns pages
Currently using href for links.  Replace with routerLink using the format: 
<a [routerLink]="['path', 'path']>Text</a>
- Fixes for all current patterns
- Point to design-patterns for management-list (currently, points to removed page in style section)
> chore(patterns): use routerLink

- src/app/components/style-guide/colors/colors.component.html
Removing links to pages that no longer exist.
- Removal of OSX Material Design System Color Picker link
> chore(): URLs to pages that no longer exist in style-guide/colors doc

- src/platform/core/paging/paging-bar.component.scss
There was some scss bleeding because of the use of `/deep/` in the paging scss, which should only affect the md/mat select components directly under the paging bar.
closes https://github.com/Teradata/covalent/issues/872
> fix(paging): stop css bleed to all md-selects from paging scss

- src/app/components/components/json-formatter/json-formatter.component.ts
- src/platform/core/json-formatter/json-formatter.component.ts
Tuples and array of arrays were presented improperly in the json formatter.
closes https://github.com/Teradata/covalent/issues/852
> fix(json-formatter): represent array of arrays properly

- src/platform/core/virtual-scroll/virtual-scroll-container.component.spec.ts
- src/platform/core/virtual-scroll/virtual-scroll-container.component.ts
After the `data` input was cleared and then populated, the pseudo height was improperly calculated 
closes https://github.com/Teradata/covalent/issues/878
> fix(virtual-scroll): re-render rows with proper height when replacing the data input

- src/platform/core/data-table/data-table-column/data-table-column.component.html
- src/platform/core/data-table/data-table-column/data-table-column.component.ts
- src/platform/core/data-table/data-table.component.html
- src/platform/core/data-table/data-table.component.scss
- src/platform/core/data-table/data-table.component.ts
Also add possibility to override projected min width via configuration
closes https://github.com/Teradata/covalent/issues/891
- `ng serve`
- See that now the projected min width per column isnt 100px, but whatever the column header width is at a minimum
- Override it via column configuration
> fix(data-table): replace hardcoded 100px min width with projected width

- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
- src/app/services/internal-docs.service.ts
- src/platform/core/data-table/data-table-cell/data-table-cell.component.scss
- src/platform/core/data-table/data-table-row/data-table-row.component.ts
- src/platform/core/data-table/data-table.component.html
- src/platform/core/data-table/data-table.component.ts
now we will cache the height of every row and recalculate the height as we keep scrolling
> feat(data-table): allow dynamic row heights in data table even when using its virtual scroll

- src/platform/core/common/platform.scss
- src/platform/core/common/styles/_content.scss
- src/platform/core/common/styles/_mixins.scss
- src/platform/core/common/styles/_shadows.scss
- src/platform/core/common/styles/_structure.scss
- src/platform/core/common/styles/_typography.scss
- src/platform/core/common/styles/_variables.scss
- src/platform/core/common/styles/_whiteframe.scss
- src/platform/core/common/styles/font/_font.scss
- src/platform/core/steps/_steps-theme.scss
Add mat- prefixes for all utility classes.. ignoring typography since that would clash with the material repos typography
> chore(): add mat- prefixes to all our md- prefixed classes (ignoring typography)

- src/app/components/components/media/media.component.html
- src/app/components/components/media/media.component.ts
- src/platform/core/media/services/media.service.ts
Fix for TdMediaService doesn't trigger Portrait or Landscape
closes #922
- modified:   src/platform/core/media/services/media.service.ts
> bugfix(mediaService): Fix for TdMediaService doesn't trigger Portrait or Landscape

- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
- src/platform/core/data-table/data-table.component.html
Change the behavior of sortable in the data-table as described in #933
closes #933
- Prioritize per column setting of sortable (allow override)
> Prioritize column setting for sortable

- src/app/app.component.html
- src/app/app.component.ts
- src/app/components/toolbar/toolbar.component.html
- src/app/components/toolbar/toolbar.component.ts
Add toggle button to switch between dark and light themes
- modified:   src/app/app.component.html
- modified:   src/app/app.component.ts
- modified:   src/app/components/toolbar/toolbar.component.html
- modified:   src/app/components/toolbar/toolbar.component.ts
> feat(theme): Add menu button to switch between dark and light themes

- src/app/components/components/loading/loading.component.html
- src/app/components/components/loading/loading.component.ts
- src/platform/core/loading/loading.component.html
- src/platform/core/loading/loading.component.ts
- src/platform/core/loading/services/loading.factory.ts
With the latest material changes, the loading component was not setting the heights properly since we need to take into account the `[diameter]` and `[strokeWidth]` inputs now.
>  fix(loading): get proper heights for overlay strategy

- src/app/components/components/loading/loading.component.html
- src/platform/core/loading/loading.component.html
- src/platform/core/loading/loading.component.scss
Remove blocking background from linear loader
closes #823
- modified:   src/app/components/components/loading/loading.component.html
- modified:   src/platform/core/loading/loading.component.html
- modified:   src/platform/core/loading/loading.component.scs
> feat(loader): Remove blocking background from linear loader

- src/app/components/docs/angular-material/angular-material.component.html
Fix broken URL in Angular Material docs page.
- `#feature-status` -> `#available-features`
Click the link and verify that it brings you to the section of the docs related to features.
N/A
> docs(angular-material): fix broken URL

- src/app/components/components/search/search.component.html
- src/app/components/components/search/search.component.ts
- src/platform/core/search/search-box/search-box.component.html
- src/platform/core/search/search-box/search-box.component.ts
- src/platform/core/search/search-input/search-input.component.html
- src/platform/core/search/search-input/search-input.component.ts
Make icons of 'Search Box' and 'Search Input' customizable
closes #420
- modified:   src/app/components/components/search/search.component.ts
- modified:   src/platform/core/search/search-box/search-box.component.html
- modified:   src/platform/core/search/search-box/search-box.component.ts
- modified:   src/platform/core/search/search-input/search-input.component.html
- modified:   src/platform/core/search/search-input/search-input.component.ts
```
<td-search-box clearIcon="swap_horiz" searchIcon="info_outline" backIcon="info_outline" *ngIf="!debounce" placeholder="Search here" [alwaysVisible]="alwaysVisible" (search)="searchBoxTerm = $event" (clear)="searchBoxTerm = ''" flex></td-search-box>
```
> feat(search): Make icons of 'Search Box' and 'Search Input' customizable

- src/platform/core/virtual-scroll/virtual-scroll-container.component.html
When using virtual scroll in a narrow area, the elements inside it had a bigger width than expected.
This is fixed by setting the virtual scroll width to 100%.
> fix(virtual-scroll): fix issue with virtual scroll not respecting the parent's width

- src/platform/core/steps/step-body/step-body.component.html
- src/platform/core/steps/step-body/step-body.component.scss
- src/platform/core/steps/step-header/step-header.component.html
- src/platform/core/steps/step-header/step-header.component.scss
- src/platform/core/steps/steps.component.html
- src/platform/core/steps/steps.component.scss
- `stepper` wont depend on `_layout.scss` anymore.
> feat(stepper): stop depending on layout.scss

- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.scss
- `expansion-panel` wont depend on `_layout.scss` anymore.
> feat(expansion-panel): stop depending on layout.scss

- src/platform/core/chips/chips.component.html
- src/platform/core/chips/chips.component.scss
- `chips` wont depend on `_layout.scss` anymore.
> feat(chips): stop depending on layout.scss

- src/platform/core/loading/loading.component.html
- src/platform/core/loading/loading.component.scss
- `loading` wont depend on `_layout.scss` anymore.
> feat(loading): stop depending on layout.scss

- src/platform/core/dialogs/dialog.component.html
- src/platform/core/dialogs/dialog.component.scss
- src/platform/core/dialogs/prompt-dialog/prompt-dialog.component.html
- src/platform/core/dialogs/prompt-dialog/prompt-dialog.component.scss
- `dialogs` wont depend on `_layout.scss` anymore.
> feat(dialog): stop depending on layout.scss

- src/platform/core/steps/step-body/step-body.component.html
- src/platform/core/steps/step-body/step-body.component.scss
- src/platform/dynamic-forms/dynamic-elements/dynamic-checkbox/dynamic-checkbox.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.scss
- src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.scss
- src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.scss
- src/platform/dynamic-forms/dynamic-elements/dynamic-slide-toggle/dynamic-slide-toggle.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-slider/dynamic-slider.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-slider/dynamic-slider.component.scss
- src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.scss
- src/platform/dynamic-forms/dynamic-forms.component.html
- src/platform/dynamic-forms/dynamic-forms.component.scss
- src/platform/dynamic-forms/dynamic-forms.component.ts
- `dynamic-forms` wont depend on `_layout.scss` anymore.
> feat(dynamic-forms): stop depending on layout.scss

- src/platform/core/layout/layout-card-over/layout-card-over.component.html
- src/platform/core/layout/layout-card-over/layout-card-over.component.scss
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.html
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.scss
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.scss
- src/platform/core/layout/layout-nav/layout-nav.component.html
- src/platform/core/layout/layout-nav/layout-nav.component.scss
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.html
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.scss
- `layouts` wont depend on `_layout.scss` anymore.
> feat(layout): stop depending on layout.scss

- src/app/components/components/ngx-charts/ngx-charts.component.html
- src/app/components/style-guide/utility-styles/utility-styles.component.html
- src/platform/core/common/styles/utilities/_pad.scss
- src/platform/core/common/styles/utilities/_pull.scss
- src/platform/core/common/styles/utilities/_push.scss
- src/platform/core/message/message.component.html
Aligns utility baselines to the [material design spec](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-baseline-grids), which indicates
> All components align to an 8dp square baseline grid for mobile, tablet, and desktop. Iconography in toolbars align to a 4dp square baseline grid.
This PR also tries to clean up the utility styles and improve the documentation.
Closes #919
The `.push-bottom-button`, `.pad-bottom-button`, and `.pull-bottom-xxxl` classes have been removed. Additionally, the sizes of the `.push`, `.pad`, and `.pull` classes has changed slightly.
- push/pad/pull none `0 -> 0` (no change)
- push/pad/pull xs `5px -> 4px`
- push/pad/pull sm `10px -> 8px`
- push/pad/pull (no size) `20px -> 16px`
- push/pad md `30px -> 24px`
- push/pad lg `40px -> …
> feat(utilities): change push/pad/pull utility baselines to be based on 4px

- src/platform/core/data-table/data-table-cell/data-table-cell.component.html
- src/platform/core/data-table/data-table-cell/data-table-cell.component.scss
- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.scss
- src/platform/core/json-formatter/json-formatter.component.html
- src/platform/core/json-formatter/json-formatter.component.scss
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.html
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.scss
- src/platform/core/menu/menu.component.html
- src/platform/core/menu/menu.component.scss
- src/platform/core/message/message.component.html
- src/platform/core/message/message.component.scss
- src/platform/core/paging/paging-bar.component.html
- src/platform/core/paging/paging-bar.component.scss
- src/platform/core/search/search-box/search-box.component.html
- src/platform/core/search/search-box/search-box.component.scss
- src/platform/core/search/search-input/search-input.component.html
- src/platform/core/search/search-input/search-input.component.scss
- no modules will depend on `_layout.scss` anymore.
> feat(all): stop depending on layout.scss cleanup

- .angular-cli.json
- src/platform/markdown/README.md
- src/platform/markdown/markdown.component.ts
The showdown.js lib needed to be included via `index.html` or `.angular-cli.json` file, now it will be pulled from the `node_modules` via `require` like `highlight` does.
> feat(markdown): make markdown include showdown.js implicitly

- package.json
- scripts/rollup.js
- src/platform/core/chips/chips.component.ts
- src/platform/core/common/services/router-path.service.ts
- src/platform/core/data-table/data-table.component.ts
- src/platform/core/loading/directives/loading.directive.spec.ts
- src/platform/core/search/search-input/search-input.component.ts
- src/platform/http/http-rest.service.ts
- src/platform/http/interceptors/http-interceptor.service.spec.ts
- yarn.lock
Since we had a small dependency to the `cdk/rxjs` module of material, this would allow us to do replace `RxChain` and leverage `pipe()` to pipe operations with observables.
This will also make us follow the same standards as material, and prepare for their next release as they removed the `cdk/rxjs` module in favor of `rxjs/operators`
- Upgrade to `rxjs@5.5.0`
- Switch to lettable operators
- Leverage `pipe()` when possible
- Stop depending on `cdk/rxjs`
> feat(): upgrade to rxjs@5.5.0 and switch to lettable operators

- src/platform/core/layout/layout-manage-list/layout-manage-list.component.scss
Since we removed the layout.scss styles from the layout module, adding some styles by default actually introduced errors, in this case the rules for `md-content` were getting in the way.
> fix(layout): fix proper width for manage-list layout

- scripts/rollup.js
- src/app/app.component.ts
- src/app/components/components/components.component.ts
- src/app/components/components/paging/paging.component.html
- src/app/components/components/paging/paging.component.ts
- src/app/components/design-patterns/design-patterns.component.ts
- src/app/components/docs/docs.component.ts
- src/app/components/layouts/manage-list/manage-list.component.html
- src/app/components/layouts/manage-list/manage-list.component.ts
- src/app/components/layouts/nav-list/nav-list.component.html
- src/app/components/layouts/nav-list/nav-list.component.ts
- src/app/components/style-guide/style-guide.component.ts
- src/app/components/templates/templates.component.ts
- src/platform/core/layout/layout-toggle.class.ts
- src/platform/core/media/services/media.service.ts
To avoid the use of broadcast on every page load, the media service Subjects will change to leverage BehaviorSubject's so the value is read upon subscription.
- fix(layout): issue when layouts are rendered for the first time in opened mode
- chore(rollup): add BehaviorSubject to rollup build
- fix(docs): remove `changeDetection` and broadcast on ngAfterViewInit
> feat(media): change to BehaviorSubject to stop the use of broadcast method on page load

- src/app/components/components/data-table/data-table.component.html
There is not call to action when a row is clicked at the documentation.
Just completed the documentation. Included at the td-data-table element the call to action placed at the Code Tab.
> chore(data-table): td-data-table missing (rowClick) at "Code" tab

- src/platform/core/loading/loading.component.ts
when calculating the diameter on the fly for the circular loading, there was a change detection error when not in `OnPush`.
the solution is to calculate it only once before rendering the loader
closes #972
> fix(loading): change detection error in overlay mode

- src/platform/core/message/message.component.ts
for some reason having 2 host animations on a component combined with ngIf makes the component stay when setting the ngIf input as false, and because of that when setting it back to true it adds it again
closes #981
> fix(message): remove second host animation since it makes ngIf duplicate the component

- src/platform/core/steps/step-body/step-body.component.html
- src/platform/core/steps/step-body/step-body.component.ts
When using a loader in replace mode to wrap multiple elements, the number of elements in the step content would change, and this would throw a change detection error since we were checking for the number of children.
The fix is to check if there is at least 1 child element, we dont care how many.
> fix(stepper): fix change detection issue when number of step content children changed

- src/platform/core/data-table/services/data-table.service.ts
Copy the sorted array to ensure that `OnPush` change detection is triggered when sorting data table. This also prevents the original array from being mutated.
- Add an array copy to the `TdDataTableService.sortData()` method
_full disclosure: I have not manually tested this yet_
[Example of broken sorting based on docs demo](http://plnkr.co/edit/K4BL9BP7kjGUIXI3hwiI?p=preview)
This PR was prompted by a [gitter question](https://gitter.im/Teradata/covalent?at=5a2029b6540c78242d69c1cb)
> Copy array on data table sort

- package.json
- src/platform/core/data-table/data-table.component.html
- src/platform/core/data-table/data-table.component.spec.ts
- src/platform/core/data-table/data-table.component.ts
- yarn.lock
`index` property is added to both `rowClick` and `rowSelect` output events.
closes #992
> feat(data-table): add index to row select and row click outputs

- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- README.md
- docs/RELEASE.md
- package.json
- scripts/combat-training
- yarn.lock
- Renamed a few aliases so they are grouped better.
- Added alias `npm run bundle-report` to check the build sizes
- Updated docs with new aliases
> chore(): rename some of the aliases so they are more intuitive

- src/platform/core/layout/layout-toggle.class.ts
Making we leverage the disable mixin everywhere we use a disable input.
> feat(): make LayoutToggle class reuse disable mixin

- src/platform/core/chips/chips.component.ts
This input was deprecated in beta.6, so we are just removing it from the codebase.
> feat(chips): remove deprecated `readOnly` input

- src/app/app.component.html
We forgot to remove the `media` service checkup to see when to close the main sidenav.. because of that it looked like it didnt work. This PR makes sure the main sidenav closes in any case.
> fix(docs): close sidenav properly when clicking on it in any scenario

- src/platform/core/chips/chips.component.ts
- src/platform/core/common/behaviors/control-value-accesor.mixin.spec.ts
- src/platform/core/common/behaviors/control-value-accesor.mixin.ts
- src/platform/core/common/common.module.ts
- src/platform/core/data-table/data-table.component.ts
- src/platform/core/file/file-input/file-input.component.ts
- src/platform/core/file/file-upload/file-upload.component.ts
Creating a mixin that adds ngModel support (implementing IControlValueAccessor) to avoid duplicating the same code over and over in the components where we wanted this.
- `mixinControlValueAccesor` mixin
- Leverage in chips, data-table, file-input and file-upload
>  feat(mixin): add ngModel mixin for reuse (control value accessor)

- src/app/components/components/file-upload/file-upload.component.html
- src/platform/core/file/file-upload/README.md
- src/platform/core/file/file-upload/file-upload.component.spec.ts
- src/platform/core/file/file-upload/file-upload.component.ts
This property was deprecated in beta.6, so we are just removing it from the codebase.
> feat(file): remove deprecated `files` variable

- src/platform/core/json-formatter/json-formatter.component.html
- src/platform/core/json-formatter/json-formatter.component.scss
Show functions, dates and array lengths properly in RTL when using the `json-formatter` component,
Part of https://github.com/Teradata/covalent/issues/323
> feat(json-formatter): support properly RTL

- src/app/components/components/search/search.component.ts
- src/platform/core/search/search-box/search-box.component.ts
- src/platform/core/search/search-input/search-input.component.ts
Making sure `td-search-box` and `td-search-input` work on OnPush change detection strat.
> feat(search): support OnPush change detection strat

- src/app/components/components/paging/paging.component.ts
- src/platform/core/paging/paging-bar.component.ts
Making sure `td-paging-bar` works on OnPush change detection strat.
Part of https://github.com/Teradata/covalent/issues/325
> feat(paging): support OnPush change detection strat

- src/app/components/components/search/search.component.html
- src/platform/core/search/search-box/search-box.component.html
- src/platform/core/search/search-box/search-box.component.spec.ts
- src/platform/core/search/search-box/search-box.component.ts
- src/platform/core/search/search-input/search-input.component.spec.ts
- src/platform/core/search/search-input/search-input.component.ts
This leverages the mixin for controlValueAccessor for both the `td-search-input` and `td-search-box`
closes https://github.com/Teradata/covalent/issues/995
> feat(search): add ngModel support to search-input and search-box

- src/platform/core/notifications/README.md
Added missing closing tags for mat-icon tag.
Updated closing tags for mat-icon in README.md file.
- Closing tags were missing. Updated in README.md file.
> Missing closing tags on example code on notifications page #759

- src/app/components/components/notifications/notifications.component.html
Fixes margin of menu header in notifications demo since the material typography adds a bottom margin by default.
closes https://github.com/Teradata/covalent/issues/1038
> fix(notifications): fix menu header margin in demo (closes #1038)

- src/app/components/components/components.module.ts
- src/app/components/components/dynamic-forms/dynamic-forms.component.html
- src/app/components/components/dynamic-forms/dynamic-forms.component.ts
- src/platform/dynamic-forms/README.md
- src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.scss
- src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.spec.ts
- src/platform/dynamic-forms/dynamic-forms.module.ts
- src/platform/dynamic-forms/services/dynamic-forms.service.ts
Add support for `mat-datepicker` to the `dynamic-forms` module.. this way we can now render datepicker elements dynamically.
- Datepicker support.
- Unit tests
- Updated DEMO and README
closes https://github.com/Teradata/covalent/issues/584
> feat(dynamic-forms): add datepicker support (closes #584)

- src/platform/core/data-table/data-table.component.html
This makes it possible to apply different styles to header and body easier. 
Changes in data-table HTML to make body and header distinguishable.
> Make table header and body distinguishable

- src/platform/core/expansion-panel/expansion-panel.component.html
- src/platform/core/expansion-panel/expansion-panel.component.scss
We fixed the label in the expansion-panel when a sublabel is not used so it flexes properly.
Also we changed the margin on labels and header to follow the MD Spec properly
closes https://github.com/Teradata/covalent/issues/1057
> fix(expansion-panel): let label flex without sublabel + follow MD spec better (closes #1057)

- docs/RELEASE.md
- package.json
- scripts/finish-release
- scripts/start-release
- yarn.lock
Leveraging the CLI of the [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) we will be able to automatically generate a first draft of it.. it still need to be reviewed to make sure its proper but this will reduce the time it takes to do so. (following https://conventionalcommits.org/)
For it to work properly though, we need to stop using the `git flow start/finish` release process and use our own to be able to tag properly the release commit and merge it to master. (since with `git flow` the release commit is generated with diff SHA in master and develop)
- added command `npm run generate:changelog`
- Updated RELEASE.md with new steps
closes https://github.com/Teradata/covalent/issues/307
> chore(release): change release process and add conventional-changelog (closes #307)

- src/app/documentation-tools/index.ts
- src/app/documentation-tools/pretty-markdown/cfm-list/cfm-list.component.html
- src/app/documentation-tools/pretty-markdown/cfm-list/cfm-list.component.ts
- src/app/documentation-tools/pretty-markdown/pretty-markdown.component.ts
- src/platform/core/chips/README.md
Since data-tables arent really responsive, we want to be able to showcase a list for our API properties and events. This means our internal `pretty markdown` module has to support them
For this we are going to use the `+` list syntax of `markdown` to replace with a `mat-list`
e.g.
```
+ item 1
+ item 2
```
Also we can use sublists to add more information to a single item leveraging `matLine`
e.g.
```
+ line 1
+ subline 1
+ subline 2
+ sline 2
```
plus added example in chips README.md
- Support for lists in pretty markdown component
- Replaces data-table in chips with list
closes https://github.com/Teradata/covalent/issues/900
> feat(docs): support list in pretty markdown to showcase API's better (closes #900)

- src/platform/core/data-table/README.md
Sinde now we support list rendering from markdown, we are going to show the API's as lists rather than data-tables.
> feat(data-table): change API from data-table representation to lists

- src/platform/core/expansion-panel/README.md
Sinde now we support list rendering from markdown, we are going to show the API's as lists rather than data-tables.
> feat(expansion-panel): change API from data-table representation to lists

- src/app/components/components/data-table/data-table.component.html
- tslint.json
- yarn.lock
Upgrade `yarn.lock` in docs repo to use latest angular and material.
> chore(): upgrade yarn to latest material@5.0.4 and angular 5.2.0

- src/platform/core/file/file-input/README.md
> feat(file-input): change API from tables to lists

- src/platform/dynamic-forms/README.md
Sinde now we support list rendering from markdown, we are going to show the API's as lists rather than data-tables.
> feat(dynamic-forms): replace API data-table with list in README

- src/platform/core/file/file-upload/README.md
> feat(file-upload): change API from tables to lists 

- src/platform/core/layout/README.md
- src/platform/core/layout/layout-card-over/README.md
- src/platform/core/layout/layout-manage-list/README.md
- src/platform/core/layout/layout-nav-list/README.md
- src/platform/core/layout/layout-nav/README.md
> feat(layout): change API from tables to lists

- src/platform/core/paging/README.md
Show the API's as lists rather than data-tables .
> feat(docs): change paging API from data-table to list

- src/platform/core/notifications/README.md
> feat(notifications): change API from tables to lists

- src/platform/core/message/README.md
> feat(messages): change API from tables to lists

- src/platform/core/search/search-input/search-input.component.ts
Initializing ngModel was triggering an undesired `(searchDebounce)` event, with this we are sure to skip the first one regardless if its undefined or initialized.
> fix(search-input): make sure initializing ngModel doesnt trigger a debounce

- package.json
- yarn.lock
Remove phantomjs dependency
- package.json
> chore(dependencies): Remove phantomjs dependency

- docs/GETTING_STARTED.md
The SystemJS documentation in our GETTING_STARTED was out dated since we change our build process to be more inline with the `Angular Build Format`. This PR updates it to use the proper `umd` files.
> chore(): update SystemJS config setup in GETTING_STARTED

- docs/RELEASE.md
- scripts/finish-release
When doing `git merge develop` onto `master`.. this generated an extra commit .. this is because git has to generate an extra commit sometimes to be able to merge both histories.. the real way of doing this is via `rebase`.
> chore(): fix release script to rebase instead of merge

- src/app/components/components/loading/loading.component.html
Fixed type in documentation of Loading component
- bugfix(loading): changed `items` to `itemList`
> bugfix(loading): fixed incorrect variable name

- docs/RELEASE.md
- scripts/npm-publish
Update `publish` script to handle `next` tag as well as `latest` tag.
- `npm run publish:npm` now accepts an argument to be able to publish modules with `tag=next`
> chore(): update script to allow publishing `next` or `latest` tags

- README.md
Fix npm link for github badges on Readme
- Updates to Readme
> Fix npm links for github badges on Readme

- src/platform/dynamic-forms/README.md
Added missing comma in docs example
- missing comma
> Added missing comma in docs example

- src/platform/core/search/search-box/search-box.component.ts
Clear value in search box when back arrow is tapped
Fixes bug found in issue:  [Covalent-1157](https://github.com/Teradata/covalent/issues/1157)
closes https://github.com/Teradata/covalent/issues/1157
> fix(search-box): back arrow clears search (closes #1157)

- docs/DEVELOPER_GUIDE.md
- package.json
- scripts/nightly-publish
- scripts/npm-publish
- src/platform/experimental/package.json
- src/platform/experimental/template-rename-me-experiment-module/rename-me.component.html
After speaking with Ed + Jeremy, experimental module should be bound to Covalent's versioning rather then be on it's own versioning and it should be consumed though it's own nightly build.
- Bound experimental's package.json `version` property to Covalent's build process.
- Experimental nightly build integration
// TODO: update with night build test instructions
> chore(): modify npm script and nightly script for experimental package

- package.json
- src/platform/experimental/README.md
Modify experimental README to explain how to run the test-bed
application and also how to install the experimental build
- rename `npm run serve:test-bed` to `npm run serve:experimental`
- Update experimental README on how to serve and how to install
> chore(): rename `npm run serve:test-bed` to `npm run serve:experimental`

- src/platform/core/data-table/data-table.component.ts
Fix for Select All Rows doesn't trigger ngModelChange
Added `this.onChange(this.value);` to selectAll method
```
<td-data-table
#dataTable
[data]="filteredData"
[columns]="columns"
[selectable]="selectable"
[clickable]="clickable"
[multiple]="multiple"
[sortable]="true"
[sortBy]="sortBy"
[(ngModel)]="selectedRows"
(ngModelChange)="getDataArray(selectedRows)"
[sortOrder]="sortOrder"
(sortChange)="sort($event)"
(rowClick)="showAlert($event)">
</td-data-table>
```
```
getDataArray(rows: any): void {
for (let i: number = 0; i < rows.length; i++) {
// do something
console.log(rows[i];
}
}
```
> fix(datatable): Fix for Select All Rows doesn't trigger ngModelChange

- src/app/components/docs/deployment/deployment.component.html
- src/app/components/docs/docs.component.ts
Removed section in docs about using ng github-pages:deploy
closes #576 
- Updated documentation
> fix(docs): GitHub Deployment Docs out of date

- src/platform/core/data-table/data-table.component.ts
Row selection checkbox incorrectly fires row click event
closes #1123 
Correct checking of event target for Firefox
> fix(datatable): Firefox - Row selection checkbox incorrectly fires row click event

- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
When jumping to last page and then applying a filter like search on the data, need to jump back to the first page.
closes: #1202 
- modified:   src/app/components/components/data-table/data-table.component.ts
The data table shows the results, the paging bar shows rows per page 50, 1-3
> fix(paging): Fix paging demo with search to jump to page 1 after searching

- src/platform/experimental/breadcrumbs/breadcrumbs.component.ts
* Change to import creation methods from rxjs. Without this change, consumers
of covalent are obligated to install rxjs-compat.
Closes #1208
Minor fix to imports in an experimental module.
Does not apply.
> fix(breadcrumbs): clean up imports of observable creation methods

- src/app/components/components/dynamic-forms/dynamic-forms.component.html
- src/app/components/components/dynamic-forms/dynamic-forms.component.ts
- src/platform/dynamic-forms/README.md
- src/platform/dynamic-forms/dynamic-element.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.html
properly leveraging the mat-error element on components that use
mat-form-field fixes this issue, but to achieve this we need to
refactor how the error message is shown
also add documentation on how to show the error message when creating a
custom component
- use mat-error when possible
- add info in README and demo on how to show error in custom component
> fix(dynamic-forms): make sure hints and errors dont overlap

- src/app/components/components/animations/animations.component.html
- src/app/components/components/animations/animations.component.ts
- src/platform/core/common/animations/rotate/rotate.animation.ts
- src/platform/core/expansion-panel/expansion-panel.component.ts
- Improved the rotate animation
- changes made were based on the [Animations Param Enhancement Doc](https://docs.google.com/document/d/18QT1kX3GchskE6PlZ3PfNCdv_DPAVoDPZpOS0e1Fan0/edit)
- Modded the pre-canned animation to allow usage of the Angular animations params feature.
- Deprecated the rotate animation pre-canned function.
> feat(animations): rotate animation params

- src/platform/core/data-table/README.md
Update Readme to add documentation about clickable input on datatable
closes #1010 
- src/platform/core/data-table/README.md
closes https://github.com/Teradata/covalent/issues/1010
> fix(docs): Add documentation about clickable input on datatable (closes #1010)

- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
Several bugs written about sorting by date on datatable.  Adding documentation to show how.
closes #674 
closes #461
closes #521
- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
> chore(docs): Adding Documentation for sorting by date

- src/app/components/components/animations/animations.component.html
- src/app/components/components/animations/animations.component.ts
- src/app/components/components/components.module.ts
- src/platform/core/common/animations/collapse/collapse.animation.ts
- Improved the collapse animation
- changes made were based on the [Animations Param Enhancement Doc](https://docs.google.com/document/d/18QT1kX3GchskE6PlZ3PfNCdv_DPAVoDPZpOS0e1Fan0/edit)
- Modded the pre-canned animation to allow usage of the Angular animations params feature.
- Deprecated the collapse animation pre-canned function.
> feat(animations): collapse animation params

- src/app/components/components/notifications/notifications.component.html
- src/platform/core/notifications/README.md
- src/platform/core/notifications/notification-count.component.spec.ts
- src/platform/core/notifications/notification-count.component.ts
Limit attribute is added to the td-notification-count component. When the notification count exceeds the limit set, it would display as {limit}+. It was initially hard coded as 99. Now it defaults to 99 but can be overridden by the user of this component.
- limit attribute added
> feat(notification): limit added

- src/platform/core/loading/README.md
fixes the typo mentioned in #1040
- changed `tdLoadingUtil` to `tdLoadingUntil`
> fix(docs): fix typo in docs #1040

- src/platform/core/layout/README.md
- src/platform/core/layout/layout-manage-list/README.md
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.html
- src/platform/core/layout/layout-manage-list/layout-manage-list.component.ts
- src/platform/core/layout/layout-nav-list/README.md
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.ts
- src/platform/core/layout/layout.component.html
- src/platform/core/layout/layout.component.ts
Allows setting `autosize` of the sidenav-container (#1230). Enables users for example to develop a mininav (see screenshot). 
- containerAutosize added to `td-layout`
- containerAutosize added to `td-layout-manage-list`
- containerAutosize added to `td-layout-nav-list`
Using autosize for a mininav.
> feat(layout): support autosize in layout #1230

- src/app/components/components/pipes/pipes.component.html
- src/app/components/components/pipes/pipes.component.ts
- src/platform/core/common/common.module.ts
- src/platform/core/common/pipes/time-until/time-until.pipe.spec.ts
- src/platform/core/common/pipes/time-until/time-until.pipe.ts
Added timeUntil pipe
closes #430 
- new file:   src/platform/core/common/pipes/time-until/time-until.pipe.spec.ts
- new file:   src/platform/core/common/pipes/time-until/time-until.pipe.ts
- modified:   src/app/components/components/pipes/pipes.component.html
- modified:   src/app/components/components/pipes/pipes.component.ts
- modified:   src/platform/core/common/common.module.ts
> feat(): Add timeUntil pipe

- src/platform/core/chips/chips.component.ts
Fixed select on Chips Autocomplete on mobile devices.
Closes #1044
* Modified: `src/platform/core/chips/chips.component.ts`
* Reason of the bug: `touchend` events is canceling `click` events on mobile
* Fix explanation: Added debounceTime to prevent both events from being fired together
> fix(chips): mobile select

- src/app/components/components/chips/chips.component.html
- src/platform/core/chips/chips.component.scss
Fixed long text inside chips
Closes #1102
**modified: src/platform/core/chips (multiple files modified)**
* Added `text-truncate` to chip content
* Added `min-width` to `.chip-content` to truncate flexbox children (see https://css-tricks.com/flexbox-truncated-text/)
* Simulated `flex="none"` to `.td-chip-content`
**modified: src/app/components/components/chips/chips.component.html (for truncate documentation)**
* Added `.text-truncate` class to docs
> fix(chips): long texts

- src/platform/experimental/breadcrumbs/breadcrumb/breadcrumb.component.html
- src/platform/experimental/breadcrumbs/breadcrumb/breadcrumb.component.scss
* Add new css class
* Reduces specificity of css selector used to style
the separator icon. Now the style is applied to the newly added class.
This makes the styling independent of the font-set class
associated to the icon, which is currently not the case.
Closes #1254
> fix(breadcrumbs): consistently align separator icons independent of their font-set class

- src/theme.scss
Fixes dark mode
- modified:   src/theme.scss to add dark mode to markdown and teradata branding themes
> fix(dark-mode): theme updates

- src/platform/core/breadcrumbs/breadcrumb/breadcrumb.component.html
- src/platform/core/breadcrumbs/breadcrumb/breadcrumb.component.scss
- src/platform/core/breadcrumbs/breadcrumb/breadcrumb.component.ts
- src/platform/core/breadcrumbs/breadcrumbs.component.html
- src/platform/core/breadcrumbs/breadcrumbs.component.scss
- src/platform/core/breadcrumbs/breadcrumbs.component.ts
Make sure we remove unnecessary elements from the `td-breadcrumbs` DOM.
e.g.
before
```
<td-breadcrumbs>
<div class="td-breadcrumbs">
<td-breadcrumb>
<span class="td-breadcrumb">
```
after
```
<td-breadcrumbs class="td-breadcrumbs">
<td-breadcrumb class="td-breadcrumb">
```
> feat(breadcrumbs): remove not needed elements from breadcrumbs

- src/app/components/components/dynamic-forms/dynamic-forms.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-checkbox/dynamic-checkbox.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-checkbox/dynamic-checkbox.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-slide-toggle/dynamic-slide-toggle.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-slide-toggle/dynamic-slide-toggle.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-slider/dynamic-slider.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-slider/dynamic-slider.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.scss
Added hints in for those elements that don't have built in `<mat-hint></mat-hint>` (ie. checkboxes, slide-toggles and sliders).
- Added hints to checkboxes
- Added hints to slide-toggles (booleans)
- Added hints to sliders
> fix(dynamic-forms):  added missing hints for checkboxes, slide-toggles and sliders

- src/app/components/components/virtual-scroll/virtual-scroll.component.ts
- src/platform/core/virtual-scroll/README.md
- src/platform/core/virtual-scroll/virtual-scroll-container.component.ts
Making some performance enhancements to check if the bottom has been reached only when scrolling.
Also making sure there are no memory leaks in the observables.
README updates for the bottom event.
> perf(virtual-scroll): leverage scroll event to check bottom reached

- src/platform/core/common/animations/collapse/collapse.animation.ts
this way we actually reduce the height of the element to 0 instead of it taking height out of the page
Also solves an issue where items with absolute position would still show up.
e.g.
`mat-tab` inside `td-expansion-panel`
> fix(animations): changing to overflow hidden instead of visibility hidden

- src/app/components/components/media/media.component.ts
- src/app/components/design-patterns/cards/cards.component.ts
- src/app/components/design-patterns/management-list/management-list.component.ts
- src/platform/core/common/animations/bounce/bounce.animation.ts
- src/platform/core/common/animations/collapse/collapse.animation.ts
- src/platform/core/common/animations/fade/fadeInOut.animation.ts
- src/platform/core/common/animations/flash/flash.animation.ts
- src/platform/core/common/animations/headshake/headshake.animation.ts
- src/platform/core/common/animations/jello/jello.animation.ts
- src/platform/core/common/animations/pulse/pulse.animation.ts
- src/platform/core/common/animations/rotate/rotate.animation.ts
Remove deprecated animation functions.
NOTE: We need to have migration steps in the CHANGELOG
> feat(animations): remove deprecated animation functions *BREAKING CHANGE*

- src/platform/core/data-table/data-table.component.ts
Since hidden elements reset their scroll by design, we need to check when that happens internally.
closes #1189
> fix(data-table): reset scroll when hiding element (closes #1189)

- src/platform/http/interceptors/http-interceptor.service.ts
Make sure response interceptor and response error interceptor are triggered in reverse error.
closes https://github.com/Teradata/covalent/issues/434
> fix(http): reverse execution of interceptors for response and response error

- src/platform/core/search/search-box/README.md
- src/platform/core/search/search-box/search-box.component.html
- src/platform/core/search/search-box/search-box.component.ts
Added (blur) event on Search Box. Closes #796
- Added (blur) event to Search Box
- Search-Input already had the blur event, so I just sent it through Search-Box
- Added the event to the documentation page, see http://localhost:4200/#/components/search
> feat(search): added blur event on search-box

- src/platform/highlight/highlight.component.ts
We need to wait until language is properly set before loading the content.
> fix(highlight): wrong language loaded initially when using content input

- src/app/components/components/dynamic-forms/dynamic-forms.component.html
- src/app/components/components/dynamic-forms/dynamic-forms.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.spec.ts
- src/platform/dynamic-forms/dynamic-forms.component.ts
Display Dynamic Forms error messages when adding error to controls through control.setErrors(...).
- Added Status Changes subscription on controls so we can detect changes when updating the control from outside
- New documentation "Manual Validators"
- Unit test
This PR fixes #1130
> fix(dynamic-forms): update template when manually adding errors to controls

- src/app/components/components/text-editor/text-editor.component.html
- src/app/components/components/text-editor/text-editor.component.ts
- src/platform/markdown/README.md
- src/platform/markdown/markdown.component.spec.ts
- src/platform/markdown/markdown.component.ts
- Adds `simpleLineBreaks` input to `<td-markdown/>`.
- Decided to default to `false` so it would be backwards-compatible.
- Thoughts on default state and input name?
- Fixes #1290
- New `simpleLineBreaks` input
- Updates to `<td-text-editor/>` demo 
- New tests
```
line 1
line 2
line 3
```
> feat(td-markdown): Add simpleLineBreaks input

- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
- src/platform/core/data-table/README.md
- src/platform/core/data-table/data-table-cell/data-table-cell.component.html
- src/platform/core/data-table/data-table-cell/data-table-cell.component.scss
- src/platform/core/data-table/data-table-cell/data-table-cell.component.ts
- src/platform/core/data-table/data-table.component.ts
Added properties 'cellAlign' on atomic components TdDataTableColumn and TdDataTableCell to align cell content.
Fixes #871 
- align: input property
> fix(data-table): Cell alignment 

- scripts/build-release
- src/platform/experimental/http/README.md
- src/platform/experimental/http/actions/class/http.decorator.ts
- src/platform/experimental/http/actions/index.ts
- src/platform/experimental/http/actions/methods/abstract-method.decorator.ts
- src/platform/experimental/http/actions/methods/delete.decorator.ts
- src/platform/experimental/http/actions/methods/get.decorator.ts
- src/platform/experimental/http/actions/methods/patch.decorator.ts
- src/platform/experimental/http/actions/methods/post.decorator.ts
- src/platform/experimental/http/actions/methods/put.decorator.ts
- src/platform/experimental/http/actions/params/abstract-param.decorator.ts
- src/platform/experimental/http/actions/params/body.decorator.ts
- src/platform/experimental/http/actions/params/param.decorator.ts
- src/platform/experimental/http/actions/params/query-params.decorator.ts
- src/platform/experimental/http/actions/params/response.decorator.ts
- src/platform/experimental/http/http.mixin.ts
- src/platform/experimental/http/index.ts
- src/platform/experimental/http/package.json
- src/platform/experimental/http/public-api.ts
- src/platform/experimental/package.json
- src/platform/experimental/public-api.ts
- src/test-bed/main/main.component.html
- src/test-bed/sandbox/http/http.component.html
- src/test-bed/sandbox/http/http.component.ts
- src/test-bed/sandbox/http/test-http.service.ts
- src/test-bed/test-bed.module.ts
- src/test-bed/test-bed.routes.ts
- tsconfig.json
Http Decorator Framework to simplify/hide the usage of `HttpClient` and make it easier to create http services.
Demo and Readme added to experimental.
> feat(http): add http decorators to experimental usage

- scripts/build-release
- src/platform/http-deprec/README.md
- src/platform/http-deprec/http-rest.service.spec.ts
- src/platform/http-deprec/http-rest.service.ts
- src/platform/http-deprec/http.module.ts
- src/platform/http-deprec/index.ts
- src/platform/http-deprec/interceptors/README.md
- src/platform/http-deprec/interceptors/http-interceptor-mapping.interface.ts
- src/platform/http-deprec/interceptors/http-interceptor-matcher.interface.ts
- src/platform/http-deprec/interceptors/http-interceptor.interface.ts
- src/platform/http-deprec/interceptors/http-interceptor.service.spec.ts
- src/platform/http-deprec/interceptors/http-interceptor.service.ts
- src/platform/http-deprec/interceptors/url-regexp-interceptor-matcher.class.spec.ts
- src/platform/http-deprec/interceptors/url-regexp-interceptor-matcher.class.ts
- src/platform/http-deprec/ng-package.js
- src/platform/http-deprec/package.json
- src/platform/http-deprec/public-api.ts
Since `@angular/http` has been deprecated for a long time.. we need to use `HttpClient` under the covers on our `http` package. Since most people wont be able to migrate in a single release, we are going to create an additional package called `http-deprec` with will have the "old" http module wrapping `@angular/http`.. and we will add a new `http` module that uses `HttpClient`.
- @covalent/http-deprec module for `@angular/http` compatibility.
> feat(http): create http-deprec package for `@angular/http` use

- src/app/components/components/chips/chips.component.html
- src/app/components/components/chips/chips.component.ts
- src/platform/core/chips/README.md
- src/platform/core/chips/chips.component.spec.ts
- src/platform/core/chips/chips.component.ts
- src/platform/core/common/behaviors/control-value-accesor.mixin.ts
Adds a `compareWith` input function to `<td-chips/>`
Fixes #1071
- Adds a `compareWith` input function
- Updates documentation 
- Adds a demo.
> feat(td-chips): Add compareWith input prop

- src/platform/http/http.module.ts
- src/platform/http/interceptors/http.service.ts
- src/platform/http/public-api.ts
Since the TdHttpService is extending HttpClient, there were AoT issues since @Injectable is added into HttpClient.
> fix(http): remove aot warning compilation

- src/app/components/components/data-table/data-table.component.html
- src/app/components/components/data-table/data-table.component.ts
- src/platform/core/data-table/data-table-column/data-table-column.component.html
Fixed the animation of atomic data table sorting icons by making the 'active' property optional.
This PR closes #532 
- Updated `th[td-data-table-column]` html
- Added new demo on Data Table docs
- Active prop is now optional. It is only used to make the highlight the columns, but the animation works without it
> fix(data-table): atomic sorting icon animation

- src/platform/flavored-markdown/flavored-markdown.component.ts
Flavored markdown should also support `-` and `*` as list item symbols.
> fix(flavored-markdown): Support '-' and '*' as list item symbols.

- src/platform/flavored-markdown/flavored-markdown.component.ts
Currently the `code-editor` docs page is broken (stuck in a loop, so careful navigating there). The issue is due to an improperly formatted table in https://github.com/Teradata/covalent-code-editor/blob/develop/docs/API.md 
Checks that the cell is valid so it does not break due to invalid tables.
Update the code-editor markdown
> fix(flavored-markdown): Prevent breakage from invalid table

- src/platform/http/actions/http.mixin.ts
- src/platform/http/http.module.ts
- src/polyfills.ts
Because of how DI works in JIT vs AOT, the `Injector` wasn't properly being injected into the decorators.
This will probably be fixed once the Ivy Renderer but for now we are gonna implement a small interim hack as a stop gap which is a small internal service that saves the injector in a static property for access.
> fix(http): fix aot issue for http decorators

- package.json
- yarn.lock
Bumps @covalent/code-editor to 2.0.3
Before
After
> chore(@covalent/code-editor): Bump to 2.0.3

- src/platform/core/json-formatter/json-formatter.component.html
- src/platform/core/json-formatter/json-formatter.component.scss
Top aligning key in json formatter if value is large.
Fix for https://github.com/Teradata/covalent/issues/1323
- One
- Two
- Three
> Bug Fix: JSON Formatter property name should not be centered when value is large

- src/platform/core/dialogs/dialogs.module.ts
- src/platform/core/dialogs/services/dialog.service.ts
Takes care of https://github.com/Teradata/covalent/issues/1327
Remove singleton creation for tdDialogService since we need to have access to the lowest provided matDialog instance.
> fix(dialog): make sure tdDialogService is not singleton (closes #1327)

- package-lock.json
- src/platform/core/breadcrumbs/_breadcrumbs-theme.scss
Updated styling for the last breadcrumb due to usability concerns. Made the last breadcrumb or active breadcrumb more prominent.
- Style update to `breadcrumbs-theme.scss`
> fix(usability-bug): style updates to the last breadcrumb

- src/platform/http/actions/http.mixin.spec.ts
- src/platform/http/actions/methods/abstract-method.decorator.ts
This PR makes sure we support appended parameters or multiple values for queryParams.
There is no way to test while serving the application, but added unit tests to validate.
closes https://github.com/Teradata/covalent/issues/1385
> fix(http): make appended/multiple value params work (closes #1385)

- angular.json
- package-lock.json
- package.json
Adding `monaco-editor` as a dependency and making sure we load that version instead of the one that comes bundled with the code-editor.
> docs(monaco): make sure we load installed version

- docs/CHANGELOG.md
- docs/GETTING_STARTED.md
- docs/UTILITY_MIXINS.md
- scripts/a11y/a11y.sh
- src/app/app.routes.ts
- src/app/components/toolbar/toolbar.component.html
- src/index.html
- src/platform/core/README.md
- src/platform/core/layout/README.md
- src/test-bed/test-bed.routes.ts
This PR merges into a feature branch: `feature/a11y-code-fixes`
Batch-0: Of code related a11y issue fixes reported by pa11y, Jenn is resolving the visual side of a11y/pa11y issues in a different feature branch.
Solution: use recommended PathLocationStrategy — the default "HTML5 pushState" style rather than HashLocationStrategy—the "hash URL" style in Angular routing strategy
> fix(): a11y code batch 0

- src/app/components/components/search/search.component.html
- src/app/components/components/search/search.component.ts
- src/platform/core/search/search-box/README.md
- src/platform/core/search/search-box/search-box.component.html
- src/platform/core/search/search-box/search-box.component.scss
- src/platform/core/search/search-box/search-box.component.ts
- src/platform/core/search/search-input/search-input.component.html
- src/platform/core/search/search-input/search-input.component.scss
Since now we expose appearance from `mat-form-field`.. we need to move the cancel button and tweak some styles depending on the appearance chosen to display a proper search layout.
> feat(search): tweak styles/layout on appearance

- src/platform/core/tab-select/tab-select.component.ts
I discussed this super briefly with @emoralesb05 over email today.
When a `td-tab-option` is added to a `td-tab-select` component, the new tabs are sometimes not rendered.
I don't think the error is on my side - I have reproduced it in a simple [repo on Stackblitz][stackblitz], that shows a very simple example of adding tabs programmatically can trigger this behavior. This example works well with `mat-tab-group` as well.
Unfortunately, I haven't found a good way to write a failing test for this bug since change detection works differently while testing. If you have an idea for a good test, please let me know and I'll add it!
My current understanding is that since the component is using `OnPush`, change detection doesn't work when changes happen inside the `ContentChildren` observable. …
> fix(tab-select): Mark for check when number of tabs change

- src/platform/markdown/markdown.component.spec.ts
- src/platform/markdown/markdown.component.ts
Handle non raw github image urls
```
[
{
"url": "https://raw.githubusercontent.com/Teradata/product-help/master/Unity/Overview/MarkdownCheatsheet.md"
}
]
```
> fix(td-help): handle non raw image urls

- src/app/components/style-guide/logo/logo.component.html
- src/platform/core/layout/README.md
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.html
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.scss
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.ts
I've added support for showing an avatar in the navigation drawer when there is no logo or icon. 
Please let me know if you'd like to see any changes in this PR, I would love to see this land in this amazing project!
- Adds a the option to show a user avatar in the navigation drawer.
- The avatar is shown when there is no logo or icon.
- Fixes #998.
- `npm run serve`
- Navigate to http://localhost:4200/#/style-guide
> Add user avatar to navigation drawer

- package-lock.json
- package.json
- Showdown was improperly converting some images into links. Upgraded Showdown.
> fix(markdown): fix github image rendering issues

- src/platform/markdown/markdown-utils.ts
- src/platform/markdown/markdown.component.spec.ts
- src/platform/markdown/markdown.component.ts
There was an issue with the original regex `\W` which did not work for Jap or other lang chars so used a more general regex.
> fix(td-markdown): fix anchor id creation

- src/platform/markdown/markdown.component.scss
- src/platform/markdown/markdown.component.ts
Fix for <td-markdown>'s possible SCSS bleeds to happen.
- Bugfix
> fix: td-markdown ng-deep

- src/platform/core/data-table/data-table.module.ts
- src/platform/core/data-table/services/data-table.service.ts
* Simplify how the singletone service is provided. Since v6 angular provides a new way of registering singleton services
by means of the provide in root module pattern.
> refactor(data-table): simplify service provider

- build.conf.js
- scripts/version-placeholders.js
- src/platform/code-editor/package.json
- src/platform/flavored-markdown/package.json
- src/platform/highlight/package.json
- src/platform/markdown/package.json
- src/platform/text-editor/package.json
Adds placeholders to a few packages to keep consitent versioning.
> build(version-placeholders): add placeholders for a few packages

- src/platform/core/schematics/ng-add/components.ts
- src/platform/core/schematics/ng-add/index.spec.ts
- src/platform/core/schematics/ng-add/index.ts
- src/platform/core/schematics/ng-add/schema.json
- src/platform/core/schematics/ng-add/schema.ts
Include `markdown-navigator` as part of ng add schematics. Takes care of #1493 
- Running ng add prompts user to setup markdown navigator
- If chosen yes, it adds `@covalent/markdown-navigator` as a dependency in package.json
> feat(schematics): include markdown navigator as part of ng-add

- package-lock.json
- package.json
Downgrade to Husky 2.7.0 so it does not depend on Git >= 2.13.2
> feat(husky): downgrade husky

- src/platform/core/package.json
Remove `schematics` as dependency from covalent/core. This causes issues on installation and its not needed since angular/cli already has this as a hard dependency.
> fix(build): remove schematics as dep from core

- src/platform/text-editor/text-editor.component.scss
- src/platform/text-editor/text-editor.component.ts
When using in ac, the style tag inserted into the dom was:
```html
<style>
SafeValue must use [property]=binding: [object Module] (see http://g.co/ng/security#xss)
</style>
```
Went with the route of just properly importing the css to fix the css issue. This also gets rid of a memory leak since the style tag was not being removed.
> fix(text-editor): import css properly

- src/app/components/components/functions/functions.component.html
Quick styling fix removing pad from buttons
- Removed all pad styling from buttons in functions demo HTML.
> feat(functions): removed button padding

- src/platform/core/nav-links/README.md
- src/platform/core/nav-links/index.ts
- src/platform/core/nav-links/nav-links.component.html
- src/platform/core/nav-links/nav-links.component.scss
- src/platform/core/nav-links/nav-links.component.spec.ts
- src/platform/core/nav-links/nav-links.component.ts
- src/platform/core/nav-links/nav-links.module.ts
- src/platform/core/nav-links/package.json
- src/platform/core/nav-links/public-api.ts
- src/test-bed/main/main.component.html
- src/test-bed/test-bed.module.ts
Add nav-links component as a styling ccomponent for navigational side sheets
- CovalentNavLinksModule
Missing in a separate PR: Docs and Demo
> feat(nav-links): add nav-links module

- src/app/content/components/component-demos/nav-steps/nav-steps.component.html
- src/app/content/components/component-demos/nav-steps/nav-steps.module.ts
- src/app/content/components/component-demos/notifications/notifications.component.html
- src/app/content/components/component-demos/notifications/notifications.module.ts
- src/app/content/components/component-demos/tab-select/tab-select.component.html
- src/app/content/components/component-demos/tab-select/tab-select.module.ts
- src/app/content/components/component-demos/text-editor/text-editor.component.html
- src/app/content/components/component-demos/text-editor/text-editor.module.ts
- src/app/content/components/components.routes.ts
- src/app/content/components/components.ts
Added components that started with n's and t's
- nav-steps
- notifications
- tab-select
- text-editor
- Visit the pages for the components above
> docs(): add components that start with n's and t's

- src/app/content/components/component-demos/file-input/file-input.component.html
- src/app/content/components/component-demos/file-input/file-input.module.ts
- src/app/content/components/component-demos/flavored-markdown/flavored-markdown.component.html
- src/app/content/components/component-demos/flavored-markdown/flavored-markdown.module.ts
- src/app/content/components/component-demos/search/search.component.html
- src/app/content/components/component-demos/search/search.module.ts
- src/app/content/components/component-demos/sidesheet/sidesheet.component.html
- src/app/content/components/component-demos/sidesheet/sidesheet.module.ts
- src/app/content/components/components.routes.ts
- src/app/content/components/components.ts
Added components that started with f's and s's
- file-input
- flavored-markdown
- search
- sidesheet
- Visit the pages for the components above
> docs(): add components that start with f's and s's

- src/platform/core/nav-links/nav-links.component.html
- src/platform/core/nav-links/nav-links.component.scss
- src/platform/core/nav-links/nav-links.component.spec.ts
- src/platform/core/nav-links/nav-links.component.ts
- src/platform/core/nav-links/nav-links.module.ts
- src/test-bed/main/main.component.html
Improve nav-links API to support more of a tree-like structure
- Improve API to support first level links rather than just nested.
- Make the collapsable groups visually more consistent and easier to use (no expansion panel).
- Make collapsable groups optional.
- Add launch icon depending if its opening a new tab or not
> feat(nav-links): improve API contract + tweaks

- src/polyfills.ts
- src/tests/utilities/covalent-tests.ts
- src/universal-app/combat-training/combat-training.ts
run on remaining files excluding platform. Works off of #1541
> Feat(tslint): run on remaining files excluding platform

- src/platform/code-editor/README.md
- src/platform/code-editor/code-editor.component.spec.ts
- src/platform/code-editor/code-editor.component.ts
- src/platform/text-editor/text-editor.component.spec.ts
Runs tslint on text and code editors. Works off off #1542 
- One
- Two
- Three
> feat(tslint): text and code editors

- build.conf.js
- package-lock.json
- package.json
- src/platform/code-editor/code-editor.component.spec.ts
- src/platform/code-editor/code-editor.component.ts
Remove styles appended to body on destroy.
> fix(code-editor): remove added styles on destroy

- src/platform/coding-standards/husky/README.md
> docs(coding-standards/husky): fix path in docs

- src/app/components/components/markdown-navigator/markdown-navigator.component.html
- src/platform/markdown-navigator/README.md
- src/platform/markdown-navigator/markdown-navigator-window-directive/markdown-navigator-window.directive.spec.ts
- src/platform/markdown-navigator/markdown-navigator-window-directive/markdown-navigator-window.directive.ts
- src/platform/markdown-navigator/markdown-navigator-window-service/markdown-navigator-window.service.ts
- src/platform/markdown-navigator/markdown-navigator.module.ts
- Adds MarkdownNavigatorWindowDirective to simplify usage.
- Audit issue is fixed in https://github.com/Teradata/covalent/pull/1557
- Figured creating a re-usable button was an overkill and wanted to keep it usage agnostic so did not want to default to an info or help icon.
- Addresses #1526
> feat(markdown-navigator): add MarkdownNavigatorWindowDirective

- .travis.yml
- package-lock.json
- src/app/components/components/markdown-navigator/markdown-navigator.component.html
- src/app/components/components/markdown-navigator/markdown-navigator.component.ts
- src/platform/markdown-navigator/README.md
- src/platform/markdown-navigator/markdown-navigator-window-service/markdown-navigator-window.service.spec.ts
- src/platform/markdown-navigator/markdown-navigator-window-service/markdown-navigator-window.service.ts
- Allows only one window open at a time
- exposes a `close()` method
- exposes a `isOpen` getter
- Updates material and cdk to get latest drag drop fixes.
- Updates doc
- Adds a test
- do not run commitlint on travis on develop, only on PRs
- Closes #1533
- Navigate to http://localhost:4200/#/components/markdown-navigator
- Click on the `Open Draggable Markdown Navigator Window` button multiple times and make sure only one is open
> feat(markdown-navigator): only open one window at a time

- src/platform/echarts/tooltip/series-tooltip.component.ts
- src/platform/echarts/tooltip/tooltip.component.ts
Templates for tooltips werent being picked up properly.
> fix(): make sure we grab tooltip templates

- src/platform/markdown/markdown-utils/markdown-utils.spec.ts
- src/platform/markdown/markdown-utils/markdown-utils.ts
- src/platform/markdown/markdown.component.spec.ts
- src/platform/markdown/markdown.component.ts
- gh svg links need to end with `sanitize=true` to get image vs text.
> feat(markdown): fix gh svg links

- src/app/components/components/markdown-navigator/markdown-navigator.component.html
- src/app/components/components/markdown-navigator/markdown-navigator.component.scss
- src/app/components/components/markdown-navigator/markdown-navigator.component.ts
- src/platform/flavored-markdown/flavored-markdown-loader/flavored-markdown-loader.component.ts
- src/platform/markdown-navigator/README.md
- src/platform/markdown-navigator/markdown-navigator-window-directive/markdown-navigator-window.directive.spec.ts
- src/platform/markdown-navigator/markdown-navigator-window-service/markdown-navigator-window.service.spec.ts
- src/platform/markdown-navigator/markdown-navigator-window-service/markdown-navigator-window.service.ts
- src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.html
- src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.spec.ts
- src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.ts
- src/platform/markdown-navigator/markdown-navigator.component.html
- src/platform/markdown-navigator/markdown-navigator.component.spec.ts
- src/platform/markdown-navigator/markdown-navigator.component.ts
- Make markdown-navigator related components on push 
- Add tree validation tests
- Add `startAt` input 
- Add compareWith input
- Add more tests
> test(markdown-nav): add ability to jump to a point in tree

- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-basic/markdown-navigator-demo-basic.component.ts
- src/app/content/components/component-demos/markdown-navigator/markdown-navigator.component.ts
- src/platform/core/common/common.module.ts
- src/platform/core/common/services/icon.service.ts
- src/platform/core/common/services/router-path.service.ts
- src/platform/core/data-table/data-table.module.ts
- src/platform/core/data-table/services/data-table.service.ts
- src/platform/core/dialogs/dialogs.module.ts
- src/platform/core/dialogs/services/dialog.service.ts
- src/platform/core/file/file.module.ts
- src/platform/core/file/services/file.service.ts
- src/platform/core/media/media.module.ts
- src/platform/core/media/services/media.service.ts
- src/platform/dynamic-forms/dynamic-forms.module.ts
- src/platform/dynamic-forms/services/dynamic-forms.service.ts
- src/platform/flavored-markdown/flavored-markdown-loader/flavored-markdown-loader.component.ts
- src/platform/markdown-navigator/README.md
- src/platform/markdown-navigator/markdown-navigator-window-directive/markdown-navigator-window.directive.spec.ts
- src/platform/markdown-navigator/markdown-navigator-window-directive/markdown-navigator-window.directive.ts
- src/platform/markdown-navigator/markdown-navigator-window-service/markdown-navigator-window.service.spec.ts
- src/platform/markdown-navigator/markdown-navigator-window-service/markdown-navigator-window.service.ts
- src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.spec.ts
- src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.ts
- src/platform/markdown-navigator/markdown-navigator.component.spec.ts
- src/platform/markdown-navigator/markdown-navigator.component.ts
- src/platform/markdown-navigator/markdown-navigator.module.ts
- src/platform/markdown/markdown-loader/markdown-loader.service.spec.ts
- src/platform/markdown/markdown-loader/markdown-loader.service.ts
- src/platform/markdown/markdown.module.ts
Backwards compatibility with angular 8.
For some reason, the compiler doesnt recognize `providedIn` syntax if the project was built using angular 9 and used in an angular 8 project.
> fix(): revert service providers to support ng 8

- src/platform/http/actions/README.md
- src/platform/http/actions/class/http.decorator.ts
Deprecate `TdHttp` and `TdClientHttp` decorators in favor of mixin extends.
> fix(http): *DEPRECATE* http class decorators

- src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.scss
get rid of markdown-nav-window extra scrollbar
Before
After
> fix(): get rid of markdown-nav-window extra scrollbar

- src/platform/core/dialogs/resizable-draggable-dialog/resizable-draggable-dialog.ts
Remove internal rxjs import.
Addresses rxjs import issue in https://github.com/Teradata/covalent/issues/1402#issuecomment-573593269
- Run `npm run serve`
- Navigate to http://localhost:4200/#/components/markdown-navigator/overview
- View markdown navigator window demo and ensure it is still resizable.
> fix(resizable-dialog): remove internal rxjs import

- src/platform/code-editor/README.md
- src/platform/code-editor/code-editor.component.spec.ts
- src/platform/code-editor/code-editor.component.ts
Removed autoLayout input from code editor. Addresses issue https://github.com/Teradata/covalent/issues/1516
- Global find/remove of autoLayout
> feat(deprecate-code-editor-autolayout): removed autoLayout input

- src/app/components/shared/demo-tools/demo.component.scss
- src/app/content/components/component-demos/loading/demos/loading-demo-fullscreen/loading-demo-fullscreen.component.html
- src/app/content/components/component-demos/loading/demos/loading-demo-fullscreen/loading-demo-fullscreen.component.scss
- src/app/content/components/component-demos/loading/demos/loading-demo-fullscreen/loading-demo-fullscreen.component.ts
- src/app/content/components/component-demos/loading/demos/loading-demo.component.html
- src/app/content/components/component-demos/loading/demos/loading-demo.module.ts
Add a fullscreen loading demo
Addresses https://github.com/Teradata/covalent/issues/1583
> feat(loading): add a fullscreen loading demo

- src/app/content/components/component-demos/message/demos/message-demo-basic/message-demo-basic.component.html
- src/app/content/components/component-demos/message/demos/message-demo-basic/message-demo-basic.component.ts
- src/app/content/components/component-demos/message/demos/message-demo.module.ts
- src/app/content/components/component-demos/message/message.module.ts
Bring all the demos for `messages & alerts` from old docs
- demos showing all sorts of messages & alerts
> feat(messages-docs): add more demos to messages, remove unused code

- src/platform/core/file/file-upload/README.md
- src/platform/core/file/services/file.service.spec.ts
- src/platform/core/file/services/file.service.ts
- Fully deprecate upload method
> feat(file-service): deprecate upload method

- src/app/content/components/component-demos/loading/demos/loading-demo-basic/loading-demo-basic.component.ts
- src/app/content/components/component-demos/loading/demos/loading-demo-observable/loading-demo-observable.component.html
- src/app/content/components/component-demos/loading/demos/loading-demo-observable/loading-demo-observable.component.ts
- src/app/content/components/component-demos/loading/demos/loading-demo-replace/loading-demo-replace.component.html
- src/app/content/components/component-demos/loading/demos/loading-demo-replace/loading-demo-replace.component.ts
- src/app/content/components/component-demos/loading/demos/loading-demo.component.html
- src/app/content/components/component-demos/loading/demos/loading-demo.module.ts
- src/platform/core/loading/directives/loading.directive.spec.ts
- src/platform/core/loading/loading.component.html
- src/platform/core/loading/loading.component.ts
- src/platform/core/loading/services/loading.factory.ts
There is an issue with angulars callback animations that introduced in angular@9 when an element that has an animation callback gets removed from the DOM and then added back, the callback stops getting triggered. This made it so that the loading element was not removed from its target after a second insertion.
For this, we decided to remove the animation delay and just remove the loader as soon as the `resolve/removal` action gets triggered. We were already thinking of doing this in the past, so this just gave us yet another reason to do this.
Also included 2 loading demos for replace and observable usage with it.
Note: A unit test was changed since it didnt make sense as it was done in the past.. and it was repurposed for a different case.
> fix(loading): remove delay on DOM insert/removal

- src/platform/core/layout/_layout-theme.scss
- src/platform/core/layout/layout-card-over/layout-card-over.component.html
- src/platform/core/layout/layout-nav-list/layout-nav-list.component.html
- src/platform/core/layout/layout-nav/layout-nav.component.html
Add dense as an attribute selector so layouts can make their toolbars 48px instead of 64px.
If material ever decides to add a dense option for toolbars, we will just leverage it under the covers.
- `dense` attribute for layouts or added to body
> feat(layout): add dense mode

- src/app/content/components/component-demos/loading/demos/loading-demo-icon/loading-demo-icon.component.html
- src/app/content/components/component-demos/loading/demos/loading-demo-icon/loading-demo-icon.component.ts
- src/app/content/components/component-demos/loading/demos/loading-demo.component.html
- src/app/content/components/component-demos/loading/demos/loading-demo.module.ts
Added loading icon demo - covalent#1627
- loading-demo-icon component
- updates to loading demo layout html
> fix(demo): added loading icon demo

- src/platform/core/common/styles/core/_toolbar.scss
Add dense as an attribute selector so toolbars are 48px instead of 64px.
- `dense` attribute for toolbars or added to body
> feat(toolbar): add dense mode

- src/platform/http/actions/http.mixin.spec.ts
- src/platform/http/actions/methods/abstract-method.decorator.ts
Ran into an issue where I had to use a custom encoder, which were being ignored. So with this change, if params are already http params, use that as a base to retain encoder and other options.
> fix(http): dont override httpParams object

- src/app/components/content-container/content-container.component.html
Fix fullscreen mode for Text editor demo
- changed z-index of sidedraw to 1.
> text editor - fix(sidedraw): change z-index on mat-sidedraw to 1

- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-basic/markdown-navigator-demo-basic.component.ts
- src/platform/markdown-navigator/README.md
- src/platform/markdown-navigator/markdown-navigator.component.html
- src/platform/markdown-navigator/markdown-navigator.component.spec.ts
- src/platform/markdown-navigator/markdown-navigator.component.ts
Adds ability to add icons and descriptions to markdown nav items
> feat(markdown-nav): support descriptions and icons

- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-basic/markdown-navigator-demo-basic.component.ts
- src/platform/markdown-navigator/markdown-navigator.component.html
- src/platform/markdown-navigator/markdown-navigator.component.scss
- src/platform/markdown-navigator/markdown-navigator.component.spec.ts
- src/platform/markdown-navigator/markdown-navigator.component.ts
Render md and list at same level.
> feat:(markdown-nav): render md and list side by side

- src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-buttons/flavored-markdown-demo-buttons.component.html
- src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-buttons/flavored-markdown-demo-buttons.component.ts
- src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo.component.html
- src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo.module.ts
- src/platform/flavored-markdown/flavored-markdown.component.ts
- src/platform/flavored-markdown/flavored-markdown.module.ts
- src/platform/flavored-markdown/flavored-markdown.spec.ts
- Converts links with special syntax into mat-raised-buttons
```
[This is a button](#data=whateverdatayouwant
[This is a button](#data=step_1)
[This is a button](#data={"planet": "Jupiter"})
```
- Added a demo
- Added some tests
- Add documentation
> feat(flavored-markdown): render links  with special syntax as buttons

- src/platform/markdown-navigator/markdown-navigator.component.spec.ts
- src/platform/markdown-navigator/markdown-navigator.component.ts
- Fixes go back regression introduced in #1689
> fix(markdown-nav): fix go back

- src/app/content/components/component-demos/flavored-markdown/demos/flavored-markdown-demo-buttons/flavored-markdown-demo-buttons.component.ts
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-events/markdown-navigator-demo-events.component.html
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-events/markdown-navigator-demo-events.component.ts
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo.component.html
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo.module.ts
- src/platform/flavored-markdown/README.md
- src/platform/flavored-markdown/flavored-markdown-loader/flavored-markdown-loader.component.html
- src/platform/flavored-markdown/flavored-markdown-loader/flavored-markdown-loader.component.ts
- src/platform/markdown-navigator/README.md
- src/platform/markdown-navigator/markdown-navigator-window-service/markdown-navigator-window.service.spec.ts
- src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.html
- src/platform/markdown-navigator/markdown-navigator-window/markdown-navigator-window.component.ts
- src/platform/markdown-navigator/markdown-navigator.component.html
- src/platform/markdown-navigator/markdown-navigator.component.ts
- Exposes button click events
- Adds a test
- View events demo on http://localhost:4200/#/components/markdown-navigator/examples
> feat(markdown-nav): expose button click events

- src/platform/http/interceptors/url-regexp-interceptor-matcher.class.ts
In order to properly handle special characters in the URL before the params section for interceptors.
- regex now properly handles *any* special characters before the ? params section
- fixing regex structure
> fix(): updating path intercepting regex

- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-children-url/markdown-navigator-demo-children-url.component.html
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-children-url/markdown-navigator-demo-children-url.component.ts
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo.component.html
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo.module.ts
- src/assets/demos-data/children_url.json
- src/platform/markdown-navigator/README.md
- src/platform/markdown-navigator/markdown-navigator.component.html
- src/platform/markdown-navigator/markdown-navigator.component.spec.ts
- src/platform/markdown-navigator/markdown-navigator.component.ts
- src/platform/markdown-navigator/markdown-navigator.module.ts
Adds childrenUrl property to IMarkdownNavigatorItem to enable fetching a remote list of children.
Addresses #1721
> feat(markdown-nav): add children url property

- src/platform/core/dialogs/resizable-draggable-dialog/resizable-draggable-dialog.ts
User should not be able select the dialog content while resizing or for draggable dialogs.
- user selection is disabled while dialog resizing.
- user selection is disabled for draggable dialogs.
> fix(dialogs): disable user selection for draggable dialogs

- src/platform/core/json-formatter/json-formatter.component.ts
Helping the child parser not do double the work.
Part of an investigation to the formatter not being able to handle large files
- Improved parseChildren function
> fix(): update json-formatter.component.ts

- package.json
Somehow the change to publish to nightly got lost in https://github.com/Teradata/covalent/pull/1741
> feat(guided-tour): push to nightly

- src/platform/core/user-profile/user-profile-menu/user-profile-menu.component.scss
Scoping margin on mat-divider to component so it doesn't propagate
- Scoping margin on mat-divider to component and updating comment
> fix: quick fix on mat-divider margin

- src/platform/core/dialogs/README.md
- src/platform/core/dialogs/confirm-dialog/confirm-dialog.component.html
- src/platform/core/dialogs/confirm-dialog/confirm-dialog.component.ts
- src/platform/core/dialogs/services/dialog.service.ts
Enable usage of the confirm dialog with a `color="warn"` button
Resolves #1778 
- Add `isDestructive` parameter to `TdConfirmDialogComponent` and `IConfirmConfig` interface. Defaults to `false`.
> feat(dialogs): add isDestructive parameter to confirm dialog

- src/platform/core/common/styles/core/_sidenav.scss
-hard coded colors are causing side effects
- removal of hard coded colors inside sidenav scss
> fix: hardcoded sidenav color

- src/app/content/components/component-demos/dynamic-forms/demos/dynamic-forms-demo-custom-elements/dynamic-forms-demo-custom-elements.component.ts
- src/platform/dynamic-forms/README.md
- src/platform/dynamic-forms/dynamic-element.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.html
- src/platform/dynamic-forms/dynamic-forms.component.spec.ts
- src/platform/dynamic-forms/services/dynamic-forms.service.ts
Addresses https://github.com/Teradata/covalent/issues/1397. 
Expose a mechanism for passing through property values to custom components used within dynamic forms.
- Extended config object to support object of custom property/value pairs that are set in the custom component on initialization.
> feat(dynamic-forms-custom-config): custom component values

- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-anchor/markdown-navigator-demo-anchor.component.html
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-anchor/markdown-navigator-demo-anchor.component.ts
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-start-at-onclick-children-url/markdown-navigator-demo-start-at-onclick-children-url.component.html
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-start-at-onclick-children-url/markdown-navigator-demo-start-at-onclick-children-url.component.ts
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo.component.html
- src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo.module.ts
- src/assets/demos-data/children_url_3.json
- src/platform/markdown-navigator/markdown-navigator.component.ts
Add a startAt option for children url, so that we can jumpTo any link if childrenUrl contains multiple urls
- Add a startAt option for children url
> fix(markdown): add startAt option for children url

- src/platform/highlight/_highlight-theme.scss
- src/platform/highlight/highlight.component.scss
Moved display rule from `_highlight-theme.scss` to `highlight.component.scss`
Fixes #1803
> fix(highlight): move highlight display rule out of theme file

- src/platform/guided-tour/guided.tour.ts
This fixes the `allowGoBack` option not working as expected for a guided tour step. Setting it false now disables / hides the button.
**ALTERNATE APPROACH:** https://github.com/9inpachi/covalent/commit/5ebdaebf668ba1b6a2a1925f900a006737e82504 (removing the back button)
- `allowGoBack` option working as expected
- Closes #1800 
For [STEP 3](https://github.com/Teradata/covalent/blob/develop/src/app/content/components/component-demos/guided-tour/demos/guided-tour-demo-go-back-navigation/guided-tour-demo-go-back-navigation.component.ts#L41-L48) in demo where the `allowGoBack` is set to false.
**Before**
**After**
> fix(guided-tour): allowGoBack not working

- src/platform/core/dynamic-menu/dynamic-menu-item/dynamic-menu-item.component.html
- src/platform/core/dynamic-menu/dynamic-menu-item/dynamic-menu-item.component.scss
covalent#1797  - Dynamic menu sub menu stays open
- Fix the issue where dynamic menu's sub menu remains open, if we hover on to other menu option
> fix(menu): fix dynamic menu hover

- src/app/components/shared/demo-tools/demo.component.html
- src/app/content/components/component-demos/code-editor/demos/code-editor-demo-basic/code-editor-demo-basic.component.html
- src/app/content/docs/build-tasks/build-tasks.component.html
- src/app/content/docs/creating/creating.component.html
- src/app/content/docs/deployment/deployment.component.html
- src/app/content/docs/icons/icons.component.html
- src/app/content/docs/mock-data/mock-data.component.html
- src/app/content/docs/testing/testing.component.html
- src/app/content/docs/theme/theme.component.html
- src/app/content/layouts/card-over/card-over.component.html
- src/app/content/layouts/manage-list/manage-list.component.html
- src/app/content/layouts/nav-list/nav-list.component.html
- src/app/content/layouts/nav-view/nav-view.component.html
- src/app/content/layouts/overview/overview.component.html
- src/app/content/utilities/utilities-demos/animations/animations.component.html
- src/app/content/utilities/utilities-demos/directives/directives.component.html
- src/app/content/utilities/utilities-demos/functions/functions.component.html
- src/app/content/utilities/utilities-demos/media/directive/media.component.html
- src/app/content/utilities/utilities-demos/media/service/media.component.html
- src/app/content/utilities/utilities-demos/pipes/pipes.component.html
- src/app/content/utilities/utilities-demos/utility-styles/utility-styles.component.html
- src/platform/flavored-markdown/flavored-markdown.component.ts
- src/platform/highlight/README.md
- src/platform/highlight/highlight.component.spec.ts
Fix all references of lang attribute in highlight component to codeLang
> fix(highlight): fix all references of lang to codeLang

- src/platform/core/dynamic-menu/dynamic-menu-item/dynamic-menu-item.component.html
- src/platform/core/dynamic-menu/dynamic-menu-item/dynamic-menu-item.component.scss
Use the already existing utility styles class `pad-none` for no padding instead of creating a custom class.
- Using utility class for no padding
None.
> fix(menu): Use default utility class for no padding

- src/app/content/components/component-demos/message/demos/message-demo.component.html
Fixed displaying .ts and .html file in demo examples of messages component.
- Closes https://github.com/Teradata/covalent/issues/1783
Before
After
> fix(message): fixed displaying file in demo for messages

- docs/UTILITY_MIXINS.md
- src/platform/core/common/styles/font/_font.scss
- src/platform/core/schematics/ng-add/files/theme.scss
- src/theme.scss
Covalent includes the Material icons as a woff2 file. There are two approaches for including these icons into a project which depends on Covalent. First, import the material-icons.css that is constructed by the builder. This has a qualified relative path to the woff2 file. Second, import the covalent-material-icons mixin. The location of the woff2 file is relative to the scss file defining the mixin. To support both cases, the $mat-font-url variable must be utilized. This PR restores the use of the variable and updates the markdown indicating how to import the mixin.
- Restored usage of $mat-font-url and updated documentation on usage of mixin import
```css
// Include pre-bundled material-icons
$mat-font-url: './';
@include covalent-material-icons();
// Alternative way to include …
```
> fix(material-icons-mixin): restored relative path mechanism

- package.json
- src/app/content/components/component-demos/markdown/demos/markdown-demo-youtube/markdown-demo-youtube.component.html
- src/app/content/components/component-demos/markdown/demos/markdown-demo-youtube/markdown-demo-youtube.component.ts
- src/app/content/components/component-demos/markdown/demos/markdown-demo.component.html
- src/app/content/components/component-demos/markdown/demos/markdown-demo.module.ts
- src/platform/core/data-table/data-table.component.ts
- src/platform/core/expansion-panel/expansion-panel-group.component.ts
- src/platform/core/layout/navigation-drawer/navigation-drawer.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.ts
- src/platform/echarts/tooltip/series-tooltip.component.ts
- src/platform/echarts/tooltip/tooltip.component.ts
- src/platform/flavored-markdown/flavored-markdown.component.ts
- src/platform/flavored-markdown/flavored-markdown.spec.ts
- src/platform/markdown/markdown-utils/markdown-utils.ts
- src/platform/markdown/markdown.component.ts
Page help desperately wants for video capability, so now we can add YouTube embedded videos natively like so:
```![youtu.be/videoID]```
- Native iframe embeds added for youtube share links
- Ability to embed playlists as well as single videos
> VAC-442 youtube markdown embeds

- README.md
- build.conf.js
upgrading the build support matrix for angular and angular material
- update to build script to include support for ng11
- README update
> chore(): upgrade angular support matrix

- src/platform/markdown-navigator/markdown-navigator.component.html
Moved the url rendering to top and children to bottom in markdown window navigator
Before
After
> fix: fixed moving child list to bottom on markdown-navigator(VAC-649)

- src/app/content/components/component-demos/dynamic-forms/demos/dynamic-forms-demo-text/dynamic-forms-demo-text.component.ts
- src/app/content/components/component-demos/dynamic-forms/dynamic-forms.component.ts
- src/platform/dynamic-forms/dynamic-element.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.ts
- src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.html
- src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.ts
- src/platform/dynamic-forms/dynamic-forms.component.html
- src/platform/dynamic-forms/dynamic-forms.component.spec.ts
- src/platform/dynamic-forms/services/dynamic-forms.service.ts
To differentiate between the label and the placeholder for
dynamic-forms, a dedicated placeholder property was added.
This change does not change the appearance of the form fields, as
material treated the placeholder mostly the same as the mat-label
if no mat-label is provided.
Closes #1820
- Label is set as `mat-label`
- Placeholder can be set for form field types
-- `TdDynamicElement.Input` (including `TdDynamicType.Text`, `TdDynamicType.Number` and `TdDynamicElement.Password`)
-- `TdDynamicElement.Textarea`
-- `TdDynamicElement.Select` (including `TdDynamicType.Array`)
-- `TdDynamicElement.FileInput`
-- `TdDynamicElement.Datepicker` (including `TdDynamicType.Date`)
- Additionally when the material form field appearance is set, the label does not vanish anymore on focus.
Without setting …
> fix(dynamic-forms): show label as mat-label instead of placeholder

- src/platform/core/dialogs/_dialog-theme.scss
- src/platform/core/dialogs/window-dialog/window-dialog.component.scss
Small fix for the Help Dialog header of the markdown navigator component 
- CSS adjustment to dialog headers in the Core module
> fix(dialogs): theming adjustment for dialog header

- src/platform/guided-tour/guided.tour.ts
Fixes an error in our logic for setting default buttons on guided tour steps. While the existing condition worked if `step.buttons` was defined as an empty array, if it was not defined, the `length` check would blow up and the tour wouldn't start.
- Aforementioned logic fix
> fix(guided-tour): step button override error

- src/app/content/components/component-demos/side-sheet/demos/side-sheet-demo-advanced/side-sheet-demo-advanced.component.ts
- src/app/content/components/component-demos/side-sheet/demos/side-sheet-demo-basic/side-sheet-demo-basic.component.ts
- src/app/content/components/component-demos/side-sheet/demos/side-sheet-demo-multi/side-sheet-demo-multi.component.html
- src/app/content/components/component-demos/side-sheet/demos/side-sheet-demo-multi/side-sheet-demo-multi.component.ts
- src/app/content/components/component-demos/side-sheet/demos/sidesheet-demo.component.html
- src/app/content/components/component-demos/side-sheet/demos/sidesheet-demo.module.ts
- src/platform/core/side-sheet/side-sheet-container.ts
- src/platform/core/side-sheet/side-sheet-ref.ts
- src/platform/core/side-sheet/side-sheet.ts
Adding animation to side sheet component when there is already a previous side sheet open.
- animation to show layered child sidesheet on top of a currently open one
- multi side sheet example for docs site
> feat(side-sheet): adding multi layered ability

- .github/workflows/codeql-analysis.yml
- src/platform/markdown/markdown.component.spec.ts
- src/platform/markdown/markdown.component.ts
> perf(markdown): do not run change detection when the markdown is clicked

- apps/docs-app/project.json
- libs/angular-highlight/src/lib/highlight.component.ts
- libs/markdown/src/lib/markdown.component.ts
- package-lock.json
- package.json
using ES6 style imports for highlight.js and markdown libraries
- using ES6 style module imports over the node based require
- allows for better module tree shaking
> fix(imports): remove require imports from highlight and markdown

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .releaserc
upgrading github actions to use latest node
- release action upgraded to node 16
- ci action upgraded to node 16
> build(actions): node 16

- apps/docs-app/src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-editor/markdown-navigator-demo-editor.component.html
- apps/docs-app/src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-editor/markdown-navigator-demo-editor.component.ts
- apps/docs-app/src/styles.scss
- apps/docs-app/tsconfig.editor.json
- apps/docs-app/tsconfig.json
- libs/angular-code-editor/src/lib/code-editor.component.ts
- libs/angular/breadcrumbs/src/breadcrumb/breadcrumb.component.html
- libs/angular/breadcrumbs/src/breadcrumbs.component.scss
- libs/angular/breadcrumbs/src/breadcrumbs.component.ts
- libs/markdown-flavored/src/lib/flavored-markdown.component.scss
- libs/markdown-flavored/src/lib/flavored-markdown.component.ts
- libs/markdown-navigator/_markdon-navigator-theme.scss
- libs/markdown-navigator/ng-package.json
- libs/markdown-navigator/src/markdown-navigator.component.html
- libs/markdown-navigator/src/markdown-navigator.component.scss
- libs/markdown-navigator/src/markdown-navigator.component.spec.ts
- libs/markdown-navigator/src/markdown-navigator.component.ts
- libs/markdown-navigator/src/markdown-navigator.module.ts
- libs/markdown/src/lib/markdown.component.ts
Adding TD breadcrumbs to markdown navigator window
- adding breadcrumbs to navigator window per UX mocks
- Fixed live editor demo for markdown navigator window
> feat(markdown-navigator): adding breadcrumbs

- libs/angular-text-editor/src/lib/text-editor.component.ts
> fix(text-editor): remove the `change` event listener when the component is destroyed

- libs/markdown-navigator/src/markdown-navigator.component.html
- Add button click event to flavored markdown loader
> fix(markdown-navigator): add button click to flavored markdown loader

- apps/docs-app/src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-children-url-start-at/markdown-navigator-demo-children-url-start-at.component.ts
- apps/docs-app/src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-children-url/markdown-navigator-demo-children-url.component.ts
- apps/docs-app/src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-service/markdown-navigator-demo-service.component.ts
fix  markdown docs asset path for demo
> docs(gh-pages): fix static asset path

- libs/markdown/src/lib/markdown.component.spec.ts
- libs/markdown/src/lib/markdown.component.ts
> perf(markdown): do not run change detection when DOM timer is fired and scrolled to an anchor

- libs/angular-dynamic-forms/src/lib/dynamic-elements/dynamic-file-input/dynamic-file-input.component.html
- libs/angular-dynamic-forms/src/lib/dynamic-elements/dynamic-textarea/dynamic-textarea.component.html
Changing name attribute for material inputs based on recent NG 13 updates
- Updates text area and file input component to use new syntax for `name` attributes for material inputs
> fix(dynamic-forms): fix name attribute for other inputs

- apps/docs-app/src/app/content/components/component-demos/search/demos/search-demo-input/search-demo-input.component.html
- apps/docs-app/src/app/content/components/component-demos/search/demos/search-demo-input/search-demo-input.component.ts
- libs/angular/search/src/search-input/search-input.component.ts
re-implementing the search input to use mixinControlValueAccessor from our common package
closes #1932 
- re-implements mixinControlValueAccessor
> fix(search): re-implementing mixinControlValueAccessor

- apps/docs-app/project.json
- docs/CHANGELOG.md
- libs/angular-text-editor/src/lib/text-editor.component.ts
- package-lock.json
- package.json
After using `@covalent/text-editor` it was discovered that EasyMDE library was not being correctly imported in a 12.x/13.x project.
closes #1940 
- Moving away from module import over to a commonjs style include
NOTE: Consumers must now import EasyMDE within their projects. this will no longer be included directly in the component.
> fix(text-editor): commonjs dependencies

- libs/markdown-flavored/src/lib/flavored-markdown.component.ts
Change the navigator button regex
- Navigator button regex only detect first pair of parentheses
> fix(navigator): fix button regex

- libs/markdown-flavored/src/lib/flavored-markdown.component.ts
- libs/markdown/src/lib/markdown.component.ts
Adjusted the regex for parsing lists in the flavored markdown component
- flavored markdown parsing for lists now include `+,*` where before it was just `+`
> fix(flavored-markdown): allow for all list characters

- package.json
Changed versioning of rxjs in package.json from `~7.4.0` to `^7.4.0`
> fix(rxjs): in package from ~ to ^

- .eslintrc.json
- apps/docs-app/src/app/components/home/home.component.ts
- apps/docs-app/src/app/components/shared/component-overview/component-overview.component.ts
- apps/docs-app/src/app/components/shared/demo-tools/demo.component.ts
- apps/docs-app/src/app/components/shared/sidenav-content/component-overview.component.ts
- apps/docs-app/src/app/content/components/component-demos/dialogs/demos/dialogs-demo-draggable-resizable-window/dialogs-demo-draggable-resizable-window.component.ts
- apps/docs-app/src/app/content/components/component-demos/dialogs/demos/dialogs-demo-draggable-resizable/dialogs-demo-draggable-resizable.component.ts
- apps/docs-app/src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-service-button-clicked/markdown-navigator-demo-service-button-clicked.component.ts
- apps/docs-app/src/app/content/utilities/content-details/content-api/content-api.component.ts
- apps/docs-app/src/app/content/utilities/content-details/content-details.component.ts
- apps/docs-app/src/app/content/utilities/content-details/content-overview/content-overview.component.ts
- libs/angular-guided-tour/src/lib/guided.tour.ts
- libs/angular/breadcrumbs/src/breadcrumbs.component.ts
- libs/angular/layout/src/navigation-drawer/navigation-drawer.component.ts
- package-lock.json
- package.json
There're no functional changes in this PR. It only setups RxJS plugins to ensure that existing/subsequent observables are unsubscribed by developers. I've also replaced `subscription = obs.subscribe` with `obs.pipe(takeUntil()).subscribe` in some places to be consistent with the other code.
> ci: setup ESLint RxJS plugins

- libs/angular/file/src/directives/file-drop.directive.spec.ts
- libs/angular/file/src/directives/file-drop.directive.ts
Note: existing tests have not been touched, I just removed unnecessary `waitForAsync + inject + whenStable` since they create a code nesting, but actually there's nothing asynchronous in these tests, because all tests are synchronous. Added a new test `should not run change detection on dragover event` that verifies the current change.
> perf(file): do not run change detection on `dragover` event

- libs/angular-code-editor/src/lib/code-editor.component.ts
removing gray border inserted in every monaco editor instance
> fix(editor): remove grey border

- stories/info-and-help.stories.mdx
Added the info and help guide from [Figma](https://www.figma.com/file/CQlXKYDbZ34DeSUqS7LoVv/Guide---Info-%26-help?node-id=137%3A275). 
- New info and help story added under "Guides". 
- `covalent-sigma/stories/info-and-help.stories.mdx` was added.
> feat: add info and help guide

- apps/docs-app/src/app/content/components/component-demos/side-sheet/demos/side-sheet-demo-multi/side-sheet-demo-multi.component.ts
- libs/angular/side-sheet/src/side-sheet.config.ts
- libs/angular/side-sheet/src/side-sheet.ts
When secondary side sheet is opened, provide 3 options to user:
1. 'pushed'. --  push the parent side sheet to entire width of the window
2. 'shifted' -- shift the parent side sheet to left 
3. 'none' --  secondary sheet simply cover the parent
Secondary side sheet change
> fix(nx): side sheet behavior change

- libs/components/src/card/card.scss
- libs/components/styles/theme/_all-theme.scss
- libs/components/styles/theme/theme.scss
- libs/tokens/build/css/variables.css
- libs/tokens/build/js/variables.d.ts
- libs/tokens/build/js/variables.js
- libs/tokens/build/json/variables.json
- libs/tokens/build/scss/_variables.scss
- libs/tokens/src/color/base.json
- libs/tokens/src/color/palettes/surface.json
- stories/color-use.stories.mdx
Implemented [this Figma documentation](https://www.figma.com/file/7pzxuLUaKxE4A4uIPB8YUd/Color-use?node-id=337%3A2188) into Storybook.
* --mdc-theme-surface-emphasis, --mdc-theme-surface-emphasis-highlight, and --mdc-theme-surface-emphasis-highlight-hover have been added.
* --mdc-theme-surface-accent, --mdc-theme-surface-accent-highlight, and --mdc-theme-surface-accent-highlight-hover have also been added but they are just aliases for --mdc-theme-surface-primary, --mdc-theme-surface-primary-highlight, and --mdc-theme-surface-primary-highlight-hover.
* Some color values and opacities on the guide were changed to match what the variables actually are.
* App bar background color was removed.
* Card background color was updated to surface.
Receiving this error when I run any of these …
> feat: add color use guide to covalent

- .github/workflows/chromatic.yml
- .gitignore
- libs/components/package.json
- libs/components/project.json
- libs/components/webpack.config.js
Fixing the build stage for the components library
- @covalent/components will now build with the rest of the libraries to also be published
- fixing the chromatic workflow to only run when certain libs change (components, tokens, icons)
- also using npx cli command for chromatic instead of action since its not verified by github marketplace
> fix(componets): deploy to npm & chromatic ci

- .storybook/preview-head.html
fix the theme and style css path used for story book previews
> build(components): storybook preview css path

- apps/docs-app/src/app/content/components/component-demos/markdown-navigator/demos/markdown-navigator-demo-basic/markdown-navigator-demo-basic.component.html
- apps/docs-app/src/app/documentation-tools/readme-loader/readme-loader.component.html
- libs/markdown-flavored/src/lib/flavored-markdown-loader/flavored-markdown-loader.component.html
- libs/markdown-flavored/src/lib/flavored-markdown-loader/flavored-markdown-loader.component.ts
- libs/markdown-flavored/src/lib/flavored-markdown.component.ts
Fixing an issue with markdown navigator which doesn't display links within lists if the links contain a `+` in their query params.
- Adding back `-` as a list character for CFM lists
- Making CFM lists opt-in via `useCfmList` input parameter. By default vanilla list will be used.
- using cfm within readme viewer for docs app
- Fix for #1987 - removing `/r` characters from markdown before parsing/conversion
Broken:
Fixed:
> fix(flavored-markdown): list display fixes, CRLF fix

- libs/components/src/side-sheet/side-sheet.scss
- libs/components/src/side-sheet/side-sheet.stories.js
- libs/components/src/side-sheet/side-sheet.ts
- package.json
Adding side sheet component to the web component library
- Added sidesheet component to the components library
- Added storybook for side sheet component
> feat(components): adding sidesheet component

- libs/components/src/icon/icon.stories.js
- libs/components/src/index.ts
- libs/components/src/snackbar/_snackbar.theme.scss
- libs/components/src/status-header/_status-header.theme.scss
- libs/components/src/status-header/status-header-base.ts
- libs/components/src/status-header/status-header-item.scss
- libs/components/src/status-header/status-header-item.ts
- libs/components/src/status-header/status-header.scss
- libs/components/src/status-header/status-header.stories.js
- libs/components/src/status-header/status-header.ts
- libs/components/src/tab/tab.stories.js
- libs/components/webpack.config.js
Pulling in the status header component done by @divrags 
- Added status header component 
- Added status header item component
> feat(components): adding @divrags status header component

- libs/components/src/index.ts
- libs/components/webpack.config.js
fix for the sidesheet web component not being exported in the build
- export as single module 
- export in general index bundle
> fix(components): exporting sidesheet in build

- libs/components/src/code-snippet/code-snippet.scss
- libs/components/src/code-snippet/code-snippet.spec.ts
- libs/components/src/code-snippet/code-snippet.stories.js
- libs/components/src/code-snippet/code-snippet.ts
- libs/components/src/index.ts
- libs/components/theme/_mixins.scss
- libs/components/theme/theme.scss
- libs/components/webpack.config.js
- libs/tokens/build/css/variables.css
- libs/tokens/build/js/variables.d.ts
- libs/tokens/build/js/variables.js
- libs/tokens/build/json/variables.json
- libs/tokens/build/scss/_variables.scss
- libs/tokens/src/color/code.json
- libs/tokens/src/color/text.json
Adding Code snippet web component to the web component library
Figma (needs td login)
https://www.figma.com/file/4qn8W9GCuhyNxEMBhMeahz/Code-samples?node-id=0%3A1&t=Rs15lTIuTGzTzrxQ-1
- Adding code snippet using [highlight.js](https://highlightjs.org/)
- Supports the common [34](https://highlightjs.org/static/demo) languages 
- Uses atom one light and dark theme
- Supports adding a title in the header and a slot for action
> feat(components): adding code snippet component

- libs/components/src/index.ts
- libs/components/src/text-lockup/text-lockup.scss
- libs/components/src/text-lockup/text-lockup.spec.ts
- libs/components/src/text-lockup/text-lockup.stories.js
- libs/components/src/text-lockup/text-lockup.ts
- libs/components/webpack.config.js
Adding text lock up component to display basic key value text anywhere
_**Using visuals pulled from this [figma](https://www.figma.com/file/ltYM4aeDULd3ec6Sd8Xvpk/Typography?node-id=2233%3A1034) (not official) **_
- Text lockup component with support for small and large scale
- Icon support for subtext
- State support for `active, positive, negative, caution`
- Trailing subtext support for to see the subtext on the bottom of the main text
> feat(components): adding text lockup component

- .github/workflows/chromatic.yml
- libs/components/.storybook/main.js
- libs/components/.storybook/preview-head.html
- libs/components/.storybook/preview.js
- libs/components/src/snackbar/snackbar.scss
Fixing the import path of the theme file for the components storybook preview. 
Note: see the broken css here https://teradata.github.io/covalent/docs/components/
> fix(components): adjusted import location of scss theme file

- libs/components/project.json
Vite was not copying the package.json asset like was webpack before.
Adding basic step to copy package.json into dist folder after building so npm knows to publish this directory
> fix(components): build fix for components not publishing to npm

- .vscode/settings.json
- libs/components/package.json
- libs/components/project.json
- libs/components/types.d.ts
- libs/components/vite.config.js
Adding back the typescript declaration files that Vite does not include when compiling ts
- adding back TS declarations
- removing `lit` and `mwc` as external deps so they also get included in the bundle for a better dev experience
- Add vscode setting to us typescript version from workspace over the ide default
> fix(components): adding back ts declaration files

- apps/docs-app/src/_teradata-branding.scss
- apps/docs-app/src/app/components/home/home.component.html
- apps/docs-app/src/app/components/home/home.component.scss
- apps/docs-app/src/app/components/shared/component-details/component-details-wrapper/content-details.component.html
- apps/docs-app/src/app/components/shared/component-details/component-hero/component-hero.component.scss
- apps/docs-app/src/app/components/shared/component-overview/component-overview.component.html
- apps/docs-app/src/app/components/shared/demo-tools/demo.component.scss
- apps/docs-app/src/app/components/shared/sidenav-content/sidenav-content.component.html
- apps/docs-app/src/app/content/components/component-demos/file-input/file-input.component.html
- apps/docs-app/src/app/content/docs/angular-material/angular-material.component.html
- apps/docs-app/src/app/content/docs/icons/icons.component.html
- apps/docs-app/src/app/content/docs/theme/theme.component.html
- apps/docs-app/src/app/content/utilities/content-details/content-details.component.html
- apps/docs-app/src/app/content/utilities/content-details/content-overview/content-overview.component.scss
- apps/docs-app/src/app/content/utilities/utilities-demos/animations/animations.component.html
- apps/docs-app/src/app/content/utilities/utilities-demos/directives/directives.component.html
- apps/docs-app/src/app/content/utilities/utilities-demos/functions/functions.component.html
- apps/docs-app/src/app/content/utilities/utilities-demos/pipes/pipes.component.html
- apps/docs-app/src/app/content/utilities/utilities-demos/utility-styles/utility-styles.component.html
- apps/docs-app/src/styles.scss
- libs/angular/breadcrumbs/src/breadcrumbs.component.spec.ts
- libs/angular/layout/src/navigation-drawer/navigation-drawer.component.scss
- libs/angular/side-sheet/_side-sheet.theme.scss
- libs/angular/side-sheet/src/side-sheet.scss
Adding better dark mode support to address #2023 
- removed a bunch of classes that are calling a color directly and replaced with themed color
- add secondary class to pull theme color
closes #2023
> fix(docs): adding better dark mode support

- libs/components/package.json
- libs/components/project.json
- libs/components/src/index.ts
Adjustments to the build config for consuming the library
- adding typings field to package.json
- creating directory before running build
- styles were not being exported
> fix(components): adjustments to consuming library

- apps/docs-app/src/app/content/components/component-demos/flavored-markdown/flavored-markdown.component.ts
- libs/markdown-flavored/src/lib/flavored-markdown.component.ts
We might want to use markdown syntax in table cells to show links, style text, or do other stuff.
This is handle automatically by showdown, but wasn't captured in our custom `TdFlavoredMarkdownTableComponent`.
- wrapping table cells in TdFlavoredMarkdownTableComponent with `<td-markdown>`
This fixes https://teradatacloud.atlassian.net/browse/CCP-2488
> fix: add support for markdown syntax in table cells

- libs/components/src/action-ribbon/action-ribbon.stories.js
This PR adds default label text in for 'Neutral' action ribbon
Fixes #2034
> fix(components): set default label text 

- libs/components/src/icon-radio/icon-radio-toggle.ts
- libs/components/src/icon-radio/icon-radio.scss
- libs/components/src/icon-radio/icon-radio.stories.js
Fixing the javascript error caused by the icon-radio component  
- using the render method from the base radio class 
- adjusting css to overwrite the base mdc styles
> fix(components): icon-radio rendering

- apps/docs-app/src/app/content/components/component-demos/flavored-markdown/flavored-markdown.component.html
- apps/docs-app/src/app/content/components/component-demos/flavored-markdown/flavored-markdown.component.ts
- apps/docs-app/src/app/content/components/component-demos/highlight/demos/highlight-demo-copy-code/highlight-demo-copy-code.component.html
- apps/docs-app/src/app/content/components/component-demos/highlight/demos/highlight-demo-ts/highlight-demo-ts.component.html
- apps/docs-app/src/app/content/components/component-demos/highlight/demos/highlight-demo.component.html
- libs/angular-highlight/_highlight-theme.scss
- libs/angular-highlight/src/lib/copy-code-button/copy-code-button.component.html
- libs/angular-highlight/src/lib/copy-code-button/copy-code-button.component.scss
- libs/angular-highlight/src/lib/copy-code-button/copy-code-button.component.ts
- libs/angular-highlight/src/lib/highlight.component.html
- libs/angular-highlight/src/lib/highlight.component.scss
- libs/angular-highlight/src/lib/highlight.component.ts
- libs/angular-highlight/src/lib/highlight.module.ts
- libs/markdown-flavored/src/lib/flavored-markdown.component.ts
Adding ability to toggle between raw and formatted code in syntax highlight component. Also updating theme with new colors and light mode.
- Added new parameters `toggleRawCode` and `rawToggleLabels` to flavored markdown
- Added new parameters `toggleRawButton` and `rawToggleLabels` to highlight component
- Added light mode theme to highlight component theme
> feat: add raw code toggle to highlight component and update highlight theme

- .github/workflows/release.yml
Adding `release/4.x.x` to github release workflow
> fix: add v4 to release workflow

- .github/workflows/release.yml
Pinning semantic-release@19.0.5 to work with node 16
> fix: pin semantic-release@19.0.5

- apps/docs-app/src/styles.scss
Fix for the code highlight in docs using only the light theme
> fix(docs): angular docs code highlight theme

- .github/workflows/ci.yml
- apps/docs-app/src/app/components/content-container/content-container.component.html
- apps/docs-app/src/app/components/content-container/content-container.component.ts
- apps/docs-app/src/app/components/content-container/content-container.module.ts
- libs/angular/layout/src/navigation-drawer/navigation-drawer.component.ts
Hiding the side nav on mobile for the angular docs app
> fix(docs): hide side nave on mobile

- libs/components/src/tree-list/tree-list-item.ts
- libs/components/src/tree-list/tree-list.ts
closes #2052
fixes JS error caused by code not checking for null values
> fix(components): tree list item js error

- libs/components/README.md
documentation update for components getting started
> Update components documentation

- libs/markdown-flavored/src/lib/flavored-markdown.component.ts
Correction to display correctly the tables when they are located inside a list
The change to render the tables correctly
closes #2074
> fix: issue 2074 - tables are rendered differently in a list

- libs/markdown/src/lib/markdown.component.scss
- libs/markdown/src/lib/markdown.component.ts
Correction for markdown tables alignment
Fix for the alignment in the markdown tables
> fix: correction in markdown table alignment

- apps/knapsack/project.json
fixing the knapsack build when using the NX commands
> build(knapsack): fixing knapsack deploy

- libs/tokens/src/color/deprecated/text.json
Updating the tokens value for the logo on background token
> fix(tokens): updating logo on background

- .github/workflows/ci.yml
- nx.json
security update to move from using read-write tokens for build cache in NX.
This new setup will leverage a read only token for consumers and use the read-write token only within the CI build
> build(nx): read only tokens visible and write tokens from secrets

- libs/markdown/src/lib/markdown.component.scss
closes #2063 
Adding external link icon for links in markdown parsers that use `target="_blank"`
> fix(markdown): external icon for target _blank

- apps/docs-app/src/app/app.component.html
- apps/docs-app/src/app/app.component.ts
- apps/docs-app/src/app/components/toolbar/toolbar.component.html
- apps/docs-app/src/app/components/toolbar/toolbar.component.ts
Fix to how we reference and set the active theme. Theming now will add its `active-theme` class to the body of the page
> fix(docs-app): adjusting how docs pulls active theme

- libs/angular-highlight/src/lib/highlight.component.scss
- libs/components/src/code-snippet/code-snippet.scss
- libs/components/src/theme/_mixins.scss
- libs/tokens/src/typography.json
Add support for Menlo font for coded text in components.
Closes https://github.com/Teradata/covalent/issues/2080
- Code snippet, Highlight and Code editor components support Menlo
> fix: add Menlo font to code snippet and highlight components

- libs/icons/covalent-icons.css
- libs/icons/covalent-icons.scss
- libs/icons/project.json
- package-lock.json
fix for exports not picking up the correct css file for tokens package
> fix(icons): fix path exports

- libs/components/package.json
- libs/components/src/badge/badge.scss
- libs/components/src/badge/badge.spec.ts
- libs/components/src/badge/badge.stories.js
- libs/components/src/badge/badge.ts
- libs/components/src/index.ts
- libs/components/src/theme/_mixins.scss
- libs/components/vite.config.js
Created a badge (`cv-badge`) web component.
- Badge component with the below properties:
- content
- size
- max
- verticalAlignment
- horizontalAlignment
- showZero
- hideBadge
> feat(components): create a badge web component

- libs/tokens/src/color/covalent-m3.json
- libs/tokens/src/color/deprecated/surface.json
- libs/tokens/src/color/deprecated/text.json
SCSS tokens which end with `%` are not showing up in the DOM.
- Remove the trailing `%` symbol in scss variables
> fix(tokens): remove % from scss variable names

- libs/components/package.json
- libs/components/src/icon-button-toggle/icon-button-toggle.scss
- libs/components/src/icon-button-toggle/icon-button-toggle.spec.ts
- libs/components/src/icon-button-toggle/icon-button-toggle.stories.js
- libs/components/src/icon-button-toggle/icon-button-toggle.ts
- libs/components/src/index.ts
- libs/components/vite.config.js
- package-lock.json
- package.json
Created a new web component called `cv-icon-button-toggle`.
It extends the functionality from [`mwc-icon-button-toggle`](https://www.npmjs.com/package/@material/mwc-icon-button-toggle/v/0.24.0-canary.8dff8894.0)
Icon button toggle component which can be toggled on/off and disabled.
It has the below properties:
- aria-label: Accessible label for the button.
- on: To toggle the button on/off.
- onIcon: Icon to display when on is true.
- offIcon: Icon to display when on is false.
- disabled: To disable the button.
- ariaLabelOn: aria-label of the button when on is true. If set, ariaLabelOff must also be set.
- ariaLabelOff: aria-label of the button when on is false. If set, ariaLabelOn must also be set.
> feat(icon-button-toggle): create new web component icon-button-toggle

- libs/angular-text-editor/src/lib/text-editor.component.scss
Style adjustment for text editor component to respect the light/dark themes
> style(text-editor): overriding default mde styles

- apps/knapsack/data/knapsack.pattern.button.json
- apps/knapsack/dist/meta/button/button.web-components-raE1x4tYL.spec.d.ts
- apps/knapsack/dist/meta/button/button.web-components-raE1x4tYL.spec.json
- apps/knapsack/dist/meta/knapsack.html-data.json
- libs/components/src/chips/chip-base.ts
- libs/components/src/chips/chip.scss
- libs/components/src/chips/chips.stories.js
1. Added missing `color` prop in knapsack for button component.
2. Added a `positive` variant for Chip item in storybook.
> docs(components): fix color issues in button and chip

- libs/components/index.html
- libs/components/src/app-shell/app-shell.stories.js
- libs/components/src/icon-button-toggle/icon-button-toggle.scss
- libs/components/src/icon-button-toggle/icon-button-toggle.ts
- libs/components/src/list/list-item.scss
- libs/components/src/list/nav-list-item.scss
Setting icon toggle button to be "filled" when toggled on
- icon filled when selected
- adding icon toggle to app shell story
https://github.com/Teradata/covalent/assets/3837706/8a597b69-228d-4960-9556-544a26ed6e22
> feat(components): adding fill to toggled on icon button

- libs/components/src/code-snippet/code-snippet.scss
- libs/components/src/code-snippet/code-snippet.ts
Padding adjustment and scrolling when a maxHeight is applied
https://github.com/Teradata/covalent/assets/3837706/f0c39218-99fc-4a2b-a333-8573b82ed016
> fix(components): padding adjustment and scrolling fix

- libs/components/src/app-shell/app-shell.scss
- libs/components/src/app-shell/app-shell.stories.js
- libs/components/src/app-shell/app-shell.ts
Adjustments to the appshell component to set a max width on the main content. Specs for the responsive appshell container can viewed [here](https://www.figma.com/file/KvXVAmYdCVAS7hzkOa73Em/Covalent-principles?type=design&node-id=7568-13372&mode=design&t=0FYXipNjcRzvzFCf-0). 
- Added a `fullWidth` attribute to allow the consumer to let the main content be 100% width
- Set a max width that is responsive
> feat(components): adding full width attribute to the appshell

- libs/components/src/code-snippet/code-snippet.ts
Removing white space from covalent code component that was causing extra space.
> fix(components): adjusting whitespace causing style issue

- libs/components/src/app-shell/app-shell.scss
- libs/components/src/app-shell/app-shell.ts
The help option panel is now resizable to the left, it can now scroll with a maximum width of 600 px. Help panel text wraps automatically
- This PR includes the functionality to make the Help Panel resizable
> fix(app-shell): enhancement to be resizable app-shell

- libs/components/src/app-shell/app-shell.scss
- libs/components/src/app-shell/app-shell.stories.js
- libs/components/src/app-shell/app-shell.ts
- package-lock.json
There was a conflict in the override firstUpdated() method, which caused a block in closing the nav-list menu. To avoid this blockage, the _startResizing method was removed. This resolved both issues: on one hand, the correct closing of the nav-list menu, and on the other hand, resizing to the default size of 320px for the help panel when double-clicking on the resize line.
- Fix the problem with the Hamburger Menu on Nav list Menu. 
- Tested using Covalent 8.12.1
NOTE : It was found that the line setTimeout(updateActionRibbon, 150) in the file app-shell.stories.js ; is causing the error "Uncaught TypeError: Cannot read properties of undefined (reading '0')". This line introduces a delay before executing updateActionRibbon to ensure that all elements and components are fully initialized. …
> fix(app-shell): fix nav-list menu

- libs/components/src/app-shell/app-shell.scss
- libs/components/src/app-shell/app-shell.stories.js
- libs/components/src/app-shell/app-shell.ts
Small fixes to works fine the Help Resizable  property..
- change the variable helpResizable instead resizing into the app-shell.stories.js
> fix(app-shell): small fix to works fine the resizable

- apps/knapsack/data/demos/demo.v3IaS3HWdf.json
- apps/knapsack/data/knapsack.pattern.list.json
- apps/knapsack/data/knapsack.pattern.naviigation-list-item.json
- apps/knapsack/dist/meta/knapsack.html-data.json
- apps/knapsack/dist/meta/ks-meta.json
- apps/knapsack/dist/meta/list/list.web-components-fObxCsu2i8.spec.d.ts
- apps/knapsack/dist/meta/list/list.web-components-fObxCsu2i8.spec.json
- apps/knapsack/dist/meta/naviigation-list-item/naviigation-list-item.web-components-Qtmmi7N-aL.spec.d.ts
- apps/knapsack/dist/meta/naviigation-list-item/naviigation-list-item.web-components-Qtmmi7N-aL.spec.json
- libs/components/index.html
- libs/components/src/app-shell/app-shell.stories.js
- libs/components/src/list/list.scss
- libs/components/src/list/nav-list-item.scss
moving the required `subNav` property from the list component scss to the `cv-navigation-item` component. This makes the styling for the subnav items to be more robust when wrapped with an other elements like an `a` tag
> feat(components): moving subnav property to nav-item component

- apps/docs-app/src/app/content/components/component-demos/dialogs/demos/dialogs-demo-basic/dialogs-demo-basic.component.html
- apps/docs-app/src/app/content/components/component-demos/dialogs/demos/dialogs-demo-basic/dialogs-demo-basic.component.ts
- apps/docs-app/src/app/content/components/components.ts
- libs/angular/dialogs/README.md
- libs/angular/dialogs/_dialog-theme.scss
- libs/angular/dialogs/src/dialog.component.html
- libs/angular/dialogs/src/dialog.component.scss
- libs/angular/dialogs/src/dialog.component.ts
- libs/angular/dialogs/src/dialogs.module.ts
- libs/angular/dialogs/src/public_api.ts
- libs/angular/dialogs/src/services/dialog.service.ts
- libs/angular/dialogs/src/status-dialog/status-dialog.component.html
- libs/angular/dialogs/src/status-dialog/status-dialog.component.scss
- libs/angular/dialogs/src/status-dialog/status-dialog.component.spec.ts
- libs/angular/dialogs/src/status-dialog/status-dialog.component.ts
- libs/angular/theming/_teradata-theme.scss
- libs/components/src/status-dialog/status-dialog.scss
Status dialog angular component.
- Angular component for status dialog
- Option to launch status dialog easily from DialogService.
> feat(status-dialog): angular component for status dialog

- .github/workflows/ci.yml
- apps/docs-app/src/styles.scss
- libs/markdown/src/lib/markdown-loader/markdown-loader.service.spec.ts
- libs/markdown/src/lib/markdown.component.spec.ts
- libs/markdown/src/lib/markdown.component.ts
Now markdown will work with both Absolute and Relative paths to allow for offline capabilities
- Accept Relative paths as well as Absolute paths
> fix(markdown): allow relative paths

- libs/components/src/list/list-item.scss
- libs/components/src/list/list.stories.js
Adding style to a list item with a disable property added
- styling in the base list component to set the color to us `--cv-theme-on-surface-38` when disabled
- icons use `--cv-theme-on-primary-container-16` token when disabled
- adjusted list stories in storybook
> fix(components): list item disabled

- libs/markdown/src/lib/markdown.component.spec.ts
- libs/markdown/src/lib/markdown.component.ts
Now markdown will work with both Absolute and Relative paths to allow for offline capabilities
- Accept Relative paths as well as Absolute paths
> fix(markdown):  allow relative paths

- libs/components/src/textfield/textfield.scss
Text size adjustment to place holder text size 
- adjusting placeholder text size
- this also fixes the issue where the floating label gets cutoff
> fix(components): adjusting textfield placeholder size

- libs/angular/dialogs/src/dialog.component.scss
- libs/angular/dialogs/src/resizable-draggable-dialog/resizable-draggable-dialog.ts
- libs/markdown/src/lib/markdown.component.ts
Fixes small bugs in 4.17.0 release
- Fixed another issue with markdown where links in a markdown file that link to other markdown files were not working when offline
- Fixed undesired uppercase of buttons for dialogs
- Fixed handle for markdown navigator window that wasn't displaying properly
> fix(markdown): relative href links in md and minor styling

- libs/components/src/app-shell/app-shell.ts
Adding delayed opening when hovering over app shell navigation
- Including a 250ms delay when user now hovers over the app shell when in collapsed mode
- Added same delay for closing app-shell which is also configurable
> feat(components): add delay to app shell navigation hover

- libs/components/src/list/nav-list-item.scss
- libs/components/src/list/nav-list-item.ts
Adjustment to expand/collapse nav item when its sub nav is active. Consumer will have to apply this styling and use `hasActivatedChild` property on the nav item when it's subnav item is activated.
```
[hasActivatedChild] {
--cv-list-item-background-color: var(--cv-theme-primary-24);
--cv-theme-on-surface: var(--cv-theme-primary);
}
cv-app-shell[open] cv-nav-list-item[hasActivatedChild]:not([subNav]) {
--cv-list-item-background-color:var(--cv-theme-on-surface-variant-8);
--cv-theme-on-surface: var(--cv-theme-on-surface-variant);
--cv-list-item-text-color: var(--cv-theme-on-surface-variant);
}
```
- added properties `--cv-list-item-background-color` and `--cv-list-item-text-color` to nav list item component
> fix(components): style fix for nav item when active

- libs/tokens/package.json
adding index.css as export path for tokens to allow importing for tokens through  commonJS system with `node_modules`
```javascript
import '@covalent/tokens/index.css';
```
> fix(tokens): adding index as pkg.json export

- libs/components/src/app-shell/app-shell.scss
Bottom margin on main card was conflicting with calc values in CSS for the card heights and causing a vertical scrollbar. This reverts that change.
> fix(styles): correct persistent unneeded vertical scrollbar

- libs/components/src/code-editor/code-editor.ts
- libs/components/src/icon-button/icon-button.scss
- libs/components/src/notebook-cell/notebook-cell.scss
- libs/components/src/notebook-cell/notebook-cell.stories.js
- libs/components/src/notebook-cell/notebook-cell.ts
- Fix drag and drop issues in notebook-cell component
- Remove draggable property for elements in the cell. This is causing issues during drag and drop.
- Replace the drag handler icon with an icon-button as per mocks.
- Stop bubbling unwanted editor events past the notebook-cell component which is also causing drag and drop issues.
https://github.com/user-attachments/assets/e4fcac80-a4fa-41d0-885e-c6db5b7526b3
> fix(notebook-cell): fix drag and drop issues

- apps/docs-app/src/app/content/components/component-demos/markdown/demos/markdown-demo-file-url/markdown-demo-file-url.component.html
- apps/docs-app/src/app/content/components/component-demos/markdown/demos/markdown-demo-file-url/markdown-demo-file-url.component.ts
- apps/docs-app/src/app/content/components/component-demos/markdown/demos/markdown-demo.component.html
- apps/docs-app/src/app/content/components/component-demos/markdown/demos/markdown-demo.module.ts
- libs/markdown-flavored/README.md
- libs/markdown/README.md
- Add a demo for file url handling in the `td-markdown` component
- Demo for handling file url clicks
> docs(markdown): add a demo for file url handling

- libs/components/src/list/nav-list-item.scss
- libs/components/src/list/nav-list-item.ts
Fix for nav item menu that is open initially when rendered
- using "inherit" value for when the content scrollheight is 0
> fix(components): fix to nav item when rendered initially open

- libs/components/src/notebook-cell/notebook-cell.scss
- libs/components/src/notebook-cell/notebook-cell.stories.js
- libs/components/src/notebook-cell/notebook-cell.ts
- With the current implementation, drag logic will be applied to the entire cell. This is causing issues with text selection, or scrolling of outputs.
- In order to prevent the entire cell component from being dragged, add a slot for drag handle where users can pass any component. They can add the drag logic to this slot.
- Add a slot called `drag-handle` in the notebook cell component
- Update notebook cell story
> fix(notebook-cell): add a slot for drag handle

- libs/components/src/textarea/textarea.stories.js
- libs/components/src/textfield/textfield.scss
- libs/components/src/textfield/textfield.stories.js
Fixing the disabled state for the outlined text field and area components
- Setting the outlined disabled state variables according to our [design principles ](https://www.figma.com/design/KvXVAmYdCVAS7hzkOa73Em/Covalent-Principles?m=auto&node-id=8066-24227)
> fix(components): color for disabled state

- libs/angular/breadcrumbs/src/breadcrumb/breadcrumb.component.scss
- libs/angular/breadcrumbs/src/breadcrumbs.component.ts
Overflowing breadcrumbs are not hidden on page load.
- Hide breadcrumbs based on the parent container size on page load
> fix(breadcrumbs): fix rendering issues on load

- apps/docs-app/src/app/content/components/component-demos/code-editor/demos/code-editor-demo-basic/code-editor-demo-basic.component.html
- apps/docs-app/src/app/content/components/component-demos/code-editor/demos/code-editor-demo-monaco/code-editor-demo-monaco.component.html
- apps/docs-app/src/app/content/components/component-demos/code-editor/demos/code-editor-demo-monaco/code-editor-demo-monaco.component.ts
- libs/angular-code-editor/src/lib/code-editor.component.ts
- libs/angular-code-editor/src/lib/editor.theme.ts
- libs/components/src/code-editor/code-editor.theme.ts
- libs/components/src/code-editor/code-editor.ts
Add covalent themes to angular code editor
- Add `cv-light` and `cv-dark` themes to angular-code-editor component
> fix(styles): add covalent theming to angular code editor

- libs/components/src/code-editor/code-editor.stories.js
- libs/components/src/code-editor/code-editor.ts
- libs/components/src/notebook-cell/notebook-cell.ts
Add a property to disable scroll in the code editor. The editor height will be dynamically set based on the content when this property is set to true.
- Add `disableScroll` boolean property in code-editor web component
> fix(code-editor): add disable scroll option for code editor

- apps/docs-app/src/app/content/components/component-demos/user-profile/demos/user-profile-demo-basic/user-profile-demo-basic.component.html
- apps/docs-app/src/app/content/components/component-demos/user-profile/demos/user-profile-demo-basic/user-profile-demo-basic.component.scss
- apps/docs-app/src/app/content/components/component-demos/user-profile/demos/user-profile-demo-basic/user-profile-demo-basic.component.ts
- apps/docs-app/src/app/content/components/component-demos/user-profile/demos/user-profile-demo-list-items/user-profile-demo-list-items.component.html
- apps/docs-app/src/app/content/components/component-demos/user-profile/demos/user-profile-demo-list-items/user-profile-demo-list-items.component.scss
- apps/docs-app/src/app/content/components/component-demos/user-profile/demos/user-profile-demo-list-items/user-profile-demo-list-items.component.ts
- libs/angular/common/_common-theme.scss
- libs/angular/menu/src/menu.component.html
- libs/angular/menu/src/menu.component.scss
- libs/angular/theming/_teradata-theme.scss
- libs/angular/user-profile/README.md
- libs/angular/user-profile/src/user-profile-menu/user-profile-menu.component.html
- libs/angular/user-profile/src/user-profile-menu/user-profile-menu.component.scss
- libs/markdown-flavored/_flavored-markdown-theme.scss
Style adjustments for the user menu profile component
- Reduced all previous styles no longer needed since angular material update
- Updated angular demo for user profile component
> feat(user-menu): fixed styles for user menu profile

- libs/angular-highlight/package.json
Fix minor issue with @covalent/highlight version 5.0.2 and its dependency on @angular/cdk.
In this case "0.0.0-NG" is converted to 14.2.12, but that version doesn't exist for @angular/cdk.  It should be using 0.0.0-MATERIAL which translates to the expected version 14.2.7.
Making this change will allow us to remove an override in our package.json:
```
"overrides": {
"@covalent/highlight": {
"@angular/cdk": "14.2.7"
}
}
```
I think this same change should also be made to the main branch.
> fix(deps): correct version of @angular/cdk (14.2.7 instead of 14.2.12)

- libs/components/package.json
- libs/components/src/icon-lockup/icon-lockup.scss
- libs/components/src/icon-lockup/icon-lockup.spec.ts
- libs/components/src/icon-lockup/icon-lockup.stories.js
- libs/components/src/icon-lockup/icon-lockup.ts
- libs/components/src/index.ts
- libs/components/vite.config.js
Add `cv-icon-lockup` component to the library. It displays text and icon side by side.
Design spec: [Figma](https://www.figma.com/design/KvXVAmYdCVAS7hzkOa73Em/Covalent-Principles?node-id=8401-43059&node-type=instance&m=dev)
`cv-icon-lockup` component with the below properties:
- **covalentIcon**: (Boolean) - Determines whether the icon is a Covalent icon. Default is false.
- **filledIcon**: (Boolean) - Indicates if the icon is filled. Default is false.
- **icon**: (String) - Specifies the icon to display. Default is an empty string ''.
- **scale**: (String) - Controls the scale of the component, affecting font-size and icon size. The default is "body1", but other values can be used to scale the component.
- **state**: (String) - Defines the state of the component, allowing for different …
> feat(icon-lockup): add icon lockup component

- apps/docs-app/src/styles.scss
- libs/markdown-navigator/_markdon-navigator-theme.scss
Fix the following error when using `@include markdown-navigator.covalent-markdown-navigator-typography($fontConfig);`
```
SassError: $map: null is not a map.
╷
10 │   @return map.get(map.get($config, $level), $name);
│           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
node_modules/@angular/material/core/typography/_typography-utils.scss 10:11   -mat-get-type-value()
node_modules/@angular/material/core/typography/_typography-utils.scss 17:11   font-size()
node_modules/@angular/material/core/typography/_typography-utils.scss 92:14   typography-level()
node_modules/@covalent/markdown-navigator/_markdon-navigator-theme.scss 10:7  covalent-markdown-navigator-typography()
```
- Replace `headline` ([Material 14 typography level](https://v14.material.angular.io/guide/typography#typography-level …
> fix: covalent-markdown-navigator-typography for Angular Material 15

- libs/markdown-navigator/src/markdown-navigator.component.html
Fix styling issue in markdown-navigator
Fix matListItem directives used in markdown-navigator per [Material docs](https://v15.material.angular.io/guide/mdc-migration#list)
> fix(markdown-navigator): matListItem directives for Angular Material 15

- libs/components/src/icon-checkbox/icon-checkbox.scss
Fix the notch color and checkmark color of icon checkbox for light and dark themes.
**Issue:**
- Change notch and checkmark colors for icon checkbox
> fix(components): fix icon-checkbox notch color

- apps/knapsack/data/blocks/block.3nK9KuZ4DN.json
- apps/knapsack/data/blocks/block.5xYWkMJtI.json
- apps/knapsack/data/blocks/block.7TZEfGqFM.json
- apps/knapsack/data/blocks/block.A4rHmg9Khg.json
- apps/knapsack/data/blocks/block.Ew3EmXiXyW.json
- apps/knapsack/data/blocks/block.K4Bfb-xLFz.json
- apps/knapsack/data/blocks/block.KfeIuYKj2w.json
- apps/knapsack/data/blocks/block.KpBSWEGwUa.json
- apps/knapsack/data/blocks/block.M27kwgYyE.json
- apps/knapsack/data/blocks/block.NTmTFKxXmZ.json
- apps/knapsack/data/blocks/block.O2FSrtamNm.json
- apps/knapsack/data/blocks/block.QUPzNPWapk.json
- apps/knapsack/data/blocks/block.UXLjbRrKsm.json
- apps/knapsack/data/blocks/block.Urkj-jpFb.json
- apps/knapsack/data/blocks/block.Y-JVxTUya.json
- apps/knapsack/data/blocks/block.a1XY2Aqt3.json
- apps/knapsack/data/blocks/block.e0PZuHL0Fl.json
- apps/knapsack/data/blocks/block.f-TlOFP3R8.json
- apps/knapsack/data/blocks/block.iFOVuyz8Pc.json
- apps/knapsack/data/blocks/block.jDBUIKk744.json
- apps/knapsack/data/blocks/block.ne8zZdjDIn.json
- apps/knapsack/data/blocks/block.qebw1cvH7j.json
- apps/knapsack/data/blocks/block.rrrSJEFzUH.json
- apps/knapsack/data/blocks/block.ruEwieJfwN.json
- apps/knapsack/data/blocks/block.u-2Q9Ua9Z4.json
- apps/knapsack/data/blocks/block.yyvAnHItNj.json
- apps/knapsack/data/blocks/block.z9Yo6rbBdE.json
- apps/knapsack/data/knapsack.custom-page.adapting-tone-by-situation.yml
- apps/knapsack/data/knapsack.navs.yml
Getting back the "Adapting tone by situation" page that was lost in a previous merge
- Restoring the adapting tone page and its content blocks under Voice and Tone section
> docs(knapsack): getting back adapting tone page

- apps/knapsack/data/knapsack.asset-sets.json
- apps/knapsack/dist/meta/ks-meta.json
using default id from knapsack documentation. This seems to fix the reference issue causing all of the icons to fail
- adjusted the default id for the light theme per knapsack documentation
> docs(knapsack): fix to knapsack asset set reference

- libs/angular/dynamic-menu/src/dynamic-menu-item/dynamic-menu-item.component.html
- libs/angular/dynamic-menu/src/dynamic-menu-item/dynamic-menu-link/dynamic-menu-link.component.html
- libs/angular/dynamic-menu/src/dynamic-menu-item/dynamic-menu-link/dynamic-menu-link.component.scss
Adjusting the stylling for the dynamic menu item when its set to open in a new tab
- Fix styling for link opening in new tab
> fix(angular): fixing dynamic menu open in new tab

- apps/knapsack/dist/meta/ks-meta.json
- apps/knapsack/public/ks-overrides.css
This pull request includes changes to the `apps/knapsack/public/ks-overrides.css` file to improve the layout and responsiveness of the application. The most important changes include adding HTML to the body selector for background color consistency and introducing new CSS rules to ensure certain elements have appropriate minimum width and height based on their parent elements.
* Added `html` to the `body` selector to ensure the background color is applied consistently across the entire page.
* Introduced a new CSS rule for elements with the class `knapsack-wrapper` and `knapsack-pattern-direct-parent` to ensure they have a minimum width and height of 100vw and 100vh respectively when they contain specific child elements like `cv-action-ribbon`, `cv-top-app-bar`, or `cv-toolbar`.
* Added …
> style(knapsack): adjusting style overrides for new update

- libs/components/src/alert/alert-base.ts
- libs/components/src/alert/alert.spec.ts
This pull request includes several changes to the `AlertBase` class in the `libs/components/src/alert/alert-base.ts` file to enhance its functionality and maintainability. The most important changes include adding a `ResizeObserver` to handle element resizing, updating the `render` method for better readability, and minor code formatting improvements.
* Added a `ResizeObserver` to the `AlertBase` class to observe and handle element resizing. This includes initializing the observer in the constructor, updating the `currentWidth` state, and handling cleanup in the `disconnectedCallback` method. [[1]](diffhunk://#diff-a57ce2a869eba60e2f74c61a2ff4654f9799ad1942a367eb3f41602c59d49124R46-R65) [[2]](diffhunk://#diff-a57ce2a869eba60e2f74c61a2ff4654f9799ad1942a367eb3f41602c59d49124R168-R169) …
> fix(components): adjusting the height layout of alert on resize

- libs/components/src/alert/alert-base.ts
Fixing import required for icon used in the alert banner
> fix(components): import fix for icon in alert

- libs/angular-dynamic-forms/src/lib/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.ts
There was a regression in the imports that caused the angular dynamic forms datepicker icon to not display, so it wasn't possible to open the datepicker.
This fixes [2467](https://github.com/Teradata/covalent/issues/2467)
Replaced `MatFormField, MatInput, MatLabel, MatError, MatHint` component imports with `MatFormFieldModule, MatInputModule`
The issue:
> fix(angular-dynamic-forms): change dynamic datepicker imports

- apps/knapsack/data/knapsack.pattern.menu-2auajeekzb.json
Copy web component tab from old menu doc to new one.
Adds the web components tab to the new Menu doc, seen here:
> docs(knapsack): copy web component tab to new menu doc

- .storybook/theme/theme.scss
- libs/components/src/chips/chip.scss
- libs/components/src/text-lockup/text-lockup.ts
Updating the chip styling to use the correct tokens
> style(theme): update chip token values

- README.md
This PR improves the README.md file with several formatting and content enhancements to make it more professional and user-friendly.
- Changed H2 title to H1 for proper document structure
- Fixed typo: 'rely up that support' → 'rely on that support'
- Added bash language annotation to Chromatic code block
- Improved description wording for better clarity and friendliness
- Added colons to setup instructions for better readability
N/A - Documentation changes only
> docs: improve README formatting and content

- .github/workflows/ci.yml
- libs/angular-code-editor/src/lib/code-editor.component.ts
- package-lock.json
- package.json
Upgrade monaco editor to the latest version for covalent 6.x.x version. This version is being used by Lake and needs to be updated to address security concerns.
[CCP-10806](https://teradata-pe.atlassian.net/browse/CCP-10806)
- Upgrade monaco-editor to v0.52.2
- Pass an empty string to editor's setValue method if null values are passed.
> feat(code-editor): upgrade monaco-editor in covalent v6.x.x

- .github/workflows/release.yml
Update checkout and setup-node actions to v4 to avoid caching issues during release.
- Update actions/checkout@v4 and actions/setup-node@v4
Fix for this issue:
> Fix/release GitHub workflow for v6.x.x

- libs/components/src/icon-radio/icon-radio.scss
- libs/components/src/icon-radio/icon-radio.stories.js
- Need the ability to support text only variants of `cv-radio-icon` as part of [VAC-2545](https://teradata-pe.atlassian.net/browse/VAC-2545).
- We can achieve this by not providing the `icon` slot. But the existing component only supports centrally aligned content. This change provides the ability to set the horizontal, vertical and text alignment of the content within `cv-radio-icon` 
- Added new custom CSS properties to change alignment:
- `--cv-icon-radio-horizontal-alignment`: sets the horizontal alignment of content
- `--cv-icon-radio-vertical-alignment`: sets the vertical alignment of content
- `--cv-icon-radio-text-alignment`: sets the text alignment of content
> fix(icon-radio): add ability to change text alignment

- libs/components/src/app-shell/app-shell.scss
- libs/components/src/app-shell/app-shell.stories.js
- libs/components/src/divider/divider.component.scss
- libs/components/src/divider/divider.stories.js
Adding some adjustment to the divider when used within the appshell navigation. Also adjusting the storybook layouts to integrate better with our current components
- Adjusted divider when used in apshell navigation area
- Added better story layout for divider to show all examples
> feat(divider): enhance divider styles and update stories layout

- libs/components/src/app-shell/app-shell.stories.js
- libs/components/src/select/select.scss
- libs/components/src/select/select.stories.js
- libs/components/src/select/select.ts
Adding text style and variant to support two lines for the select component.
- adding the property `text` that removes default fill style
- adding `twoline` variant that will enable space for a `secondary` slot
- updated select storybook with two line varient and text style updates
> feat(components): adding text style to select

- libs/angular/common/src/directives/web-components/form-control.directive.spec.ts
- libs/angular/common/src/directives/web-components/form-control.directive.ts
- `CovalentTextfieldValueAccessorDirective` respects the `updateOn` strategy set in the form control
- Values in the form control are updated based on the `updateOn` strategy
> fix: support updateOn strategy for form controls 10.x.x
